<?php

declare(strict_types=1);

namespace App\Search;

use App\Database\Connection;

/**
 * Construit App\Search\PrefixAvecThreeLettersLinks depuis list_counts (list_type
 * 'start_with_triple'), meme principe que App\Search\AvecThreeLettersLinksBuilder (variante SANS
 * commencant) -- une seule requete triviale, aucun calcul sur `terms` au runtime.
 *
 * list_key est toujours "{prefixe}:{lettre1}:{lettre2}:{lettre3}" avec
 * lettre1 < lettre2 < lettre3 ALPHABETIQUEMENT. Depuis une page palier 2 "commencant/{X}/
 * avec/{Y}/{Z}", la paire source (Y,Z, deja triee) peut occuper TROIS positions differentes
 * dans le triplet trie stocke selon ou tombe le partenaire -- meme OR a trois motifs que
 * AvecThreeLettersLinksBuilder.
 */
final class PrefixAvecThreeLettersLinksBuilder
{
    /**
     * Doublons de contenu avec l'une des trois pages PARENTES palier 2 (D-045, meme methodologie
     * que App\Search\AvecThreeLettersLinksBuilder::DUPLICATE_PARENT_KEYS). Calculee
     * PROGRAMMATIQUEMENT (comparaison directe list_counts, chargement en memoire par prefixe),
     * 3 810 cles trouvees sur les 44 023 candidats reels -- voir docs/DECISIONS.md D-045.
     *
     * @var list<string>
     */
    private const DUPLICATE_PARENT_KEYS = [
        'A:B:G:W', 'A:B:Q:U', 'A:B:R:W', 'A:C:Q:U', 'A:C:S:W', 'A:D:E:Z',
        'A:D:Q:U', 'A:E:F:Z', 'A:E:H:J', 'A:E:J:Y', 'A:E:L:W', 'A:E:N:W',
        'A:E:P:W', 'A:E:P:Z', 'A:E:Q:U', 'A:F:K:R', 'A:F:Q:U', 'A:G:I:W',
        'A:G:K:W', 'A:G:Q:U', 'A:G:R:W', 'A:H:I:J', 'A:H:J:N', 'A:H:P:W',
        'A:H:Q:U', 'A:I:J:Q', 'A:I:K:Q', 'A:I:K:V', 'A:I:P:W', 'A:I:Q:U',
        'A:J:L:Y', 'A:J:N:Y', 'A:J:O:Y', 'A:J:Q:U', 'A:J:U:Y', 'A:K:O:X',
        'A:K:Q:U', 'A:K:T:V', 'A:L:Q:U', 'A:M:Q:U', 'A:N:P:W', 'A:N:Q:U',
        'A:O:Q:U', 'A:P:Q:U', 'A:P:R:W', 'A:Q:R:U', 'A:Q:S:U', 'A:Q:T:U',
        'A:Q:U:V', 'A:Q:U:X', 'A:Q:U:Y', 'A:Q:U:Z', 'B:A:F:Y', 'B:A:J:K',
        'B:A:J:Q', 'B:A:J:Y', 'B:A:K:W', 'B:A:P:X', 'B:C:J:K', 'B:C:R:W',
        'B:D:E:W', 'B:D:I:W', 'B:D:L:W', 'B:D:N:W', 'B:D:O:W', 'B:D:Q:U',
        'B:D:W:Y', 'B:E:F:J', 'B:E:F:V', 'B:E:H:Q', 'B:E:J:Y', 'B:E:J:Z',
        'B:E:K:W', 'B:E:P:Q', 'B:E:P:V', 'B:E:Q:X', 'B:E:W:X', 'B:E:W:Y',
        'B:E:X:Z', 'B:F:I:J', 'B:F:I:Q', 'B:F:I:V', 'B:F:O:V', 'B:F:Q:U',
        'B:G:O:W', 'B:G:Q:U', 'B:H:I:W', 'B:H:J:O', 'B:I:J:P', 'B:I:J:V',
        'B:I:J:X', 'B:I:P:X', 'B:I:W:X', 'B:I:W:Y', 'B:I:W:Z', 'B:J:K:L',
        'B:J:O:P', 'B:J:O:Y', 'B:J:P:U', 'B:J:Q:U', 'B:J:R:Y', 'B:J:U:X',
        'B:K:Q:U', 'B:K:R:W', 'B:L:O:W', 'B:L:W:X', 'B:L:W:Y', 'B:N:W:Y',
        'B:O:U:W', 'B:O:W:X', 'B:O:W:Y', 'B:P:U:V', 'B:Q:R:U', 'B:Q:U:V',
        'B:Q:U:X', 'B:Q:U:Y', 'B:Q:U:Z', 'B:R:W:X', 'B:S:W:X', 'B:U:W:X',
        'C:A:H:J', 'C:A:J:K', 'C:A:J:Y', 'C:A:K:X', 'C:A:W:Z', 'C:B:J:Y',
        'C:B:Q:U', 'C:D:E:K', 'C:D:I:K', 'C:D:I:W', 'C:D:J:Y', 'C:D:K:R',
        'C:D:O:W', 'C:D:R:W', 'C:E:F:K', 'C:E:F:Z', 'C:E:H:J', 'C:E:J:P',
        'C:E:J:Y', 'C:E:J:Z', 'C:E:K:Q', 'C:E:K:V', 'C:E:K:X', 'C:E:K:Z',
        'C:E:Q:W', 'C:E:Q:X', 'C:E:V:Z', 'C:E:W:Z', 'C:E:X:Z', 'C:F:I:J',
        'C:F:J:O', 'C:F:K:O', 'C:F:O:W', 'C:G:I:W', 'C:G:J:N', 'C:G:J:O',
        'C:G:Q:U', 'C:H:I:J', 'C:H:J:Y', 'C:H:Q:U', 'C:I:J:Y', 'C:I:K:Q',
        'C:I:K:V', 'C:I:K:X', 'C:J:K:R', 'C:J:N:V', 'C:J:O:V', 'C:J:O:X',
        'C:J:P:T', 'C:J:R:Y', 'C:J:S:Y', 'C:J:T:V', 'C:J:U:X', 'C:K:N:X',
        'C:K:O:Q', 'C:K:Q:U', 'C:K:T:V', 'C:K:T:X', 'C:K:U:X', 'C:L:Q:U',
        'C:L:Q:W', 'C:L:W:Z', 'C:M:Q:U', 'C:N:Q:W', 'C:O:Q:W', 'C:O:W:X',
        'C:O:X:Z', 'C:P:Q:U', 'C:P:W:X', 'C:Q:R:U', 'C:Q:S:W', 'C:Q:U:V',
        'C:Q:U:W', 'C:Q:U:X', 'C:Q:U:Y', 'C:Q:U:Z', 'D:A:J:K', 'D:A:J:Y',
        'D:A:K:X', 'D:A:M:W', 'D:B:E:P', 'D:B:E:Q', 'D:B:E:X', 'D:B:Q:U',
        'D:B:R:W', 'D:C:K:X', 'D:E:F:H', 'D:E:F:K', 'D:E:F:V', 'D:E:F:W',
        'D:E:F:X', 'D:E:F:Z', 'D:E:H:Q', 'D:E:H:X', 'D:E:J:K', 'D:E:J:Q',
        'D:E:J:X', 'D:E:J:Y', 'D:E:J:Z', 'D:E:K:L', 'D:E:K:P', 'D:E:K:Q',
        'D:E:K:V', 'D:E:K:X', 'D:E:M:W', 'D:E:P:V', 'D:E:P:Z', 'D:E:Q:U',
        'D:E:Q:V', 'D:E:Q:X', 'D:E:Q:Y', 'D:E:W:Z', 'D:E:X:Z', 'D:F:I:W',
        'D:F:J:O', 'D:F:K:W', 'D:F:Q:U', 'D:G:Q:U', 'D:H:Q:U', 'D:I:J:V',
        'D:I:J:X', 'D:I:Q:U', 'D:I:Q:X', 'D:J:K:M', 'D:J:K:O', 'D:J:K:R',
        'D:J:K:Y', 'D:J:M:Y', 'D:J:N:X', 'D:J:O:Q', 'D:J:O:X', 'D:J:O:Y',
        'D:J:Q:U', 'D:J:R:Y', 'D:J:S:X', 'D:J:U:X', 'D:K:N:Q', 'D:K:Q:U',
        'D:K:T:X', 'D:K:U:X', 'D:L:Q:U', 'D:M:Q:U', 'D:M:S:W', 'D:N:Q:U',
        'D:O:Q:U', 'D:P:Q:U', 'D:Q:S:U', 'D:Q:T:U', 'D:Q:U:V', 'D:Q:U:X',
        'D:Q:U:Y', 'D:Q:U:Z', 'D:U:V:X', 'E:A:B:W', 'E:A:G:K', 'E:A:K:V',
        'E:A:K:X', 'E:A:Q:U', 'E:A:W:X', 'E:B:H:K', 'E:B:I:K', 'E:B:K:L',
        'E:B:K:O', 'E:B:Q:U', 'E:B:R:W', 'E:B:S:W', 'E:B:W:X', 'E:C:F:J',
        'E:C:F:K', 'E:C:H:W', 'E:C:I:W', 'E:C:K:W', 'E:C:Q:U', 'E:D:I:K',
        'E:D:I:W', 'E:D:Q:U', 'E:F:I:J', 'E:F:J:T', 'E:F:K:L', 'E:F:K:N',
        'E:F:K:O', 'E:F:K:R', 'E:F:K:T', 'E:F:K:U', 'E:F:Q:U', 'E:G:K:M',
        'E:G:K:N', 'E:G:K:S', 'E:G:Q:U', 'E:H:I:W', 'E:H:J:N', 'E:H:J:O',
        'E:H:Q:U', 'E:H:S:W', 'E:I:K:Q', 'E:I:K:V', 'E:I:K:W', 'E:I:L:W',
        'E:I:Q:U', 'E:I:W:Y', 'E:J:N:P', 'E:J:P:U', 'E:J:U:X', 'E:K:L:V',
        'E:K:N:V', 'E:K:O:Q', 'E:K:P:Q', 'E:K:Q:R', 'E:K:Q:T', 'E:K:Q:U',
        'E:K:Q:Y', 'E:K:R:W', 'E:K:S:V', 'E:K:T:Y', 'E:K:V:X', 'E:L:Q:U',
        'E:L:W:Y', 'E:M:O:W', 'E:M:Q:U', 'E:M:S:W', 'E:N:Q:U', 'E:O:Q:U',
        'E:O:W:Y', 'E:Q:R:U', 'E:Q:S:U', 'E:Q:T:U', 'E:Q:U:V', 'E:Q:U:X',
        'E:Q:U:Y', 'E:Q:U:Z', 'E:R:W:Y', 'E:S:W:X', 'E:S:W:Y', 'F:A:B:H',
        'F:A:J:X', 'F:A:P:X', 'F:A:W:Y', 'F:B:E:V', 'F:B:E:W', 'F:B:E:Z',
        'F:B:K:P', 'F:B:O:P', 'F:B:O:V', 'F:B:O:Y', 'F:B:Q:U', 'F:D:E:Q',
        'F:D:E:V', 'F:D:I:Q', 'F:D:I:V', 'F:D:Q:U', 'F:E:G:Q', 'F:E:G:Z',
        'F:E:H:V', 'F:E:J:M', 'F:E:J:V', 'F:E:J:X', 'F:E:J:Z', 'F:E:K:M',
        'F:E:K:Q', 'F:E:K:V', 'F:E:K:X', 'F:E:K:Z', 'F:E:M:Q', 'F:E:M:W',
        'F:E:M:Z', 'F:E:P:V', 'F:E:P:X', 'F:E:P:Z', 'F:E:Q:U', 'F:E:Q:V',
        'F:E:Q:X', 'F:E:Q:Y', 'F:E:Q:Z', 'F:E:V:Z', 'F:E:W:Z', 'F:E:X:Z',
        'F:E:Y:Z', 'F:G:I:Q', 'F:G:I:V', 'F:G:J:U', 'F:G:K:L', 'F:G:K:O',
        'F:G:P:X', 'F:G:Q:U', 'F:H:K:L', 'F:H:P:X', 'F:I:K:P', 'F:I:K:Q',
        'F:I:K:V', 'F:I:P:X', 'F:I:Q:V', 'F:I:Q:X', 'F:I:Q:Y', 'F:I:W:Y',
        'F:J:M:X', 'F:J:N:X', 'F:J:O:X', 'F:J:R:Z', 'F:J:T:X', 'F:J:U:X',
        'F:K:L:P', 'F:K:L:Q', 'F:K:L:V', 'F:K:M:V', 'F:K:N:V', 'F:K:N:Y',
        'F:K:O:P', 'F:K:O:Q', 'F:K:O:V', 'F:K:O:X', 'F:K:Q:R', 'F:K:Q:U',
        'F:K:S:V', 'F:K:T:V', 'F:K:U:X', 'F:L:P:X', 'F:L:Q:U', 'F:M:Q:U',
        'F:N:O:W', 'F:N:Q:U', 'F:O:P:X', 'F:O:Q:U', 'F:O:Q:Y', 'F:O:W:Z',
        'F:P:R:X', 'F:Q:R:U', 'F:Q:R:X', 'F:Q:R:Y', 'F:Q:T:U', 'F:Q:T:X',
        'F:Q:U:V', 'F:Q:U:X', 'F:Q:U:Y', 'F:Q:U:Z', 'F:R:W:Y', 'G:A:C:J',
        'G:A:C:W', 'G:A:D:J', 'G:A:J:L', 'G:A:J:M', 'G:A:J:Q', 'G:A:K:W',
        'G:A:K:X', 'G:A:K:Y', 'G:A:Q:U', 'G:A:Q:V', 'G:A:W:Y', 'G:B:E:F',
        'G:B:E:W', 'G:B:E:Z', 'G:B:I:Q', 'G:B:I:W', 'G:B:O:P', 'G:B:Q:U',
        'G:B:R:W', 'G:B:S:W', 'G:B:U:X', 'G:C:E:W', 'G:C:I:J', 'G:C:J:Q',
        'G:C:J:S', 'G:C:K:W', 'G:C:Q:U', 'G:C:R:W', 'G:C:U:W', 'G:D:E:K',
        'G:D:E:Q', 'G:D:F:I', 'G:D:Q:U', 'G:D:U:X', 'G:E:F:H', 'G:E:F:Q',
        'G:E:F:X', 'G:E:F:Z', 'G:E:H:Q', 'G:E:H:W', 'G:E:H:X', 'G:E:J:M',
        'G:E:J:Z', 'G:E:K:Z', 'G:E:L:Q', 'G:E:P:Q', 'G:E:P:V', 'G:E:Q:U',
        'G:E:Q:V', 'G:E:Q:X', 'G:E:Q:Y', 'G:E:Q:Z', 'G:E:V:Z', 'G:E:W:X',
        'G:E:W:Y', 'G:E:W:Z', 'G:E:X:Z', 'G:F:H:I', 'G:F:H:O', 'G:F:I:Q',
        'G:F:I:V', 'G:F:Q:U', 'G:F:U:X', 'G:H:I:W', 'G:H:K:Y', 'G:H:Q:U',
        'G:H:U:W', 'G:H:U:X', 'G:I:J:Q', 'G:I:K:X', 'G:I:Q:U', 'G:I:Q:V',
        'G:I:Q:X', 'G:I:W:X', 'G:J:O:Q', 'G:J:Q:S', 'G:J:Q:U', 'G:K:M:Y',
        'G:K:N:Y', 'G:K:O:P', 'G:K:T:X', 'G:K:U:X', 'G:L:Q:U', 'G:L:W:X',
        'G:M:N:W', 'G:M:Q:U', 'G:N:Q:U', 'G:O:Q:U', 'G:O:Q:X', 'G:O:W:X',
        'G:P:Q:U', 'G:Q:R:U', 'G:Q:S:U', 'G:Q:T:U', 'G:Q:U:V', 'G:Q:U:X',
        'G:Q:U:Y', 'G:Q:U:Z', 'G:R:W:X', 'G:R:W:Z', 'G:S:W:X', 'G:T:W:Y',
        'G:U:X:Y', 'G:U:X:Z', 'H:A:B:J', 'H:A:F:K', 'H:A:F:V', 'H:A:J:K',
        'H:A:J:M', 'H:A:J:Z', 'H:A:K:X', 'H:A:K:Z', 'H:A:M:W', 'H:A:Q:U',
        'H:B:C:W', 'H:B:E:F', 'H:B:E:P', 'H:B:E:W', 'H:B:F:I', 'H:B:F:L',
        'H:B:F:O', 'H:B:F:R', 'H:B:F:T', 'H:B:I:J', 'H:B:O:W', 'H:B:Q:U',
        'H:B:R:W', 'H:B:S:W', 'H:B:T:W', 'H:C:E:J', 'H:C:E:W', 'H:C:F:K',
        'H:C:F:V', 'H:C:J:K', 'H:C:J:N', 'H:C:J:O', 'H:C:J:U', 'H:C:J:Z',
        'H:C:K:X', 'H:C:O:W', 'H:C:Q:U', 'H:C:T:W', 'H:D:E:Q', 'H:D:J:Y',
        'H:D:Q:U', 'H:D:Q:W', 'H:E:F:Q', 'H:E:F:V', 'H:E:F:Z', 'H:E:G:Q',
        'H:E:G:V', 'H:E:G:W', 'H:E:G:Z', 'H:E:J:K', 'H:E:J:L', 'H:E:J:N',
        'H:E:J:O', 'H:E:J:T', 'H:E:J:U', 'H:E:J:Y', 'H:E:J:Z', 'H:E:K:Q',
        'H:E:K:X', 'H:E:K:Z', 'H:E:M:Q', 'H:E:M:W', 'H:E:N:W', 'H:E:P:Q',
        'H:E:Q:U', 'H:E:Q:V', 'H:E:Q:W', 'H:E:Q:X', 'H:E:Q:Y', 'H:E:Q:Z',
        'H:E:R:W', 'H:E:T:W', 'H:E:V:X', 'H:E:V:Z', 'H:E:W:Y', 'H:E:W:Z',
        'H:E:Y:Z', 'H:F:K:L', 'H:F:K:R', 'H:F:K:T', 'H:F:O:V', 'H:F:O:X',
        'H:F:Q:R', 'H:F:Q:U', 'H:F:R:V', 'H:F:T:V', 'H:G:I:W', 'H:G:K:N',
        'H:G:M:W', 'H:G:N:W', 'H:G:Q:U', 'H:I:K:Q', 'H:I:K:V', 'H:I:M:W',
        'H:I:Q:U', 'H:I:Q:V', 'H:I:W:Z', 'H:J:K:M', 'H:J:K:O', 'H:J:K:Z',
        'H:J:L:O', 'H:J:L:S', 'H:J:L:T', 'H:J:L:U', 'H:J:M:Z', 'H:J:N:O',
        'H:J:O:T', 'H:J:O:U', 'H:J:O:Y', 'H:J:O:Z', 'H:J:R:Y', 'H:J:S:U',
        'H:J:T:U', 'H:J:T:Y', 'H:K:O:X', 'H:K:Q:R', 'H:K:Q:U', 'H:K:T:X',
        'H:K:U:X', 'H:L:O:W', 'H:L:Q:U', 'H:L:Q:W', 'H:L:W:Z', 'H:M:N:W',
        'H:M:Q:U', 'H:M:W:Y', 'H:N:Q:U', 'H:N:W:Z', 'H:O:Q:U', 'H:O:Q:W',
        'H:O:W:Z', 'H:P:Q:U', 'H:Q:R:U', 'H:Q:S:U', 'H:Q:S:W', 'H:Q:T:U',
        'H:Q:U:V', 'H:Q:U:W', 'H:Q:U:X', 'H:Q:U:Y', 'H:Q:U:Z', 'H:Q:W:Y',
        'H:R:W:Z', 'H:T:W:Z', 'I:A:B:K', 'I:A:D:J', 'I:A:D:K', 'I:A:F:Y',
        'I:A:H:J', 'I:A:K:M', 'I:A:K:V', 'I:A:K:Z', 'I:A:M:W', 'I:A:N:W',
        'I:B:E:K', 'I:B:E:Y', 'I:B:K:N', 'I:B:Q:U', 'I:C:J:V', 'I:C:K:L',
        'I:C:K:O', 'I:C:Q:U', 'I:D:E:K', 'I:D:E:X', 'I:D:E:Y', 'I:D:E:Z',
        'I:D:H:J', 'I:D:H:K', 'I:D:J:T', 'I:D:K:L', 'I:D:K:N', 'I:D:Q:U',
        'I:E:F:Y', 'I:E:F:Z', 'I:E:G:Q', 'I:E:G:W', 'I:E:G:Z', 'I:E:H:Q',
        'I:E:H:V', 'I:E:H:X', 'I:E:J:M', 'I:E:J:V', 'I:E:J:Z', 'I:E:K:M',
        'I:E:K:W', 'I:E:K:Z', 'I:E:L:W', 'I:E:M:W', 'I:E:M:Z', 'I:E:N:W',
        'I:E:O:W', 'I:E:P:Y', 'I:E:P:Z', 'I:E:Q:Z', 'I:E:R:W', 'I:E:R:Z',
        'I:E:T:W', 'I:E:U:W', 'I:E:V:W', 'I:E:V:Z', 'I:E:W:Y', 'I:E:W:Z',
        'I:E:X:Z', 'I:F:J:N', 'I:F:J:T', 'I:F:N:Q', 'I:F:N:X', 'I:F:Q:U',
        'I:G:J:L', 'I:G:J:N', 'I:G:J:O', 'I:G:L:W', 'I:G:N:W', 'I:G:O:W',
        'I:G:O:Y', 'I:G:Q:U', 'I:G:R:W', 'I:G:S:W', 'I:H:N:V', 'I:H:Q:U',
        'I:J:M:S', 'I:J:N:V', 'I:J:N:Z', 'I:J:T:V', 'I:J:U:X', 'I:K:M:R',
        'I:K:M:S', 'I:K:N:V', 'I:K:N:W', 'I:K:P:S', 'I:K:P:V', 'I:K:R:V',
        'I:K:R:W', 'I:K:R:Z', 'I:K:S:V', 'I:K:S:Z', 'I:K:T:W', 'I:L:N:W',
        'I:L:O:W', 'I:L:Q:U', 'I:L:R:W', 'I:L:S:W', 'I:M:N:W', 'I:M:R:W',
        'I:M:S:W', 'I:M:T:W', 'I:M:V:W', 'I:N:O:W', 'I:N:Q:V', 'I:N:Q:X',
        'I:N:R:W', 'I:N:S:W', 'I:N:T:W', 'I:N:U:W', 'I:N:V:W', 'I:N:V:Y',
        'I:N:W:Y', 'I:N:W:Z', 'I:N:X:Y', 'I:O:R:W', 'I:P:Q:U', 'I:Q:U:V',
        'I:Q:U:X', 'I:Q:U:Y', 'I:R:T:W', 'I:R:V:W', 'I:R:V:Y', 'I:R:W:Z',
        'I:S:W:Y', 'I:T:V:W', 'I:T:W:Z', 'I:U:W:Y', 'I:V:W:Z', 'J:A:B:C',
        'J:A:B:F', 'J:A:B:G', 'J:A:B:V', 'J:A:B:Y', 'J:A:D:F', 'J:A:D:K',
        'J:A:D:W', 'J:A:E:W', 'J:A:F:Q', 'J:A:F:V', 'J:A:G:H', 'J:A:G:Q',
        'J:A:G:Y', 'J:A:H:L', 'J:A:I:W', 'J:A:K:L', 'J:A:K:M', 'J:A:K:P',
        'J:A:K:Q', 'J:A:L:X', 'J:A:M:W', 'J:A:M:X', 'J:A:N:W', 'J:A:O:W',
        'J:A:P:Q', 'J:A:P:V', 'J:A:P:X', 'J:A:P:Y', 'J:A:Q:U', 'J:A:R:W',
        'J:A:T:W', 'J:A:U:X', 'J:A:V:X', 'J:A:W:Z', 'J:B:E:F', 'J:B:E:H',
        'J:B:E:P', 'J:B:E:X', 'J:B:E:Z', 'J:B:F:I', 'J:B:F:L', 'J:B:F:S',
        'J:B:F:T', 'J:B:F:U', 'J:B:I:V', 'J:B:K:X', 'J:B:L:V', 'J:B:L:Y',
        'J:B:O:P', 'J:B:O:X', 'J:B:P:U', 'J:B:U:X', 'J:C:D:F', 'J:C:F:I',
        'J:C:G:Y', 'J:C:K:Q', 'J:C:P:V', 'J:C:P:Y', 'J:C:Q:U', 'J:C:U:X',
        'J:D:E:F', 'J:D:E:X', 'J:D:E:Z', 'J:D:F:I', 'J:D:F:N', 'J:D:F:R',
        'J:D:I:V', 'J:D:I:W', 'J:D:I:X', 'J:D:K:O', 'J:D:K:U', 'J:D:N:W',
        'J:D:P:U', 'J:D:Q:U', 'J:D:U:X', 'J:E:F:M', 'J:E:F:Q', 'J:E:F:R',
        'J:E:G:H', 'J:E:G:Q', 'J:E:H:Q', 'J:E:H:V', 'J:E:H:Z', 'J:E:K:M',
        'J:E:K:Q', 'J:E:K:X', 'J:E:K:Z', 'J:E:L:Z', 'J:E:M:X', 'J:E:O:W',
        'J:E:P:Q', 'J:E:P:Z', 'J:E:Q:U', 'J:E:Q:V', 'J:E:Q:Z', 'J:E:R:W',
        'J:E:R:Z', 'J:E:T:W', 'J:E:U:X', 'J:E:V:Z', 'J:E:X:Z', 'J:F:I:M',
        'J:F:I:Q', 'J:F:I:V', 'J:F:I:Z', 'J:F:L:U', 'J:F:N:Q', 'J:F:Q:U',
        'J:F:T:V', 'J:G:H:I', 'J:G:H:N', 'J:G:H:R', 'J:G:I:Y', 'J:G:M:Y',
        'J:G:N:Q', 'J:G:N:Y', 'J:G:O:Q', 'J:G:O:Y', 'J:G:Q:R', 'J:G:Q:S',
        'J:G:Q:U', 'J:G:S:Y', 'J:G:U:Y', 'J:H:I:V', 'J:H:K:O', 'J:H:O:Q',
        'J:H:O:V', 'J:H:Q:U', 'J:H:T:V', 'J:I:P:Q', 'J:I:P:V', 'J:I:Q:U',
        'J:I:Q:V', 'J:I:R:W', 'J:I:T:W', 'J:I:V:Y', 'J:K:M:S', 'J:K:N:Q',
        'J:K:O:P', 'J:K:O:Q', 'J:K:O:X', 'J:K:Q:S', 'J:K:Q:U', 'J:K:U:X',
        'J:L:Q:U', 'J:L:U:X', 'J:M:N:W', 'J:M:O:W', 'J:M:Q:U', 'J:M:U:X',
        'J:M:W:Z', 'J:N:Q:U', 'J:N:W:Z', 'J:O:P:X', 'J:O:P:Y', 'J:O:Q:U',
        'J:O:Q:V', 'J:O:R:W', 'J:O:T:W', 'J:O:U:X', 'J:O:V:Y', 'J:O:W:Z',
        'J:O:X:Y', 'J:O:X:Z', 'J:P:Q:U', 'J:P:R:V', 'J:P:S:V', 'J:P:T:V',
        'J:P:T:X', 'J:P:U:X', 'J:P:U:Y', 'J:Q:R:U', 'J:Q:S:U', 'J:Q:T:U',
        'J:Q:U:V', 'J:Q:U:Z', 'J:R:T:W', 'J:R:U:X', 'J:S:V:Y', 'J:T:U:X',
        'J:T:X:Z', 'J:U:V:X', 'J:U:X:Y', 'J:U:X:Z', 'K:A:B:F', 'K:A:B:V',
        'K:A:C:F', 'K:A:C:J', 'K:A:D:J', 'K:A:D:Q', 'K:A:D:X', 'K:A:F:M',
        'K:A:F:W', 'K:A:F:X', 'K:A:G:V', 'K:A:G:Y', 'K:A:H:J', 'K:A:H:W',
        'K:A:H:X', 'K:A:J:M', 'K:A:J:N', 'K:A:J:R', 'K:A:M:X', 'K:A:Q:U',
        'K:A:U:W', 'K:A:V:X', 'K:A:W:Y', 'K:A:X:Z', 'K:A:Y:Z', 'K:B:E:Q',
        'K:B:E:V', 'K:B:E:W', 'K:B:F:L', 'K:B:F:O', 'K:B:F:R', 'K:B:G:I',
        'K:B:I:P', 'K:B:I:Q', 'K:B:I:W', 'K:B:L:Q', 'K:B:L:W', 'K:B:N:V',
        'K:B:O:V', 'K:B:O:W', 'K:B:Q:S', 'K:B:Q:U', 'K:B:R:V', 'K:B:R:W',
        'K:B:S:V', 'K:B:S:W', 'K:B:T:V', 'K:C:D:O', 'K:C:D:Q', 'K:C:E:Q',
        'K:C:F:I', 'K:C:F:N', 'K:C:F:O', 'K:C:G:I', 'K:C:G:O', 'K:C:G:V',
        'K:C:I:Q', 'K:C:J:N', 'K:C:J:O', 'K:C:L:Q', 'K:C:O:Q', 'K:C:O:X',
        'K:C:Q:U', 'K:D:E:Q', 'K:D:E:V', 'K:D:E:X', 'K:D:E:Z', 'K:D:F:I',
        'K:D:H:V', 'K:D:H:X', 'K:D:I:Q', 'K:D:I:V', 'K:D:I:X', 'K:D:I:Z',
        'K:D:J:R', 'K:D:L:Q', 'K:D:N:W', 'K:D:O:Q', 'K:D:P:Q', 'K:D:Q:S',
        'K:D:Q:U', 'K:D:U:X', 'K:D:V:X', 'K:D:W:Y', 'K:E:F:M', 'K:E:F:P',
        'K:E:F:Q', 'K:E:F:W', 'K:E:F:Z', 'K:E:G:Q', 'K:E:G:V', 'K:E:H:Q',
        'K:E:I:Q', 'K:E:J:T', 'K:E:L:Q', 'K:E:M:X', 'K:E:N:Q', 'K:E:O:Q',
        'K:E:P:Q', 'K:E:Q:R', 'K:E:Q:U', 'K:E:Q:V', 'K:E:Q:Y', 'K:E:U:W',
        'K:E:V:X', 'K:E:X:Z', 'K:E:Y:Z', 'K:F:H:X', 'K:F:I:M', 'K:F:I:Q',
        'K:F:I:X', 'K:F:I:Z', 'K:F:L:P', 'K:F:L:X', 'K:F:M:S', 'K:F:Q:U',
        'K:F:U:X', 'K:G:I:Q', 'K:G:I:V', 'K:G:I:Z', 'K:G:L:Q', 'K:G:N:V',
        'K:G:N:X', 'K:G:O:Q', 'K:G:O:V', 'K:G:O:Y', 'K:G:Q:R', 'K:G:Q:U',
        'K:G:R:V', 'K:G:R:Y', 'K:G:S:V', 'K:H:I:J', 'K:H:I:Q', 'K:H:J:R',
        'K:H:N:Q', 'K:H:Q:T', 'K:H:Q:U', 'K:H:U:X', 'K:H:V:X', 'K:I:N:Q',
        'K:I:O:Q', 'K:I:P:Q', 'K:I:P:Z', 'K:I:Q:U', 'K:I:Q:V', 'K:I:Q:Y',
        'K:I:T:W', 'K:I:U:W', 'K:I:V:X', 'K:I:W:Y', 'K:J:M:R', 'K:L:M:X',
        'K:L:Q:U', 'K:L:U:W', 'K:L:X:Z', 'K:M:N:X', 'K:M:O:X', 'K:M:Q:U',
        'K:M:S:X', 'K:M:U:V', 'K:N:Q:U', 'K:N:Q:V', 'K:N:W:Y', 'K:N:W:Z',
        'K:N:X:Z', 'K:O:Q:U', 'K:O:Q:V', 'K:O:U:W', 'K:O:X:Z', 'K:P:Q:U',
        'K:Q:R:U', 'K:Q:S:U', 'K:Q:T:U', 'K:Q:U:V', 'K:Q:U:Y', 'K:R:U:W',
        'K:R:W:Y', 'K:T:U:W', 'K:U:V:X', 'L:A:B:J', 'L:A:B:W', 'L:A:C:J',
        'L:A:D:K', 'L:A:D:W', 'L:A:F:X', 'L:A:G:K', 'L:A:G:W', 'L:A:H:J',
        'L:A:J:P', 'L:A:J:T', 'L:A:J:X', 'L:A:J:Z', 'L:A:M:W', 'L:A:N:W',
        'L:A:Q:U', 'L:A:T:W', 'L:A:U:W', 'L:B:E:Z', 'L:B:J:X', 'L:B:M:W',
        'L:B:O:W', 'L:B:Q:U', 'L:B:S:W', 'L:C:E:W', 'L:C:I:J', 'L:C:I:W',
        'L:C:J:O', 'L:C:J:S', 'L:C:J:T', 'L:C:Q:U', 'L:C:R:W', 'L:D:F:I',
        'L:D:H:K', 'L:D:I:K', 'L:D:J:P', 'L:D:Q:U', 'L:D:T:W', 'L:E:F:Z',
        'L:E:G:K', 'L:E:H:Q', 'L:E:H:W', 'L:E:J:X', 'L:E:K:Q', 'L:E:K:Y',
        'L:E:K:Z', 'L:E:P:Q', 'L:E:Q:U', 'L:E:Q:V', 'L:E:Q:X', 'L:E:Q:Z',
        'L:E:R:W', 'L:E:T:W', 'L:E:X:Z', 'L:F:H:I', 'L:F:I:P', 'L:F:I:V',
        'L:F:I:X', 'L:F:N:V', 'L:F:Q:U', 'L:F:T:X', 'L:G:I:J', 'L:G:I:K',
        'L:G:J:N', 'L:G:J:O', 'L:G:Q:U', 'L:G:T:W', 'L:H:J:M', 'L:H:J:N',
        'L:H:Q:U', 'L:H:R:W', 'L:I:J:P', 'L:I:J:T', 'L:I:J:X', 'L:I:J:Z',
        'L:I:K:Q', 'L:I:K:Y', 'L:I:Q:U', 'L:I:Q:V', 'L:I:Q:Y', 'L:I:U:W',
        'L:J:M:N', 'L:J:N:R', 'L:J:N:T', 'L:J:N:X', 'L:J:N:Z', 'L:J:O:R',
        'L:J:O:T', 'L:J:O:X', 'L:J:P:S', 'L:J:P:U', 'L:J:R:X', 'L:J:S:T',
        'L:J:S:X', 'L:J:S:Z', 'L:J:T:U', 'L:J:U:X', 'L:J:U:Z', 'L:K:O:Q',
        'L:K:P:Q', 'L:K:Q:R', 'L:K:Q:T', 'L:K:Q:U', 'L:M:Q:U', 'L:N:Q:U',
        'L:N:T:W', 'L:O:Q:U', 'L:O:T:W', 'L:P:Q:U', 'L:Q:R:U', 'L:Q:S:U',
        'L:Q:T:U', 'L:Q:U:V', 'L:Q:U:X', 'L:Q:U:Y', 'L:Q:U:Z', 'L:R:T:W',
        'M:A:D:J', 'M:A:F:J', 'M:A:F:K', 'M:A:F:V', 'M:A:G:W', 'M:A:H:J',
        'M:A:J:Q', 'M:A:K:X', 'M:A:K:Z', 'M:A:U:W', 'M:A:W:X', 'M:B:C:J',
        'M:B:E:F', 'M:B:E:Q', 'M:B:E:W', 'M:B:J:O', 'M:B:Q:U', 'M:B:R:W',
        'M:B:S:W', 'M:C:I:W', 'M:C:O:W', 'M:C:Q:U', 'M:C:R:W', 'M:C:S:W',
        'M:D:Q:U', 'M:E:F:J', 'M:E:F:Z', 'M:E:G:W', 'M:E:H:Q', 'M:E:J:P',
        'M:E:J:V', 'M:E:J:Z', 'M:E:K:Q', 'M:E:K:V', 'M:E:P:Q', 'M:E:P:V',
        'M:E:Q:U', 'M:E:Q:Z', 'M:E:U:W', 'M:E:V:Z', 'M:E:W:X', 'M:E:W:Z',
        'M:F:I:J', 'M:F:I:K', 'M:F:I:Q', 'M:F:I:V', 'M:F:J:O', 'M:F:J:R',
        'M:F:J:T', 'M:F:K:L', 'M:F:K:O', 'M:F:K:T', 'M:F:Q:U', 'M:G:Q:U',
        'M:G:U:W', 'M:H:Q:U', 'M:H:U:W', 'M:I:J:K', 'M:I:J:P', 'M:I:J:Q',
        'M:I:K:Q', 'M:I:K:V', 'M:I:Q:U', 'M:I:Q:V', 'M:I:W:Z', 'M:J:K:O',
        'M:J:K:U', 'M:J:N:Y', 'M:J:O:Q', 'M:J:O:V', 'M:J:O:Y', 'M:J:P:U',
        'M:J:Q:U', 'M:J:T:Y', 'M:J:U:X', 'M:K:O:W', 'M:K:Q:S', 'M:K:Q:U',
        'M:K:T:X', 'M:K:U:X', 'M:L:Q:U', 'M:L:W:X', 'M:L:W:Z', 'M:N:Q:U',
        'M:O:Q:U', 'M:O:W:Z', 'M:P:Q:U', 'M:Q:R:U', 'M:Q:T:U', 'M:Q:U:V',
        'M:Q:U:X', 'M:Q:U:Y', 'M:Q:U:Z', 'M:R:U:W', 'M:R:W:Z', 'M:T:U:W',
        'N:A:B:Y', 'N:A:C:J', 'N:A:D:J', 'N:A:D:W', 'N:A:F:Q', 'N:A:F:X',
        'N:A:G:K', 'N:A:G:W', 'N:A:H:J', 'N:A:H:K', 'N:A:J:M', 'N:A:J:V',
        'N:A:K:P', 'N:A:K:V', 'N:A:K:X', 'N:A:W:Y', 'N:A:X:Y', 'N:A:X:Z',
        'N:B:E:F', 'N:B:E:V', 'N:B:E:W', 'N:B:E:Y', 'N:B:F:I', 'N:B:F:O',
        'N:B:F:U', 'N:B:L:Y', 'N:B:O:P', 'N:B:O:Y', 'N:B:T:Y', 'N:B:U:X',
        'N:C:F:Q', 'N:C:F:X', 'N:C:I:J', 'N:C:J:S', 'N:C:Q:U', 'N:D:E:Y',
        'N:D:I:J', 'N:D:I:V', 'N:D:J:M', 'N:D:J:O', 'N:D:O:V', 'N:D:U:X',
        'N:E:F:V', 'N:E:F:W', 'N:E:F:X', 'N:E:G:Z', 'N:E:H:Q', 'N:E:H:V',
        'N:E:I:W', 'N:E:J:L', 'N:E:J:M', 'N:E:J:Z', 'N:E:K:M', 'N:E:K:Q',
        'N:E:K:V', 'N:E:L:W', 'N:E:M:W', 'N:E:P:Q', 'N:E:P:Z', 'N:E:Q:X',
        'N:E:Q:Y', 'N:E:Q:Z', 'N:E:R:W', 'N:E:U:W', 'N:E:V:Y', 'N:E:V:Z',
        'N:E:W:Y', 'N:E:W:Z', 'N:E:X:Z', 'N:E:Y:Z', 'N:F:I:P', 'N:F:I:Q',
        'N:F:I:V', 'N:F:I:W', 'N:F:I:X', 'N:F:L:X', 'N:F:O:V', 'N:F:O:X',
        'N:F:Q:R', 'N:F:Q:T', 'N:F:Q:U', 'N:F:R:X', 'N:G:I:K', 'N:G:U:X',
        'N:H:I:Z', 'N:H:J:U', 'N:I:J:M', 'N:I:J:T', 'N:I:J:Z', 'N:I:K:P',
        'N:I:K:Q', 'N:I:K:V', 'N:I:P:Q', 'N:I:Q:X', 'N:I:Q:Y', 'N:I:U:W',
        'N:I:W:Y', 'N:I:X:Z', 'N:J:L:O', 'N:J:L:U', 'N:J:L:Z', 'N:J:M:O',
        'N:J:M:S', 'N:J:O:Z', 'N:J:S:T', 'N:J:T:U', 'N:J:U:Z', 'N:K:L:V',
        'N:K:O:Q', 'N:K:O:V', 'N:K:O:X', 'N:K:O:Y', 'N:K:P:S', 'N:K:Q:R',
        'N:K:Q:S', 'N:K:Q:T', 'N:K:Q:U', 'N:K:S:V', 'N:K:S:Y', 'N:K:T:X',
        'N:K:U:X', 'N:K:W:Y', 'N:L:Q:U', 'N:L:U:W', 'N:L:X:Z', 'N:M:S:W',
        'N:M:X:Z', 'N:O:Q:X', 'N:O:U:W', 'N:O:W:Y', 'N:O:Y:Z', 'N:P:Q:U',
        'N:Q:R:U', 'N:Q:R:X', 'N:Q:T:X', 'N:Q:U:V', 'N:Q:U:X', 'N:Q:U:Y',
        'N:Q:U:Z', 'N:R:U:W', 'N:R:W:Y', 'N:S:U:W', 'N:S:W:Y', 'N:S:X:Z',
        'N:T:X:Z', 'O:A:B:W', 'O:A:D:W', 'O:A:J:L', 'O:A:J:W', 'O:A:J:X',
        'O:A:J:Y', 'O:A:Q:U', 'O:A:U:W', 'O:A:V:W', 'O:A:V:X', 'O:A:W:Y',
        'O:B:C:J', 'O:B:E:Z', 'O:B:F:I', 'O:B:F:J', 'O:B:I:W', 'O:B:J:L',
        'O:B:J:R', 'O:B:J:T', 'O:B:J:V', 'O:B:J:W', 'O:B:J:X', 'O:B:J:Y',
        'O:B:J:Z', 'O:B:Q:U', 'O:B:W:Y', 'O:C:E:J', 'O:C:F:J', 'O:C:H:W',
        'O:C:I:W', 'O:C:J:L', 'O:C:J:T', 'O:C:J:V', 'O:C:J:X', 'O:C:Q:U',
        'O:C:R:W', 'O:C:S:W', 'O:D:E:H', 'O:D:E:Q', 'O:D:I:W', 'O:D:L:W',
        'O:D:Q:U', 'O:E:F:J', 'O:E:F:K', 'O:E:F:M', 'O:E:F:W', 'O:E:F:Z',
        'O:E:H:Q', 'O:E:H:Z', 'O:E:I:W', 'O:E:J:L', 'O:E:J:M', 'O:E:J:V',
        'O:E:J:X', 'O:E:J:Z', 'O:E:K:L', 'O:E:K:Q', 'O:E:K:V', 'O:E:K:Z',
        'O:E:M:Q', 'O:E:M:W', 'O:E:M:Z', 'O:E:N:W', 'O:E:P:Q', 'O:E:P:Z',
        'O:E:Q:U', 'O:E:Q:V', 'O:E:Q:X', 'O:E:Q:Z', 'O:E:V:W', 'O:E:V:Z',
        'O:E:X:Z', 'O:E:Y:Z', 'O:F:I:J', 'O:F:I:K', 'O:F:I:P', 'O:F:I:W',
        'O:F:J:T', 'O:F:K:Q', 'O:F:K:R', 'O:F:K:S', 'O:F:K:U', 'O:F:L:W',
        'O:F:Q:U', 'O:F:R:W', 'O:F:S:W', 'O:F:X:Y', 'O:G:I:Q', 'O:G:J:U',
        'O:G:Q:U', 'O:H:I:V', 'O:H:I:W', 'O:H:Q:U', 'O:H:S:W', 'O:I:J:V',
        'O:I:J:W', 'O:I:J:Y', 'O:I:K:Q', 'O:I:M:W', 'O:I:N:W', 'O:I:P:V',
        'O:I:Q:U', 'O:I:Q:V', 'O:I:Q:X', 'O:I:R:W', 'O:I:V:W', 'O:I:W:Y',
        'O:J:L:T', 'O:J:T:V', 'O:J:T:X', 'O:J:U:X', 'O:J:W:Y', 'O:K:Q:U',
        'O:K:R:V', 'O:L:Q:U', 'O:L:Q:V', 'O:M:Q:U', 'O:M:S:W', 'O:N:Q:U',
        'O:P:Q:U', 'O:Q:R:U', 'O:Q:S:U', 'O:Q:T:U', 'O:Q:U:V', 'O:Q:U:X',
        'O:Q:U:Y', 'O:Q:U:Z', 'O:R:V:W', 'O:T:U:W', 'O:T:V:W', 'O:U:V:W',
        'P:A:B:J', 'P:A:F:W', 'P:A:J:X', 'P:A:J:Y', 'P:A:K:W', 'P:A:K:X',
        'P:A:U:W', 'P:A:W:Y', 'P:A:W:Z', 'P:B:E:V', 'P:B:E:W', 'P:B:E:Z',
        'P:B:Q:U', 'P:B:R:V', 'P:B:R:W', 'P:B:S:W', 'P:C:E:J', 'P:C:J:X',
        'P:C:K:W', 'P:C:M:W', 'P:C:O:W', 'P:C:Q:U', 'P:D:I:J', 'P:D:Q:U',
        'P:E:F:J', 'P:E:F:Q', 'P:E:F:W', 'P:E:F:Z', 'P:E:G:J', 'P:E:H:J',
        'P:E:J:V', 'P:E:J:X', 'P:E:J:Z', 'P:E:K:Q', 'P:E:K:V', 'P:E:K:Z',
        'P:E:M:W', 'P:E:M:Z', 'P:E:Q:U', 'P:E:Q:X', 'P:E:W:Y', 'P:E:W:Z',
        'P:E:X:Z', 'P:F:I:J', 'P:F:I:Q', 'P:F:I:V', 'P:F:I:W', 'P:F:J:O',
        'P:F:J:R', 'P:F:J:T', 'P:F:L:W', 'P:F:O:W', 'P:F:Q:U', 'P:F:R:W',
        'P:F:S:W', 'P:F:W:Y', 'P:F:W:Z', 'P:G:Q:U', 'P:H:J:L', 'P:H:K:W',
        'P:H:O:W', 'P:H:Q:U', 'P:I:J:K', 'P:I:K:V', 'P:I:L:W', 'P:I:Q:U',
        'P:I:U:W', 'P:I:W:Y', 'P:I:W:Z', 'P:J:R:X', 'P:J:U:X', 'P:K:O:W',
        'P:K:Q:T', 'P:K:Q:U', 'P:K:R:W', 'P:K:T:W', 'P:K:T:X', 'P:K:U:X',
        'P:L:Q:U', 'P:L:U:W', 'P:L:W:Y', 'P:L:W:Z', 'P:M:N:W', 'P:M:O:W',
        'P:M:Q:U', 'P:N:U:W', 'P:O:U:W', 'P:O:W:Y', 'P:O:W:Z', 'P:Q:R:U',
        'P:Q:T:U', 'P:Q:U:V', 'P:Q:U:X', 'P:Q:U:Y', 'P:Q:U:Z', 'P:R:W:Y',
        'P:R:W:Z', 'P:S:W:Y', 'P:S:W:Z', 'P:W:Y:Z', 'Q:A:B:D', 'Q:A:B:F',
        'Q:A:B:H', 'Q:A:B:J', 'Q:A:B:K', 'Q:A:B:Y', 'Q:A:C:G', 'Q:A:C:J',
        'Q:A:C:X', 'Q:A:D:H', 'Q:A:D:J', 'Q:A:D:P', 'Q:A:D:X', 'Q:A:D:Y',
        'Q:A:D:Z', 'Q:A:F:M', 'Q:A:F:V', 'Q:A:F:Z', 'Q:A:G:H', 'Q:A:G:P',
        'Q:A:G:U', 'Q:A:G:V', 'Q:A:G:X', 'Q:A:G:Z', 'Q:A:H:M', 'Q:A:I:V',
        'Q:A:I:W', 'Q:A:J:L', 'Q:A:J:M', 'Q:A:J:O', 'Q:A:J:R', 'Q:A:J:S',
        'Q:A:J:T', 'Q:A:J:X', 'Q:A:K:M', 'Q:A:K:N', 'Q:A:K:O', 'Q:A:K:R',
        'Q:A:K:U', 'Q:A:L:V', 'Q:A:L:W', 'Q:A:L:X', 'Q:A:M:X', 'Q:A:M:Y',
        'Q:A:N:W', 'Q:A:O:X', 'Q:A:P:U', 'Q:A:P:X', 'Q:A:P:Y', 'Q:A:S:X',
        'Q:A:U:V', 'Q:A:U:W', 'Q:A:U:X', 'Q:A:U:Y', 'Q:A:X:Y', 'Q:A:X:Z',
        'Q:B:C:E', 'Q:B:C:H', 'Q:B:C:K', 'Q:B:C:U', 'Q:B:D:E', 'Q:B:D:I',
        'Q:B:D:R', 'Q:B:D:U', 'Q:B:D:Y', 'Q:B:E:F', 'Q:B:E:H', 'Q:B:E:K',
        'Q:B:E:U', 'Q:B:E:V', 'Q:B:E:Y', 'Q:B:E:Z', 'Q:B:F:I', 'Q:B:F:L',
        'Q:B:F:U', 'Q:B:H:O', 'Q:B:H:R', 'Q:B:H:U', 'Q:B:I:J', 'Q:B:I:M',
        'Q:B:I:N', 'Q:B:I:V', 'Q:B:I:Y', 'Q:B:I:Z', 'Q:B:J:N', 'Q:B:J:O',
        'Q:B:J:R', 'Q:B:J:S', 'Q:B:J:U', 'Q:B:K:R', 'Q:B:K:T', 'Q:B:K:U',
        'Q:B:L:Y', 'Q:B:M:S', 'Q:B:M:U', 'Q:B:N:U', 'Q:B:O:U', 'Q:B:R:U',
        'Q:B:R:Y', 'Q:B:S:Y', 'Q:B:T:U', 'Q:B:U:V', 'Q:B:U:Y', 'Q:B:U:Z',
        'Q:C:D:I', 'Q:C:E:G', 'Q:C:E:U', 'Q:C:E:V', 'Q:C:E:Z', 'Q:C:F:U',
        'Q:C:F:V', 'Q:C:G:I', 'Q:C:G:N', 'Q:C:G:O', 'Q:C:G:U', 'Q:C:H:V',
        'Q:C:I:J', 'Q:C:I:P', 'Q:C:I:V', 'Q:C:I:X', 'Q:C:I:Y', 'Q:C:J:N',
        'Q:C:J:O', 'Q:C:J:U', 'Q:C:K:P', 'Q:C:K:T', 'Q:C:K:U', 'Q:C:L:U',
        'Q:C:N:U', 'Q:C:O:U', 'Q:C:P:U', 'Q:C:R:U', 'Q:C:T:U', 'Q:C:U:V',
        'Q:C:U:X', 'Q:C:U:Y', 'Q:C:U:Z', 'Q:D:E:F', 'Q:D:E:G', 'Q:D:E:U',
        'Q:D:E:Y', 'Q:D:E:Z', 'Q:D:F:I', 'Q:D:F:U', 'Q:D:G:P', 'Q:D:G:U',
        'Q:D:H:I', 'Q:D:I:V', 'Q:D:J:L', 'Q:D:J:M', 'Q:D:J:R', 'Q:D:L:U',
        'Q:D:L:X', 'Q:D:M:U', 'Q:D:M:X', 'Q:D:N:U', 'Q:D:O:U', 'Q:D:P:R',
        'Q:D:P:U', 'Q:D:P:X', 'Q:D:P:Y', 'Q:D:R:V', 'Q:D:R:Y', 'Q:D:S:X',
        'Q:D:T:U', 'Q:D:U:V', 'Q:D:U:X', 'Q:D:U:Y', 'Q:D:U:Z', 'Q:D:X:Y',
        'Q:E:F:M', 'Q:E:F:R', 'Q:E:F:U', 'Q:E:F:V', 'Q:E:G:J', 'Q:E:G:M',
        'Q:E:G:P', 'Q:E:G:U', 'Q:E:G:V', 'Q:E:G:X', 'Q:E:G:Y', 'Q:E:G:Z',
        'Q:E:H:M', 'Q:E:H:U', 'Q:E:H:V', 'Q:E:H:Z', 'Q:E:I:J', 'Q:E:I:V',
        'Q:E:J:L', 'Q:E:J:M', 'Q:E:J:T', 'Q:E:J:U', 'Q:E:K:M', 'Q:E:K:N',
        'Q:E:K:P', 'Q:E:K:T', 'Q:E:K:U', 'Q:E:L:M', 'Q:E:L:U', 'Q:E:L:V',
        'Q:E:L:X', 'Q:E:L:Y', 'Q:E:L:Z', 'Q:E:M:X', 'Q:E:M:Y', 'Q:E:M:Z',
        'Q:E:N:V', 'Q:E:N:W', 'Q:E:O:V', 'Q:E:P:U', 'Q:E:P:V', 'Q:E:P:Y',
        'Q:E:P:Z', 'Q:E:R:W', 'Q:E:R:Y', 'Q:E:S:X', 'Q:E:T:V', 'Q:E:T:W',
        'Q:E:U:V', 'Q:E:U:W', 'Q:E:U:X', 'Q:E:W:Y', 'Q:E:W:Z', 'Q:E:X:Y',
        'Q:E:X:Z', 'Q:E:Y:Z', 'Q:F:I:L', 'Q:F:I:M', 'Q:F:I:T', 'Q:F:I:V',
        'Q:F:L:U', 'Q:F:L:V', 'Q:F:M:U', 'Q:F:N:U', 'Q:F:R:U', 'Q:F:T:U',
        'Q:F:T:V', 'Q:F:U:V', 'Q:G:H:O', 'Q:G:H:U', 'Q:G:I:J', 'Q:G:I:P',
        'Q:G:I:V', 'Q:G:J:U', 'Q:G:L:P', 'Q:G:L:U', 'Q:G:M:U', 'Q:G:N:V',
        'Q:G:O:U', 'Q:G:P:R', 'Q:G:P:U', 'Q:G:R:U', 'Q:G:R:V', 'Q:G:R:Z',
        'Q:G:T:U', 'Q:G:T:V', 'Q:G:T:Z', 'Q:G:U:V', 'Q:G:U:X', 'Q:G:U:Y',
        'Q:G:U:Z', 'Q:H:I:L', 'Q:H:I:M', 'Q:H:I:N', 'Q:H:I:V', 'Q:H:I:Z',
        'Q:H:L:O', 'Q:H:L:U', 'Q:H:M:U', 'Q:H:N:U', 'Q:H:N:V', 'Q:H:O:P',
        'Q:H:O:V', 'Q:H:R:U', 'Q:H:R:V', 'Q:H:S:V', 'Q:H:T:U', 'Q:H:U:V',
        'Q:H:U:Z', 'Q:I:J:L', 'Q:I:J:M', 'Q:I:J:N', 'Q:I:J:O', 'Q:I:J:S',
        'Q:I:J:T', 'Q:I:J:U', 'Q:I:J:X', 'Q:I:K:M', 'Q:I:K:N', 'Q:I:K:P',
        'Q:I:K:U', 'Q:I:L:V', 'Q:I:L:W', 'Q:I:L:Y', 'Q:I:M:U', 'Q:I:M:V',
        'Q:I:M:X', 'Q:I:M:Y', 'Q:I:N:V', 'Q:I:O:V', 'Q:I:P:U', 'Q:I:P:V',
        'Q:I:P:Y', 'Q:I:R:V', 'Q:I:S:V', 'Q:I:T:V', 'Q:I:U:V', 'Q:I:U:X',
        'Q:I:U:Y', 'Q:I:Y:Z', 'Q:J:L:M', 'Q:J:L:R', 'Q:J:L:U', 'Q:J:M:R',
        'Q:J:M:U', 'Q:J:N:U', 'Q:J:O:T', 'Q:J:O:U', 'Q:J:S:T', 'Q:J:S:U',
        'Q:J:T:U', 'Q:J:U:X', 'Q:K:M:R', 'Q:K:M:S', 'Q:K:M:U', 'Q:K:N:O',
        'Q:K:N:R', 'Q:K:N:U', 'Q:K:O:U', 'Q:K:P:S', 'Q:K:P:T', 'Q:K:P:U',
        'Q:K:R:U', 'Q:K:S:U', 'Q:K:T:U', 'Q:L:M:U', 'Q:L:O:U', 'Q:L:P:U',
        'Q:L:R:U', 'Q:L:R:X', 'Q:L:T:U', 'Q:L:U:V', 'Q:L:U:X', 'Q:L:U:Y',
        'Q:L:U:Z', 'Q:M:N:U', 'Q:M:N:Y', 'Q:M:O:U', 'Q:M:O:Y', 'Q:M:P:U',
        'Q:M:P:V', 'Q:M:R:U', 'Q:M:R:X', 'Q:M:S:Y', 'Q:M:T:Y', 'Q:M:U:V',
        'Q:M:U:X', 'Q:M:U:Y', 'Q:M:U:Z', 'Q:N:P:U', 'Q:N:P:V', 'Q:N:U:V',
        'Q:N:U:W', 'Q:N:U:X', 'Q:N:U:Y', 'Q:N:U:Z', 'Q:N:Y:Z', 'Q:O:P:V',
        'Q:O:P:Y', 'Q:O:U:V', 'Q:O:U:X', 'Q:O:U:Y', 'Q:O:U:Z', 'Q:O:X:Y',
        'Q:O:Y:Z', 'Q:P:R:U', 'Q:P:R:V', 'Q:P:R:X', 'Q:P:R:Y', 'Q:P:S:U',
        'Q:P:S:V', 'Q:P:S:Y', 'Q:P:T:U', 'Q:P:U:V', 'Q:P:U:X', 'Q:P:U:Y',
        'Q:P:U:Z', 'Q:R:S:X', 'Q:R:T:W', 'Q:R:U:V', 'Q:R:U:X', 'Q:R:W:Y',
        'Q:R:W:Z', 'Q:R:X:Y', 'Q:S:U:V', 'Q:S:U:X', 'Q:T:U:V', 'Q:T:U:X',
        'Q:T:W:Y', 'Q:T:W:Z', 'Q:T:Y:Z', 'Q:U:X:Y', 'Q:U:X:Z', 'Q:U:Y:Z',
        'R:A:J:K', 'R:A:J:X', 'R:A:K:Q', 'R:A:K:X', 'R:A:Q:U', 'R:B:G:W',
        'R:B:K:Q', 'R:B:M:W', 'R:B:N:W', 'R:B:O:W', 'R:B:Q:U', 'R:B:U:W',
        'R:B:W:Y', 'R:C:E:J', 'R:C:J:K', 'R:D:Q:U', 'R:E:F:J', 'R:E:F:K',
        'R:E:F:V', 'R:E:J:K', 'R:E:J:L', 'R:E:J:Q', 'R:E:J:V', 'R:E:J:X',
        'R:E:J:Y', 'R:E:J:Z', 'R:E:K:P', 'R:E:K:Q', 'R:E:K:X', 'R:E:K:Z',
        'R:E:M:Q', 'R:E:P:W', 'R:E:Q:V', 'R:E:Q:W', 'R:E:Q:X', 'R:E:Q:Y',
        'R:E:Q:Z', 'R:E:T:W', 'R:E:V:W', 'R:E:W:Z', 'R:E:X:Z', 'R:E:Y:Z',
        'R:F:I:J', 'R:F:Q:U', 'R:G:Q:U', 'R:H:Q:U', 'R:H:Q:W', 'R:I:J:V',
        'R:I:J:Y', 'R:I:K:W', 'R:I:P:W', 'R:I:Q:U', 'R:I:Q:W', 'R:I:V:W',
        'R:J:N:Y', 'R:J:O:Q', 'R:J:O:X', 'R:J:O:Y', 'R:J:P:X', 'R:J:Q:U',
        'R:J:S:X', 'R:J:T:X', 'R:J:T:Y', 'R:J:U:X', 'R:K:L:X', 'R:K:M:Q',
        'R:K:N:X', 'R:K:O:Q', 'R:K:O:V', 'R:K:O:X', 'R:K:Q:U', 'R:L:Q:U',
        'R:N:Q:U', 'R:N:Q:W', 'R:N:V:W', 'R:P:Q:U', 'R:Q:U:V', 'R:Q:U:W',
        'R:Q:U:X', 'R:Q:U:Y', 'R:Q:U:Z', 'R:T:V:W', 'S:A:J:Q', 'S:A:Q:U',
        'S:A:Q:W', 'S:B:J:U', 'S:B:O:W', 'S:B:Q:U', 'S:C:F:J', 'S:C:Q:U',
        'S:D:Q:U', 'S:E:F:W', 'S:E:G:Q', 'S:E:J:M', 'S:E:J:Q', 'S:E:J:V',
        'S:E:J:X', 'S:E:J:Z', 'S:E:K:Q', 'S:E:Q:U', 'S:E:Q:X', 'S:E:Q:Z',
        'S:E:X:Z', 'S:F:I:V', 'S:F:J:U', 'S:F:Q:U', 'S:G:Q:U', 'S:H:Q:U',
        'S:I:J:Q', 'S:I:J:V', 'S:I:Q:U', 'S:J:M:U', 'S:J:Q:U', 'S:J:U:X',
        'S:J:U:Z', 'S:K:Q:U', 'S:L:Q:U', 'S:M:Q:U', 'S:O:Q:U', 'S:P:Q:U',
        'S:Q:R:U', 'S:Q:T:U', 'S:Q:U:V', 'S:Q:U:W', 'S:Q:U:X', 'S:Q:U:Y',
        'S:Q:U:Z', 'T:A:B:K', 'T:A:B:W', 'T:A:C:W', 'T:A:D:J', 'T:A:D:K',
        'T:A:F:K', 'T:A:G:J', 'T:A:H:J', 'T:A:J:K', 'T:A:J:P', 'T:A:J:X',
        'T:A:J:Y', 'T:A:K:P', 'T:A:K:X', 'T:A:V:X', 'T:A:W:X', 'T:A:W:Y',
        'T:B:C:J', 'T:B:E:J', 'T:B:E:Q', 'T:B:E:W', 'T:B:F:J', 'T:B:I:J',
        'T:B:J:L', 'T:B:J:O', 'T:B:Q:U', 'T:B:R:W', 'T:B:S:W', 'T:C:E:W',
        'T:C:F:J', 'T:C:H:J', 'T:C:I:J', 'T:C:I:W', 'T:C:L:W', 'T:C:N:W',
        'T:C:R:W', 'T:C:S:W', 'T:D:E:W', 'T:D:Q:U', 'T:E:F:J', 'T:E:F:P',
        'T:E:F:V', 'T:E:F:Y', 'T:E:F:Z', 'T:E:G:J', 'T:E:G:Q', 'T:E:H:J',
        'T:E:J:M', 'T:E:J:X', 'T:E:J:Y', 'T:E:J:Z', 'T:E:K:Q', 'T:E:M:Q',
        'T:E:P:V', 'T:E:Q:V', 'T:E:Q:X', 'T:E:Q:Z', 'T:E:U:W', 'T:E:V:Z',
        'T:E:W:Z', 'T:E:X:Z', 'T:E:Y:Z', 'T:F:I:J', 'T:F:I:K', 'T:F:I:Q',
        'T:F:I:V', 'T:F:I:Y', 'T:F:J:L', 'T:F:J:O', 'T:F:P:Y', 'T:F:Q:U',
        'T:F:R:V', 'T:G:H:J', 'T:G:I:K', 'T:G:J:R', 'T:G:Q:U', 'T:H:I:J',
        'T:H:J:O', 'T:H:J:P', 'T:H:J:R', 'T:I:J:Y', 'T:I:K:V', 'T:I:W:X',
        'T:J:O:Y', 'T:J:R:X', 'T:J:R:Z', 'T:J:S:Y', 'T:J:U:X', 'T:K:N:V',
        'T:K:Q:U', 'T:L:Q:U', 'T:N:Q:U', 'T:N:V:Y', 'T:O:P:V', 'T:O:Q:U',
        'T:P:Q:U', 'T:P:S:V', 'T:Q:U:V', 'T:Q:U:X', 'T:Q:U:Z', 'U:A:B:D',
        'U:A:B:F', 'U:A:B:H', 'U:A:B:J', 'U:A:B:P', 'U:A:B:V', 'U:A:B:Y',
        'U:A:D:V', 'U:A:D:W', 'U:A:E:J', 'U:A:E:W', 'U:A:F:X', 'U:A:G:K',
        'U:A:G:V', 'U:A:G:Z', 'U:A:H:K', 'U:A:I:J', 'U:A:I:W', 'U:A:J:M',
        'U:A:J:N', 'U:A:J:S', 'U:A:J:T', 'U:A:K:M', 'U:A:K:P', 'U:A:Q:X',
        'U:A:Q:Z', 'U:A:R:W', 'U:A:T:W', 'U:A:V:X', 'U:A:V:Y', 'U:A:V:Z',
        'U:A:X:Y', 'U:A:Y:Z', 'U:B:C:H', 'U:B:D:M', 'U:B:D:N', 'U:B:E:F',
        'U:B:E:H', 'U:B:E:J', 'U:B:E:K', 'U:B:E:P', 'U:B:E:Q', 'U:B:E:Z',
        'U:B:F:I', 'U:B:F:L', 'U:B:F:R', 'U:B:G:I', 'U:B:G:N', 'U:B:G:O',
        'U:B:H:I', 'U:B:H:O', 'U:B:H:R', 'U:B:H:S', 'U:B:I:J', 'U:B:I:V',
        'U:B:J:M', 'U:B:J:N', 'U:B:J:S', 'U:B:J:T', 'U:B:K:Z', 'U:B:L:P',
        'U:B:N:V', 'U:B:N:Y', 'U:B:O:P', 'U:B:P:R', 'U:B:P:T', 'U:B:R:V',
        'U:B:R:Y', 'U:B:V:Y', 'U:C:D:K', 'U:C:E:K', 'U:C:E:Z', 'U:C:F:I',
        'U:C:G:K', 'U:C:I:Y', 'U:C:K:N', 'U:C:K:O', 'U:D:E:K', 'U:D:E:V',
        'U:D:E:W', 'U:D:E:Y', 'U:D:E:Z', 'U:D:F:I', 'U:D:F:L', 'U:D:F:P',
        'U:D:F:R', 'U:D:G:Z', 'U:D:I:Q', 'U:D:I:V', 'U:D:I:W', 'U:D:I:Y',
        'U:D:K:L', 'U:D:K:N', 'U:D:K:O', 'U:D:K:R', 'U:D:L:W', 'U:D:N:W',
        'U:D:N:Y', 'U:D:R:V', 'U:D:R:W', 'U:D:T:W', 'U:E:F:G', 'U:E:F:P',
        'U:E:F:Q', 'U:E:G:K', 'U:E:G:M', 'U:E:G:Q', 'U:E:G:V', 'U:E:G:W',
        'U:E:G:Z', 'U:E:H:K', 'U:E:H:W', 'U:E:H:X', 'U:E:I:J', 'U:E:I:W',
        'U:E:J:M', 'U:E:J:N', 'U:E:J:S', 'U:E:J:T', 'U:E:K:L', 'U:E:K:M',
        'U:E:K:P', 'U:E:K:Z', 'U:E:L:W', 'U:E:M:V', 'U:E:M:Z', 'U:E:N:W',
        'U:E:O:W', 'U:E:P:Q', 'U:E:P:V', 'U:E:P:W', 'U:E:P:Z', 'U:E:Q:T',
        'U:E:Q:V', 'U:E:Q:X', 'U:E:Q:Y', 'U:E:R:W', 'U:E:R:Z', 'U:E:S:W',
        'U:E:T:W', 'U:E:T:X', 'U:E:T:Y', 'U:E:V:Z', 'U:E:Y:Z', 'U:F:H:I',
        'U:F:H:O', 'U:F:H:S', 'U:F:I:P', 'U:F:I:Q', 'U:F:I:X', 'U:F:I:Z',
        'U:F:L:P', 'U:F:L:Q', 'U:F:N:P', 'U:F:N:X', 'U:F:P:R', 'U:G:I:K',
        'U:G:I:Q', 'U:G:I:W', 'U:G:K:N', 'U:G:K:O', 'U:G:K:S', 'U:G:L:W',
        'U:G:N:W', 'U:G:O:Q', 'U:G:P:W', 'U:G:P:Y', 'U:G:P:Z', 'U:G:R:Z',
        'U:G:X:Y', 'U:H:I:K', 'U:H:I:P', 'U:H:I:Q', 'U:H:I:W', 'U:H:I:Z',
        'U:H:K:N', 'U:H:K:O', 'U:H:K:P', 'U:H:K:R', 'U:H:L:W', 'U:H:O:W',
        'U:H:R:W', 'U:H:S:W', 'U:H:S:Z', 'U:I:J:M', 'U:I:J:N', 'U:I:J:S',
        'U:I:J:T', 'U:I:K:N', 'U:I:K:P', 'U:I:L:W', 'U:I:M:Q', 'U:I:M:V',
        'U:I:M:X', 'U:I:M:Z', 'U:I:N:W', 'U:I:O:Q', 'U:I:O:V', 'U:I:O:W',
        'U:I:P:Q', 'U:I:P:V', 'U:I:P:W', 'U:I:P:X', 'U:I:Q:V', 'U:I:Q:X',
        'U:I:Q:Y', 'U:I:Q:Z', 'U:I:R:W', 'U:I:S:W', 'U:I:T:V', 'U:I:T:W',
        'U:I:T:Y', 'U:I:V:Y', 'U:I:V:Z', 'U:I:X:Y', 'U:I:Y:Z', 'U:J:M:N',
        'U:J:M:S', 'U:J:M:T', 'U:J:N:S', 'U:J:N:T', 'U:J:S:T', 'U:K:M:N',
        'U:K:M:R', 'U:K:M:S', 'U:K:N:O', 'U:K:N:P', 'U:K:N:R', 'U:K:N:T',
        'U:K:O:P', 'U:K:P:R', 'U:K:R:T', 'U:L:M:V', 'U:L:N:W', 'U:L:P:V',
        'U:L:P:W', 'U:L:Q:X', 'U:L:Q:Y', 'U:L:S:W', 'U:L:V:Y', 'U:L:V:Z',
        'U:M:N:V', 'U:M:N:Z', 'U:M:O:Z', 'U:M:R:V', 'U:M:R:Z', 'U:M:S:V',
        'U:M:S:Z', 'U:N:P:V', 'U:N:P:W', 'U:N:V:Y', 'U:N:V:Z', 'U:N:Y:Z',
        'U:O:P:Q', 'U:O:P:V', 'U:O:Q:X', 'U:O:Q:Z', 'U:O:R:W', 'U:O:X:Y',
        'U:P:R:X', 'U:P:S:V', 'U:P:X:Y', 'U:Q:R:X', 'U:Q:S:Z', 'U:Q:T:X',
        'U:R:T:W', 'U:R:V:Y', 'U:R:V:Z', 'U:R:X:Y', 'U:S:V:Y', 'U:S:V:Z',
        'V:A:B:Y', 'V:A:D:K', 'V:A:F:H', 'V:A:F:X', 'V:A:G:J', 'V:A:H:K',
        'V:A:J:M', 'V:A:J:Y', 'V:A:K:U', 'V:A:K:Y', 'V:A:Q:U', 'V:B:E:F',
        'V:B:E:H', 'V:B:E:K', 'V:B:E:P', 'V:B:E:Q', 'V:B:E:Y', 'V:B:E:Z',
        'V:B:F:R', 'V:B:G:K', 'V:B:H:O', 'V:B:I:K', 'V:B:I:P', 'V:B:K:L',
        'V:B:K:O', 'V:B:K:R', 'V:B:K:S', 'V:B:P:R', 'V:B:Q:R', 'V:B:Q:U',
        'V:C:D:J', 'V:C:F:H', 'V:C:H:K', 'V:C:H:Z', 'V:C:I:J', 'V:C:J:O',
        'V:C:K:O', 'V:C:K:T', 'V:D:E:Q', 'V:D:E:X', 'V:D:E:Y', 'V:D:I:J',
        'V:D:I:X', 'V:D:J:O', 'V:E:F:G', 'V:E:F:H', 'V:E:F:J', 'V:E:F:P',
        'V:E:F:Q', 'V:E:F:X', 'V:E:F:Y', 'V:E:F:Z', 'V:E:G:J', 'V:E:G:Q',
        'V:E:G:Z', 'V:E:H:Q', 'V:E:H:X', 'V:E:H:Z', 'V:E:J:M', 'V:E:J:Z',
        'V:E:K:Y', 'V:E:L:Q', 'V:E:M:Q', 'V:E:M:Z', 'V:E:P:X', 'V:E:P:Y',
        'V:E:P:Z', 'V:E:Q:X', 'V:E:Q:Y', 'V:E:Q:Z', 'V:E:X:Y', 'V:F:G:I',
        'V:F:H:I', 'V:F:H:L', 'V:F:H:N', 'V:F:H:R', 'V:F:I:J', 'V:F:I:P',
        'V:F:I:Q', 'V:F:I:X', 'V:F:I:Z', 'V:F:J:L', 'V:F:J:O', 'V:F:J:S',
        'V:F:J:U', 'V:F:L:Y', 'V:F:N:Q', 'V:F:N:X', 'V:F:N:Y', 'V:F:O:X',
        'V:F:P:R', 'V:F:Q:U', 'V:F:R:X', 'V:F:R:Y', 'V:F:T:X', 'V:G:H:I',
        'V:G:I:K', 'V:G:J:R', 'V:G:Q:U', 'V:G:X:Y', 'V:H:I:P', 'V:H:I:Q',
        'V:H:I:Y', 'V:H:K:O', 'V:H:K:R', 'V:H:K:T', 'V:H:K:U', 'V:H:O:X',
        'V:H:Q:U', 'V:I:J:L', 'V:I:J:P', 'V:I:K:N', 'V:I:K:Y', 'V:I:P:Y',
        'V:I:X:Y', 'V:J:M:R', 'V:J:M:S', 'V:J:M:T', 'V:J:M:U', 'V:J:N:Y',
        'V:J:O:P', 'V:J:R:Y', 'V:J:R:Z', 'V:J:T:Z', 'V:J:U:Z', 'V:K:L:P',
        'V:K:L:Y', 'V:K:O:P', 'V:K:O:T', 'V:K:O:U', 'V:K:R:Y', 'V:L:Q:U',
        'V:M:Q:U', 'V:N:Q:U', 'V:O:X:Y', 'V:P:Q:U', 'V:Q:R:U', 'V:Q:S:U',
        'V:Q:T:U', 'V:Q:U:X', 'V:Q:U:Y', 'V:Q:U:Z', 'V:U:X:Y', 'W:A:B:J',
        'W:A:B:K', 'W:A:B:P', 'W:A:B:Y', 'W:A:C:X', 'W:A:C:Z', 'W:A:E:J',
        'W:A:F:P', 'W:A:F:Q', 'W:A:F:V', 'W:A:G:K', 'W:A:G:Y', 'W:A:J:L',
        'W:A:J:N', 'W:A:J:O', 'W:A:J:R', 'W:A:J:U', 'W:A:K:V', 'W:A:M:Q',
        'W:A:M:V', 'W:A:N:Q', 'W:A:R:X', 'W:A:T:Y', 'W:A:V:Z', 'W:B:E:F',
        'W:B:E:G', 'W:B:E:J', 'W:B:E:K', 'W:B:E:P', 'W:B:E:R', 'W:B:E:Z',
        'W:B:F:O', 'W:B:F:R', 'W:B:G:P', 'W:B:H:I', 'W:B:H:P', 'W:B:I:P',
        'W:B:J:L', 'W:B:J:N', 'W:B:J:O', 'W:B:J:R', 'W:B:J:U', 'W:B:K:R',
        'W:B:L:Y', 'W:B:O:P', 'W:B:P:R', 'W:C:E:V', 'W:C:E:X', 'W:C:E:Y',
        'W:C:E:Z', 'W:C:F:V', 'W:C:G:K', 'W:C:G:S', 'W:C:H:X', 'W:C:I:Q',
        'W:C:I:V', 'W:C:I:X', 'W:C:I:Y', 'W:C:N:Y', 'W:C:O:P', 'W:C:O:V',
        'W:C:O:Y', 'W:C:P:Y', 'W:C:Q:U', 'W:C:Q:V', 'W:C:R:X', 'W:D:E:K',
        'W:D:E:Q', 'W:D:E:T', 'W:D:E:V', 'W:D:F:I', 'W:D:F:R', 'W:D:G:V',
        'W:D:H:I', 'W:D:H:O', 'W:D:H:V', 'W:D:I:M', 'W:D:I:P', 'W:D:I:Q',
        'W:D:I:V', 'W:D:K:Q', 'W:D:L:V', 'W:D:N:V', 'W:D:O:Q', 'W:D:O:V',
        'W:D:P:Q', 'W:D:Q:U', 'W:D:R:V', 'W:D:S:V', 'W:D:U:V', 'W:E:F:P',
        'W:E:F:V', 'W:E:F:Z', 'W:E:G:P', 'W:E:G:Q', 'W:E:G:V', 'W:E:H:Q',
        'W:E:H:V', 'W:E:H:X', 'W:E:I:Q', 'W:E:I:X', 'W:E:J:L', 'W:E:J:N',
        'W:E:J:O', 'W:E:J:R', 'W:E:J:U', 'W:E:K:Q', 'W:E:K:V', 'W:E:K:Z',
        'W:E:L:P', 'W:E:L:Q', 'W:E:L:X', 'W:E:L:Z', 'W:E:M:Q', 'W:E:M:V',
        'W:E:M:Y', 'W:E:M:Z', 'W:E:O:X', 'W:E:O:Y', 'W:E:P:Q', 'W:E:P:Y',
        'W:E:P:Z', 'W:E:Q:T', 'W:E:Q:U', 'W:E:Q:V', 'W:E:R:X', 'W:E:S:X',
        'W:E:T:V', 'W:E:U:V', 'W:E:V:Z', 'W:F:G:I', 'W:F:G:O', 'W:F:I:V',
        'W:F:I:Z', 'W:F:K:Z', 'W:F:N:V', 'W:F:O:P', 'W:F:O:V', 'W:F:P:R',
        'W:F:P:T', 'W:F:T:V', 'W:F:U:V', 'W:G:I:K', 'W:G:I:P', 'W:G:I:Q',
        'W:G:I:V', 'W:G:K:N', 'W:G:K:S', 'W:G:N:V', 'W:G:N:Y', 'W:G:N:Z',
        'W:G:O:P', 'W:G:Q:U', 'W:G:S:V', 'W:H:I:Q', 'W:H:I:V', 'W:H:I:X',
        'W:H:I:Y', 'W:H:K:Q', 'W:H:L:X', 'W:H:N:V', 'W:H:O:V', 'W:H:O:X',
        'W:H:P:Q', 'W:H:Q:U', 'W:H:R:V', 'W:H:R:X', 'W:H:S:V', 'W:H:S:X',
        'W:H:S:Y', 'W:H:T:Z', 'W:I:K:Q', 'W:I:K:Y', 'W:I:K:Z', 'W:I:L:Q',
        'W:I:L:X', 'W:I:M:Q', 'W:I:M:V', 'W:I:M:X', 'W:I:M:Y', 'W:I:N:Q',
        'W:I:O:Q', 'W:I:O:X', 'W:I:P:Q', 'W:I:P:Y', 'W:I:P:Z', 'W:I:Q:R',
        'W:I:Q:T', 'W:I:Q:U', 'W:I:Q:V', 'W:I:R:X', 'W:I:S:X', 'W:I:T:V',
        'W:I:U:V', 'W:I:V:Z', 'W:J:L:N', 'W:J:L:O', 'W:J:L:R', 'W:J:L:U',
        'W:J:N:O', 'W:J:N:R', 'W:J:N:U', 'W:J:O:R', 'W:J:O:U', 'W:J:R:U',
        'W:K:L:Q', 'W:K:O:Q', 'W:K:P:Q', 'W:K:Q:U', 'W:K:R:V', 'W:L:M:X',
        'W:L:O:V', 'W:L:O:X', 'W:L:O:Z', 'W:L:P:Q', 'W:L:Q:U', 'W:L:S:X',
        'W:M:N:Q', 'W:M:O:X', 'W:M:Q:U', 'W:M:S:X', 'W:N:P:Y', 'W:N:Q:U',
        'W:N:V:Z', 'W:O:P:Q', 'W:O:P:Y', 'W:O:Q:U', 'W:O:Q:V', 'W:O:S:X',
        'W:P:Q:U', 'W:Q:R:U', 'W:Q:R:V', 'W:Q:S:V', 'W:Q:T:U', 'W:Q:U:V',
        'W:T:V:Z', 'W:U:V:Z', 'X:A:B:L', 'X:A:B:M', 'X:A:B:O', 'X:A:B:Y',
        'X:A:C:G', 'X:A:C:O', 'X:A:D:E', 'X:A:D:G', 'X:A:D:N', 'X:A:D:O',
        'X:A:D:T', 'X:A:E:Q', 'X:A:E:U', 'X:A:E:V', 'X:A:E:Z', 'X:A:G:H',
        'X:A:G:M', 'X:A:G:P', 'X:A:G:Q', 'X:A:G:V', 'X:A:G:Z', 'X:A:H:Z',
        'X:A:I:Z', 'X:A:L:V', 'X:A:L:Z', 'X:A:O:V', 'X:A:O:Z', 'X:A:P:Z',
        'X:A:Q:U', 'X:A:R:V', 'X:A:R:Z', 'X:A:U:V', 'X:A:V:Y', 'X:A:Y:Z',
        'X:B:E:G', 'X:B:E:H', 'X:B:E:N', 'X:B:E:O', 'X:B:E:P', 'X:B:E:Q',
        'X:B:E:T', 'X:B:E:U', 'X:B:G:I', 'X:B:G:L', 'X:B:G:N', 'X:B:G:O',
        'X:B:H:N', 'X:B:H:O', 'X:B:H:P', 'X:B:I:O', 'X:B:I:Q', 'X:B:I:R',
        'X:B:I:T', 'X:B:I:U', 'X:B:L:M', 'X:B:L:O', 'X:B:L:Y', 'X:B:M:O',
        'X:B:M:Y', 'X:B:N:O', 'X:B:N:P', 'X:B:N:Q', 'X:B:N:U', 'X:B:O:P',
        'X:B:O:Q', 'X:B:O:R', 'X:B:O:S', 'X:B:O:T', 'X:B:O:U', 'X:B:O:Y',
        'X:B:Q:U', 'X:C:D:E', 'X:C:D:G', 'X:C:D:I', 'X:C:D:N', 'X:C:D:O',
        'X:C:E:G', 'X:C:E:P', 'X:C:E:Q', 'X:C:E:U', 'X:C:G:I', 'X:C:G:N',
        'X:C:G:O', 'X:C:G:S', 'X:C:G:T', 'X:C:H:O', 'X:C:H:Q', 'X:C:I:Q',
        'X:C:L:O', 'X:C:M:O', 'X:C:M:Q', 'X:C:N:Q', 'X:C:O:P', 'X:C:O:Q',
        'X:C:O:Y', 'X:C:Q:R', 'X:C:Q:U', 'X:D:E:G', 'X:D:E:H', 'X:D:E:I',
        'X:D:E:L', 'X:D:E:M', 'X:D:E:N', 'X:D:E:O', 'X:D:E:P', 'X:D:E:Q',
        'X:D:E:R', 'X:D:E:S', 'X:D:E:T', 'X:D:E:U', 'X:D:E:V', 'X:D:E:Y',
        'X:D:G:I', 'X:D:G:N', 'X:D:G:O', 'X:D:G:S', 'X:D:G:T', 'X:D:H:O',
        'X:D:H:P', 'X:D:I:L', 'X:D:I:P', 'X:D:I:V', 'X:D:I:Y', 'X:D:L:Y',
        'X:D:M:O', 'X:D:M:R', 'X:D:N:T', 'X:D:N:V', 'X:D:O:P', 'X:D:O:Q',
        'X:D:O:R', 'X:D:O:T', 'X:D:O:U', 'X:D:O:V', 'X:D:Q:U', 'X:D:S:V',
        'X:E:F:G', 'X:E:F:I', 'X:E:F:L', 'X:E:F:N', 'X:E:F:O', 'X:E:F:R',
        'X:E:F:S', 'X:E:F:U', 'X:E:F:Y', 'X:E:G:M', 'X:E:G:Q', 'X:E:G:V',
        'X:E:G:Z', 'X:E:H:Q', 'X:E:H:U', 'X:E:H:Z', 'X:E:I:Q', 'X:E:I:Z',
        'X:E:L:Q', 'X:E:L:U', 'X:E:L:Z', 'X:E:M:P', 'X:E:M:Q', 'X:E:M:U',
        'X:E:N:Q', 'X:E:O:Q', 'X:E:O:Z', 'X:E:P:Q', 'X:E:P:U', 'X:E:P:Z',
        'X:E:Q:R', 'X:E:Q:S', 'X:E:Q:T', 'X:E:Q:U', 'X:E:Q:Y', 'X:E:R:U',
        'X:E:R:V', 'X:E:R:Z', 'X:E:S:U', 'X:E:T:U', 'X:E:U:V', 'X:E:U:Y',
        'X:E:V:Y', 'X:E:Y:Z', 'X:F:G:I', 'X:F:G:N', 'X:F:G:O', 'X:F:G:U',
        'X:F:I:N', 'X:F:I:O', 'X:F:I:U', 'X:F:L:O', 'X:F:L:R', 'X:F:L:Y',
        'X:F:N:O', 'X:F:N:U', 'X:F:O:R', 'X:F:O:S', 'X:F:O:U', 'X:F:O:Y',
        'X:F:R:Y', 'X:G:H:M', 'X:G:H:O', 'X:G:H:P', 'X:G:H:Q', 'X:G:H:Z',
        'X:G:I:M', 'X:G:I:Q', 'X:G:I:Z', 'X:G:L:O', 'X:G:L:V', 'X:G:L:Y',
        'X:G:L:Z', 'X:G:M:O', 'X:G:M:P', 'X:G:M:R', 'X:G:M:S', 'X:G:O:P',
        'X:G:O:Q', 'X:G:O:R', 'X:G:O:T', 'X:G:O:U', 'X:G:O:V', 'X:G:O:Y',
        'X:G:O:Z', 'X:G:P:Z', 'X:G:Q:U', 'X:G:R:V', 'X:G:R:Z', 'X:G:U:V',
        'X:G:V:Y', 'X:G:Y:Z', 'X:H:I:Z', 'X:H:L:Z', 'X:H:M:Q', 'X:H:M:U',
        'X:H:O:Z', 'X:H:P:Z', 'X:H:Q:U', 'X:H:R:Z', 'X:H:Y:Z', 'X:I:L:Z',
        'X:I:M:Q', 'X:I:M:U', 'X:I:N:V', 'X:I:O:Z', 'X:I:P:Q', 'X:I:P:Z',
        'X:I:Q:U', 'X:I:R:Z', 'X:I:Y:Z', 'X:L:O:V', 'X:L:O:Z', 'X:L:P:Z',
        'X:L:Q:U', 'X:L:R:V', 'X:L:R:Z', 'X:L:U:V', 'X:L:V:Y', 'X:L:Y:Z',
        'X:M:O:Q', 'X:M:O:U', 'X:M:Q:R', 'X:M:Q:U', 'X:N:O:V', 'X:N:Q:U',
        'X:N:S:V', 'X:O:P:Q', 'X:O:P:U', 'X:O:P:Z', 'X:O:Q:U', 'X:O:R:V',
        'X:O:R:Y', 'X:O:R:Z', 'X:O:U:V', 'X:O:V:Y', 'X:O:Y:Z', 'X:P:Q:U',
        'X:P:R:Z', 'X:P:Y:Z', 'X:Q:R:U', 'X:Q:S:U', 'X:Q:T:U', 'X:Q:U:Y',
        'X:R:U:V', 'X:R:V:Y', 'X:R:Y:Z', 'X:U:V:Y', 'Y:A:B:D', 'Y:A:B:G',
        'Y:A:B:J', 'Y:A:C:F', 'Y:A:C:G', 'Y:A:C:P', 'Y:A:C:X', 'Y:A:D:F',
        'Y:A:D:G', 'Y:A:D:J', 'Y:A:D:X', 'Y:A:E:Q', 'Y:A:G:L', 'Y:A:G:V',
        'Y:A:H:W', 'Y:A:J:N', 'Y:A:J:R', 'Y:A:K:X', 'Y:A:K:Z', 'Y:A:M:W',
        'Y:A:N:X', 'Y:A:O:X', 'Y:A:P:V', 'Y:A:P:X', 'Y:A:Q:U', 'Y:A:Q:V',
        'Y:A:R:X', 'Y:A:T:X', 'Y:A:U:X', 'Y:B:D:I', 'Y:B:D:J', 'Y:B:D:N',
        'Y:B:D:R', 'Y:B:E:Q', 'Y:B:E:W', 'Y:B:I:J', 'Y:B:I:N', 'Y:B:J:N',
        'Y:B:J:R', 'Y:B:O:Q', 'Y:B:O:W', 'Y:B:Q:S', 'Y:B:Q:U', 'Y:B:R:W',
        'Y:B:S:W', 'Y:B:T:W', 'Y:C:E:J', 'Y:C:E:Q', 'Y:C:H:W', 'Y:C:J:L',
        'Y:C:J:O', 'Y:C:J:S', 'Y:C:J:T', 'Y:C:J:U', 'Y:C:K:X', 'Y:C:L:O',
        'Y:C:L:T', 'Y:C:M:W', 'Y:C:O:P', 'Y:C:O:W', 'Y:C:O:X', 'Y:C:Q:U',
        'Y:C:Q:V', 'Y:C:S:V', 'Y:C:T:W', 'Y:C:T:X', 'Y:C:U:X', 'Y:D:E:M',
        'Y:D:E:P', 'Y:D:E:V', 'Y:D:F:O', 'Y:D:F:R', 'Y:D:F:S', 'Y:D:F:T',
        'Y:D:G:I', 'Y:D:G:N', 'Y:D:G:R', 'Y:D:G:S', 'Y:D:H:P', 'Y:D:I:J',
        'Y:D:I:P', 'Y:D:I:V', 'Y:D:J:N', 'Y:D:J:R', 'Y:D:L:O', 'Y:D:M:S',
        'Y:D:M:Z', 'Y:D:N:P', 'Y:D:N:V', 'Y:D:N:X', 'Y:D:O:P', 'Y:D:O:T',
        'Y:D:O:V', 'Y:D:O:X', 'Y:D:P:S', 'Y:D:R:V', 'Y:D:S:V', 'Y:D:U:X',
        'Y:E:F:I', 'Y:E:F:K', 'Y:E:F:L', 'Y:E:F:U', 'Y:E:F:W', 'Y:E:G:L',
        'Y:E:G:Q', 'Y:E:H:L', 'Y:E:H:P', 'Y:E:I:W', 'Y:E:J:L', 'Y:E:J:O',
        'Y:E:J:S', 'Y:E:J:T', 'Y:E:J:U', 'Y:E:K:V', 'Y:E:K:W', 'Y:E:L:Q',
        'Y:E:L:R', 'Y:E:L:Z', 'Y:E:M:P', 'Y:E:M:Q', 'Y:E:M:Z', 'Y:E:N:Q',
        'Y:E:O:Q', 'Y:E:O:W', 'Y:E:P:V', 'Y:E:P:X', 'Y:E:Q:R', 'Y:E:Q:T',
        'Y:E:Q:V', 'Y:E:R:W', 'Y:E:R:X', 'Y:E:R:Z', 'Y:E:U:X', 'Y:F:I:K',
        'Y:F:I:L', 'Y:F:I:N', 'Y:F:I:U', 'Y:F:I:W', 'Y:F:K:L', 'Y:F:K:N',
        'Y:F:K:O', 'Y:F:K:W', 'Y:F:L:O', 'Y:F:L:U', 'Y:F:L:W', 'Y:F:N:W',
        'Y:F:O:U', 'Y:F:O:W', 'Y:F:R:T', 'Y:F:R:U', 'Y:F:T:U', 'Y:G:I:J',
        'Y:G:I:K', 'Y:G:I:Q', 'Y:G:J:K', 'Y:G:J:O', 'Y:G:J:U', 'Y:G:K:O',
        'Y:G:K:U', 'Y:G:O:Q', 'Y:G:Q:U', 'Y:G:S:V', 'Y:H:I:L', 'Y:H:I:P',
        'Y:H:I:V', 'Y:H:L:O', 'Y:H:L:T', 'Y:H:M:W', 'Y:H:N:P', 'Y:H:N:W',
        'Y:H:O:P', 'Y:H:O:W', 'Y:H:P:S', 'Y:H:S:V', 'Y:H:T:W', 'Y:I:J:K',
        'Y:I:J:N', 'Y:I:J:R', 'Y:I:K:V', 'Y:I:K:W', 'Y:I:L:W', 'Y:I:M:Q',
        'Y:I:M:V', 'Y:I:M:Z', 'Y:I:N:Q', 'Y:I:N:W', 'Y:I:O:W', 'Y:I:P:V',
        'Y:I:Q:U', 'Y:I:Q:V', 'Y:J:K:O', 'Y:J:K:U', 'Y:J:L:O', 'Y:J:L:S',
        'Y:J:L:T', 'Y:J:L:U', 'Y:J:N:R', 'Y:J:O:S', 'Y:J:O:T', 'Y:J:O:U',
        'Y:J:S:T', 'Y:J:S:U', 'Y:J:T:U', 'Y:K:L:V', 'Y:K:L:W', 'Y:K:N:V',
        'Y:K:N:W', 'Y:K:O:P', 'Y:K:O:V', 'Y:K:O:W', 'Y:K:O:X', 'Y:K:S:V',
        'Y:K:T:V', 'Y:K:T:X', 'Y:K:U:X', 'Y:K:U:Z', 'Y:L:M:O', 'Y:L:M:S',
        'Y:L:O:Z', 'Y:L:P:V', 'Y:L:S:V', 'Y:M:N:W', 'Y:M:O:P', 'Y:M:O:Q',
        'Y:M:O:V', 'Y:M:O:W', 'Y:M:P:T', 'Y:M:Q:T', 'Y:M:Q:U', 'Y:M:S:V',
        'Y:M:S:Z', 'Y:M:T:W', 'Y:N:O:W', 'Y:N:O:X', 'Y:N:Q:U', 'Y:N:U:X',
        'Y:O:Q:U', 'Y:O:R:W', 'Y:O:T:V', 'Y:O:T:W', 'Y:O:T:X', 'Y:O:T:Z',
        'Y:O:U:X', 'Y:P:R:V', 'Y:P:R:X', 'Y:P:S:V', 'Y:P:U:X', 'Y:Q:R:U',
        'Y:Q:R:V', 'Y:Q:S:V', 'Y:Q:T:U', 'Y:Q:U:V', 'Y:R:S:W', 'Y:R:T:W',
        'Y:R:U:X', 'Y:S:T:V', 'Y:T:U:X', 'Z:A:B:K', 'Z:A:B:X', 'Z:A:C:V',
        'Z:A:C:X', 'Z:A:D:L', 'Z:A:D:W', 'Z:A:D:X', 'Z:A:F:G', 'Z:A:F:P',
        'Z:A:F:Q', 'Z:A:F:W', 'Z:A:G:V', 'Z:A:H:J', 'Z:A:H:K', 'Z:A:H:X',
        'Z:A:I:J', 'Z:A:J:M', 'Z:A:J:N', 'Z:A:J:R', 'Z:A:K:W', 'Z:A:L:X',
        'Z:A:M:W', 'Z:A:M:X', 'Z:A:Q:X', 'Z:A:R:X', 'Z:A:V:Y', 'Z:A:W:Y',
        'Z:B:C:K', 'Z:B:D:E', 'Z:B:D:O', 'Z:B:E:G', 'Z:B:E:K', 'Z:B:E:P',
        'Z:B:E:Q', 'Z:B:E:W', 'Z:B:E:X', 'Z:B:F:I', 'Z:B:F:O', 'Z:B:G:I',
        'Z:B:I:K', 'Z:B:J:O', 'Z:B:K:W', 'Z:B:O:P', 'Z:B:Q:U', 'Z:B:R:X',
        'Z:B:U:X', 'Z:C:D:X', 'Z:C:E:F', 'Z:C:E:K', 'Z:C:E:Q', 'Z:C:E:W',
        'Z:C:F:I', 'Z:C:H:K', 'Z:C:I:K', 'Z:C:I:V', 'Z:C:I:W', 'Z:C:I:X',
        'Z:C:K:W', 'Z:C:O:Y', 'Z:C:Q:U', 'Z:C:U:X', 'Z:D:E:F', 'Z:D:E:K',
        'Z:D:E:P', 'Z:D:E:W', 'Z:D:F:P', 'Z:D:I:Q', 'Z:D:I:V', 'Z:D:I:W',
        'Z:D:I:X', 'Z:D:L:W', 'Z:D:O:X', 'Z:D:U:X', 'Z:E:F:G', 'Z:E:F:L',
        'Z:E:F:P', 'Z:E:F:W', 'Z:E:G:Q', 'Z:E:G:V', 'Z:E:G:X', 'Z:E:H:J',
        'Z:E:H:K', 'Z:E:H:Q', 'Z:E:H:X', 'Z:E:J:L', 'Z:E:J:P', 'Z:E:J:R',
        'Z:E:J:T', 'Z:E:K:Q', 'Z:E:K:V', 'Z:E:K:W', 'Z:E:L:Q', 'Z:E:L:V',
        'Z:E:L:W', 'Z:E:L:X', 'Z:E:M:Q', 'Z:E:M:V', 'Z:E:M:W', 'Z:E:N:V',
        'Z:E:O:V', 'Z:E:P:Q', 'Z:E:P:V', 'Z:E:P:W', 'Z:E:Q:R', 'Z:E:Q:X',
        'Z:E:Q:Y', 'Z:E:R:V', 'Z:E:R:W', 'Z:E:S:X', 'Z:E:T:V', 'Z:E:T:X',
        'Z:E:U:V', 'Z:F:G:W', 'Z:F:I:M', 'Z:F:I:Q', 'Z:F:M:O', 'Z:F:N:W',
        'Z:F:O:P', 'Z:F:O:Q', 'Z:F:O:U', 'Z:F:P:R', 'Z:F:P:S', 'Z:F:P:T',
        'Z:F:Q:S', 'Z:F:Q:U', 'Z:F:R:W', 'Z:G:I:Q', 'Z:G:I:V', 'Z:G:I:X',
        'Z:G:N:V', 'Z:G:O:Q', 'Z:G:O:X', 'Z:G:Q:U', 'Z:G:U:X', 'Z:H:I:J',
        'Z:H:I:K', 'Z:H:J:N', 'Z:H:J:O', 'Z:H:J:P', 'Z:H:J:R', 'Z:H:J:T',
        'Z:H:K:N', 'Z:H:K:O', 'Z:H:K:R', 'Z:H:K:S', 'Z:H:L:X', 'Z:H:N:X',
        'Z:H:Q:U', 'Z:H:T:X', 'Z:I:J:R', 'Z:I:K:Q', 'Z:I:K:W', 'Z:I:L:W',
        'Z:I:M:Q', 'Z:I:N:Q', 'Z:I:Q:X', 'Z:I:Q:Y', 'Z:I:W:Y', 'Z:J:L:O',
        'Z:J:L:S', 'Z:J:L:T', 'Z:J:L:U', 'Z:J:M:N', 'Z:J:N:R', 'Z:J:O:P',
        'Z:J:O:R', 'Z:J:O:T', 'Z:J:O:U', 'Z:J:P:R', 'Z:J:P:T', 'Z:J:R:T',
        'Z:K:L:V', 'Z:K:O:P', 'Z:K:O:Q', 'Z:K:Q:R', 'Z:K:Q:S', 'Z:K:Q:T',
        'Z:K:Q:U', 'Z:L:N:X', 'Z:L:O:X', 'Z:L:Q:U', 'Z:L:T:X', 'Z:M:Q:U',
        'Z:M:T:V', 'Z:N:U:W', 'Z:O:P:V', 'Z:O:P:W', 'Z:O:Q:U', 'Z:O:Q:X',
        'Z:O:U:V', 'Z:P:Q:U', 'Z:P:S:V', 'Z:P:S:W', 'Z:P:T:V', 'Z:P:T:W',
        'Z:Q:R:U', 'Z:Q:T:U', 'Z:Q:T:X', 'Z:Q:U:X', 'Z:Q:U:Y', 'Z:R:U:X',
    ];

    /**
     * Doublons de contenu entre pages SOEURS du meme prefixe (D-045) : regroupement par
     * (prefixe, count), verification par empreinte (liste triee des mots reels du panier). 1 909
     * cles trouvees (perdantes, canonicalisees vers la cle gagnante la plus petite
     * alphabetiquement) -- voir docs/DECISIONS.md D-045.
     *
     * @var list<string>
     */
    private const SIBLING_DUPLICATE_KEYS = [
        'A:B:K:O', 'A:B:K:U', 'A:B:K:W', 'A:B:K:Y', 'A:B:N:W', 'A:B:O:W',
        'A:C:H:J', 'A:C:H:W', 'A:C:I:W', 'A:C:M:W', 'A:C:N:W', 'A:C:R:W',
        'A:D:J:Q', 'A:D:K:T', 'A:D:K:U', 'A:D:R:W', 'A:E:K:X', 'A:E:W:Z',
        'A:F:J:T', 'A:F:K:L', 'A:F:K:N', 'A:F:K:O', 'A:F:K:T', 'A:F:L:Y',
        'A:F:P:Y', 'A:G:K:U', 'A:H:I:W', 'A:H:J:L', 'A:H:J:O', 'A:H:J:T',
        'A:H:K:U', 'A:H:K:Y', 'A:H:M:W', 'A:H:N:W', 'A:H:R:W', 'A:H:W:Z',
        'A:I:M:W', 'A:I:W:Z', 'A:J:L:V', 'A:J:V:X', 'A:J:V:Z', 'A:J:X:Y',
        'A:K:L:V', 'A:K:L:X', 'A:K:M:Z', 'A:K:N:V', 'A:K:N:W', 'A:K:O:V',
        'A:K:P:Y', 'A:K:U:X', 'A:K:U:Y', 'A:K:W:Z', 'A:K:X:Y', 'A:L:M:W',
        'A:L:R:W', 'A:L:T:W', 'A:L:X:Z', 'A:M:N:W', 'A:M:O:W', 'A:M:R:W',
        'A:N:W:Z', 'A:X:Y:Z', 'B:A:J:P', 'B:C:H:J', 'B:C:I:W', 'B:C:J:M',
        'B:C:K:P', 'B:C:P:V', 'B:C:W:Z', 'B:D:G:J', 'B:D:K:L', 'B:D:K:U',
        'B:D:K:W', 'B:D:R:W', 'B:E:F:P', 'B:E:H:J', 'B:E:J:P', 'B:E:J:X',
        'B:F:G:Z', 'B:F:I:P', 'B:F:J:L', 'B:F:J:O', 'B:F:J:P', 'B:F:J:T',
        'B:F:J:U', 'B:F:L:P', 'B:F:M:Z', 'B:F:P:R', 'B:F:P:T', 'B:F:P:U',
        'B:F:T:Y', 'B:G:I:J', 'B:G:J:L', 'B:G:J:O', 'B:G:J:U', 'B:G:M:V',
        'B:G:T:X', 'B:G:U:W', 'B:H:J:M', 'B:H:J:N', 'B:H:J:P', 'B:H:J:R',
        'B:H:J:U', 'B:H:K:V', 'B:H:P:X', 'B:H:T:W', 'B:H:U:W', 'B:H:W:Z',
        'B:I:K:V', 'B:I:K:W', 'B:I:K:Y', 'B:I:P:V', 'B:I:U:W', 'B:J:L:P',
        'B:J:L:V', 'B:J:M:X', 'B:J:O:V', 'B:J:P:R', 'B:J:T:V', 'B:J:U:V',
        'B:K:L:W', 'B:K:N:W', 'B:K:N:Y', 'B:K:O:V', 'B:K:O:W', 'B:K:P:U',
        'B:K:P:Z', 'B:K:Q:R', 'B:K:R:Y', 'B:K:U:V', 'B:L:M:W', 'B:L:P:X',
        'B:M:O:W', 'B:M:Q:Z', 'B:M:S:W', 'B:N:P:V', 'B:N:P:X', 'B:N:W:Z',
        'B:O:W:Z', 'B:P:R:V', 'B:R:W:Z', 'B:S:W:Z', 'B:U:V:Y', 'C:B:H:J',
        'C:B:I:W', 'C:B:K:P', 'C:B:K:R', 'C:B:K:Y', 'C:B:N:W', 'C:B:R:W',
        'C:B:T:W', 'C:B:W:Y', 'C:D:H:J', 'C:D:K:L', 'C:D:K:N', 'C:D:K:T',
        'C:D:K:U', 'C:D:L:W', 'C:D:S:W', 'C:D:W:Z', 'C:F:G:W', 'C:F:H:W',
        'C:F:I:W', 'C:F:J:R', 'C:F:J:T', 'C:F:L:W', 'C:F:N:W', 'C:F:R:W',
        'C:F:S:W', 'C:F:U:W', 'C:G:H:W', 'C:G:J:P', 'C:G:K:U', 'C:G:R:W',
        'C:H:J:N', 'C:H:J:O', 'C:H:J:P', 'C:H:J:R', 'C:H:J:S', 'C:H:J:U',
        'C:H:K:W', 'C:H:U:W', 'C:I:P:W', 'C:I:W:Y', 'C:J:M:Y', 'C:J:P:U',
        'C:J:T:Y', 'C:K:N:W', 'C:K:Q:R', 'C:K:Q:S', 'C:K:Q:T', 'C:K:Q:Y',
        'C:K:R:V', 'C:K:R:W', 'C:K:S:V', 'C:K:U:V', 'C:K:U:W', 'C:M:P:W',
        'C:N:W:Y', 'C:O:W:Z', 'C:P:W:Y', 'C:P:X:Z', 'C:R:W:Y', 'C:T:W:Z',
        'C:U:W:Z', 'C:V:X:Z', 'C:X:Y:Z', 'D:B:F:J', 'D:B:J:V', 'D:C:O:W',
        'D:C:Q:X', 'D:C:R:W', 'D:E:U:W', 'D:F:I:J', 'D:F:J:L', 'D:F:J:M',
        'D:F:J:N', 'D:F:J:S', 'D:F:J:T', 'D:G:K:Z', 'D:H:J:U', 'D:I:Q:V',
        'D:I:U:W', 'D:J:S:Y', 'D:J:T:V', 'D:J:U:V', 'D:J:V:Z', 'D:K:L:Y',
        'D:K:M:W', 'D:K:N:P', 'D:K:N:V', 'D:K:O:P', 'D:K:P:S', 'D:K:P:T',
        'D:K:Q:Y', 'D:K:S:V', 'D:K:T:V', 'D:K:U:W', 'D:K:U:Y', 'D:K:W:Z',
        'D:M:O:W', 'D:N:U:W', 'D:N:W:Z', 'D:O:U:W', 'D:O:W:Z', 'D:Q:T:V',
        'D:T:U:W', 'E:B:K:M', 'E:B:K:R', 'E:B:K:T', 'E:C:D:W', 'E:C:K:Z',
        'E:C:T:W', 'E:C:W:Z', 'E:D:J:M', 'E:D:J:R', 'E:D:J:U', 'E:D:J:X',
        'E:D:K:L', 'E:D:K:O', 'E:D:K:R', 'E:D:K:W', 'E:D:K:Z', 'E:D:N:W',
        'E:D:T:W', 'E:D:W:Z', 'E:F:H:Y', 'E:F:Q:Y', 'E:G:H:W', 'E:G:J:X',
        'E:G:M:W', 'E:G:O:W', 'E:G:W:Z', 'E:H:K:M', 'E:H:K:W', 'E:H:M:W',
        'E:H:O:W', 'E:H:R:W', 'E:H:T:W', 'E:I:J:X', 'E:I:M:W', 'E:J:T:X',
        'E:K:L:W', 'E:K:L:Z', 'E:K:M:W', 'E:K:N:P', 'E:K:N:X', 'E:K:O:W',
        'E:K:P:R', 'E:K:P:Y', 'E:K:U:Y', 'E:K:W:Z', 'E:K:Y:Z', 'E:L:N:W',
        'E:L:W:Z', 'E:M:N:W', 'E:M:R:W', 'E:N:W:Z', 'E:O:T:W', 'E:O:W:X',
        'E:O:W:Z', 'E:P:V:Y', 'F:A:P:Q', 'F:B:H:P', 'F:B:L:V', 'F:B:L:W',
        'F:B:O:W', 'F:B:R:V', 'F:B:R:W', 'F:B:T:V', 'F:B:T:W', 'F:C:J:M',
        'F:D:J:M', 'F:D:K:L', 'F:D:L:W', 'F:D:N:Q', 'F:D:O:W', 'F:D:Q:Y',
        'F:D:R:W', 'F:D:U:V', 'F:E:H:X', 'F:E:K:Y', 'F:G:J:R', 'F:G:P:Q',
        'F:G:P:V', 'F:H:K:O', 'F:H:K:R', 'F:H:K:T', 'F:H:K:U', 'F:H:K:Y',
        'F:H:M:P', 'F:H:P:Q', 'F:H:P:Y', 'F:H:P:Z', 'F:H:Q:U', 'F:H:Q:Y',
        'F:H:R:X', 'F:H:U:V', 'F:I:J:M', 'F:I:K:Y', 'F:I:P:Q', 'F:J:L:T',
        'F:J:N:V', 'F:J:O:V', 'F:J:R:V', 'F:J:U:Z', 'F:K:L:Y', 'F:K:M:X',
        'F:K:T:X', 'F:K:T:Y', 'F:L:P:Q', 'F:M:P:Q', 'F:M:Q:Y', 'F:O:P:V',
        'F:O:X:Y', 'F:P:Q:R', 'F:P:Q:U', 'F:T:X:Y', 'F:U:V:Y', 'F:X:Y:Z',
        'G:B:F:L', 'G:B:H:V', 'G:B:K:N', 'G:B:K:O', 'G:B:K:R', 'G:B:K:T',
        'G:B:K:U', 'G:B:K:Z', 'G:B:O:W', 'G:B:T:V', 'G:B:U:W', 'G:C:J:R',
        'G:C:K:Z', 'G:D:I:K', 'G:D:K:L', 'G:D:K:N', 'G:D:K:O', 'G:D:K:U',
        'G:D:K:V', 'G:D:N:W', 'G:D:O:W', 'G:D:T:X', 'G:D:U:W', 'G:E:K:P',
        'G:E:K:W', 'G:F:H:L', 'G:F:H:S', 'G:F:H:T', 'G:F:H:U', 'G:F:I:P',
        'G:F:O:Q', 'G:F:P:T', 'G:F:P:U', 'G:F:Q:R', 'G:F:Q:V', 'G:H:K:R',
        'G:H:K:U', 'G:H:N:W', 'G:H:O:W', 'G:H:O:X', 'G:H:R:W', 'G:H:T:W',
        'G:I:K:P', 'G:I:K:V', 'G:I:W:Z', 'G:J:U:Z', 'G:K:L:P', 'G:K:L:V',
        'G:K:L:Z', 'G:K:M:U', 'G:K:N:P', 'G:K:N:V', 'G:K:N:Z', 'G:K:O:Z',
        'G:K:R:W', 'G:K:S:Y', 'G:K:T:Z', 'G:K:U:W', 'G:K:U:Z', 'G:L:X:Z',
        'G:M:R:W', 'G:M:T:W', 'G:M:U:W', 'G:M:W:Z', 'G:N:W:Z', 'G:O:P:V',
        'G:O:R:W', 'G:P:R:X', 'G:P:T:X', 'G:Q:T:X', 'G:Q:T:Z', 'G:Q:X:Y',
        'G:T:W:Z', 'H:A:W:Y', 'H:B:F:U', 'H:B:I:K', 'H:B:K:M', 'H:B:K:Z',
        'H:B:T:X', 'H:B:V:Y', 'H:B:X:Y', 'H:C:J:M', 'H:C:V:Y', 'H:D:J:L',
        'H:D:J:M', 'H:D:J:O', 'H:D:J:T', 'H:D:K:Y', 'H:E:I:J', 'H:E:J:M',
        'H:E:K:M', 'H:F:L:Q', 'H:F:O:Q', 'H:F:P:Q', 'H:F:P:Z', 'H:F:Q:T',
        'H:F:R:X', 'H:F:T:X', 'H:G:K:M', 'H:G:K:Y', 'H:G:O:W', 'H:G:R:W',
        'H:G:V:Y', 'H:G:W:Y', 'H:I:J:M', 'H:I:J:O', 'H:I:O:W', 'H:J:K:N',
        'H:J:L:M', 'H:J:M:N', 'H:J:M:O', 'H:J:M:R', 'H:J:M:T', 'H:J:O:R',
        'H:K:L:P', 'H:K:L:Z', 'H:K:M:P', 'H:K:M:Y', 'H:K:P:Q', 'H:K:P:U',
        'H:K:Q:V', 'H:K:Q:Y', 'H:K:T:V', 'H:K:U:V', 'H:K:U:Z', 'H:K:V:Z',
        'H:K:Y:Z', 'H:L:U:W', 'H:L:W:Y', 'H:M:V:Y', 'H:N:U:W', 'H:N:W:Y',
        'H:O:U:W', 'H:O:V:Z', 'H:O:W:Y', 'H:P:Q:V', 'H:Q:V:Y', 'H:R:U:W',
        'H:S:X:Z', 'H:U:W:Y', 'H:V:X:Y', 'H:X:Y:Z', 'I:A:R:W', 'I:A:T:W',
        'I:A:V:W', 'I:B:J:M', 'I:B:J:X', 'I:B:U:Y', 'I:B:X:Y', 'I:C:H:J',
        'I:E:H:J', 'I:F:L:Y', 'I:F:R:Y', 'I:F:S:Y', 'I:F:T:Y', 'I:G:H:Y',
        'I:H:J:M', 'I:H:J:O', 'I:H:J:R', 'I:H:K:O', 'I:H:K:R', 'I:H:L:X',
        'I:H:P:Z', 'I:J:L:R', 'I:J:N:X', 'I:J:R:X', 'I:J:S:Z', 'I:J:U:V',
        'I:K:L:P', 'I:K:N:P', 'I:K:O:P', 'I:K:O:U', 'I:K:P:R', 'I:K:P:T',
        'I:K:R:U', 'I:M:U:Y', 'I:O:V:W', 'I:O:V:X', 'I:O:V:Y', 'I:P:Q:X',
        'I:P:U:Y', 'I:P:V:Y', 'I:P:V:Z', 'I:Q:T:X', 'I:S:V:W', 'I:S:V:X',
        'I:S:W:Z', 'I:T:U:W', 'I:T:X:Y', 'I:U:V:W', 'I:U:X:Y', 'I:U:X:Z',
        'J:B:D:P', 'J:B:F:N', 'J:B:H:L', 'J:B:H:N', 'J:B:H:P', 'J:B:H:R',
        'J:B:K:L', 'J:B:K:R', 'J:B:L:P', 'J:B:L:X', 'J:B:N:X', 'J:B:O:Y',
        'J:B:P:T', 'J:B:P:X', 'J:B:R:Y', 'J:B:S:X', 'J:B:T:X', 'J:C:F:T',
        'J:C:G:H', 'J:C:H:V', 'J:C:M:V', 'J:C:M:Y', 'J:C:R:X', 'J:D:H:N',
        'J:D:K:T', 'J:D:N:V', 'J:D:N:X', 'J:D:P:Z', 'J:D:R:X', 'J:D:U:V',
        'J:E:N:W', 'J:E:W:Z', 'J:F:I:L', 'J:F:L:M', 'J:F:L:N', 'J:F:L:T',
        'J:F:M:O', 'J:F:M:R', 'J:F:M:S', 'J:F:O:V', 'J:F:U:V', 'J:G:H:L',
        'J:G:H:S', 'J:G:H:U', 'J:G:L:P', 'J:G:N:V', 'J:G:P:R', 'J:G:R:X',
        'J:G:U:X', 'J:H:I:Q', 'J:H:K:L', 'J:H:K:N', 'J:H:K:P', 'J:H:K:R',
        'J:H:K:U', 'J:H:L:R', 'J:H:M:V', 'J:H:N:Q', 'J:H:P:Z', 'J:I:L:Y',
        'J:I:O:W', 'J:K:L:R', 'J:K:L:U', 'J:K:L:Y', 'J:K:M:N', 'J:K:P:U',
        'J:K:R:Y', 'J:K:T:Y', 'J:K:U:Y', 'J:L:M:Y', 'J:L:R:Y', 'J:L:U:Y',
        'J:M:N:X', 'J:M:O:Y', 'J:M:T:X', 'J:N:Q:V', 'J:N:V:X', 'J:N:V:Y',
        'J:N:Y:Z', 'J:O:Y:Z', 'J:P:X:Z', 'J:Q:R:V', 'J:Q:S:V', 'J:Q:T:V',
        'J:R:V:Y', 'J:S:X:Z', 'J:U:V:Y', 'J:U:Y:Z', 'K:A:D:Y', 'K:B:D:E',
        'K:B:D:N', 'K:B:D:O', 'K:B:D:R', 'K:B:G:P', 'K:B:G:U', 'K:B:H:P',
        'K:B:I:X', 'K:B:N:P', 'K:B:N:X', 'K:B:O:P', 'K:B:O:Q', 'K:B:O:X',
        'K:B:P:T', 'K:B:P:Y', 'K:B:Q:R', 'K:B:Q:T', 'K:B:Y:Z', 'K:C:D:L',
        'K:C:F:H', 'K:C:G:R', 'K:C:G:X', 'K:C:H:W', 'K:C:I:W', 'K:C:I:X',
        'K:C:J:U', 'K:C:M:V', 'K:C:O:V', 'K:C:O:W', 'K:C:P:Q', 'K:C:R:W',
        'K:C:S:X', 'K:C:U:V', 'K:D:F:O', 'K:D:F:R', 'K:D:G:N', 'K:D:H:P',
        'K:D:J:L', 'K:D:L:V', 'K:D:L:W', 'K:D:L:Y', 'K:D:L:Z', 'K:D:N:Y',
        'K:D:N:Z', 'K:D:O:Z', 'K:D:P:Y', 'K:D:P:Z', 'K:D:R:W', 'K:D:R:Y',
        'K:D:T:U', 'K:D:T:Z', 'K:E:G:X', 'K:E:H:J', 'K:E:J:O', 'K:E:J:R',
        'K:E:J:U', 'K:F:G:O', 'K:F:G:T', 'K:F:L:Z', 'K:F:M:N', 'K:F:M:O',
        'K:F:M:U', 'K:F:N:W', 'K:F:O:P', 'K:F:O:Z', 'K:F:P:U', 'K:F:R:W',
        'K:F:T:W', 'K:F:T:Z', 'K:G:H:X', 'K:G:I:X', 'K:G:M:P', 'K:G:M:Y',
        'K:G:N:Q', 'K:G:O:X', 'K:G:O:Z', 'K:G:P:T', 'K:G:P:U', 'K:G:P:Y',
        'K:G:Q:S', 'K:G:Q:T', 'K:G:R:Z', 'K:G:T:Z', 'K:G:U:X', 'K:G:U:Z',
        'K:H:J:M', 'K:H:J:T', 'K:H:M:V', 'K:H:N:X', 'K:H:P:Q', 'K:H:Q:Y',
        'K:H:R:V', 'K:H:R:W', 'K:H:T:W', 'K:H:U:W', 'K:H:U:Y', 'K:I:J:L',
        'K:I:J:T', 'K:I:M:Q', 'K:I:M:V', 'K:I:Q:S', 'K:I:Q:T', 'K:I:W:Z',
        'K:J:L:N', 'K:J:L:O', 'K:J:L:R', 'K:J:L:U', 'K:J:M:S', 'K:J:M:U',
        'K:J:N:O', 'K:J:N:U', 'K:J:O:U', 'K:J:R:T', 'K:J:R:U', 'K:J:S:U',
        'K:L:M:Y', 'K:L:O:W', 'K:L:S:X', 'K:L:T:X', 'K:L:U:Y', 'K:L:W:Z',
        'K:L:Y:Z', 'K:M:N:Q', 'K:M:N:Z', 'K:M:O:V', 'K:M:P:Y', 'K:M:Q:R',
        'K:M:R:V', 'K:M:T:V', 'K:N:P:Q', 'K:N:Q:Y', 'K:N:R:X', 'K:N:U:X',
        'K:O:P:Q', 'K:O:Q:Y', 'K:O:T:X', 'K:O:W:Z', 'K:P:Q:Y', 'K:P:T:Z',
        'K:R:U:V', 'K:R:U:X', 'K:S:X:Y', 'K:T:U:V', 'K:T:X:Y', 'L:B:D:Y',
        'L:B:F:Y', 'L:B:J:S', 'L:B:K:M', 'L:B:K:P', 'L:B:K:U', 'L:B:N:V',
        'L:C:F:V', 'L:C:M:W', 'L:C:N:W', 'L:C:O:W', 'L:C:U:W', 'L:D:H:W',
        'L:D:J:U', 'L:D:R:W', 'L:E:M:W', 'L:F:H:V', 'L:F:H:Y', 'L:F:H:Z',
        'L:F:I:Y', 'L:F:M:Y', 'L:F:N:Y', 'L:F:O:Y', 'L:F:P:Z', 'L:F:R:Y',
        'L:F:T:Y', 'L:F:U:Y', 'L:G:J:M', 'L:G:J:R', 'L:G:J:U', 'L:G:K:R',
        'L:G:K:T', 'L:G:K:U', 'L:G:K:Y', 'L:G:O:W', 'L:G:Q:V', 'L:G:U:W',
        'L:H:I:W', 'L:H:K:N', 'L:H:K:P', 'L:H:K:U', 'L:H:K:Y', 'L:H:N:W',
        'L:H:O:W', 'L:H:P:X', 'L:I:J:M', 'L:I:J:R', 'L:I:K:P', 'L:I:M:W',
        'L:J:R:U', 'L:K:M:P', 'L:K:O:P', 'L:K:O:Y', 'L:K:P:Y', 'L:K:R:Y',
        'L:K:S:Z', 'L:K:U:Z', 'L:M:N:W', 'L:M:Q:X', 'L:M:R:W', 'L:M:U:W',
        'L:P:Q:X', 'L:R:U:W', 'L:S:X:Z', 'L:T:Y:Z', 'M:B:G:W', 'M:B:H:V',
        'M:B:K:P', 'M:B:K:U', 'M:B:O:W', 'M:D:F:V', 'M:D:K:T', 'M:D:K:Z',
        'M:F:I:P', 'M:F:L:P', 'M:F:L:X', 'M:F:O:P', 'M:F:U:V', 'M:G:H:K',
        'M:G:H:V', 'M:G:K:P', 'M:G:K:X', 'M:G:O:W', 'M:H:J:U', 'M:I:K:P',
        'M:I:K:W', 'M:J:O:P', 'M:J:P:R', 'M:J:T:X', 'M:J:U:Z', 'M:J:X:Y',
        'M:K:L:P', 'M:K:L:Y', 'M:K:O:X', 'M:K:O:Y', 'M:K:P:S', 'M:K:P:U',
        'M:K:R:X', 'M:K:U:Y', 'M:K:Y:Z', 'M:N:W:Z', 'M:P:Q:X', 'M:P:R:V',
        'M:Q:Y:Z', 'M:T:W:Z', 'M:X:Y:Z', 'N:B:H:P', 'N:B:I:K', 'N:B:I:X',
        'N:B:K:R', 'N:B:K:U', 'N:B:L:V', 'N:B:O:Q', 'N:B:O:W', 'N:B:P:U',
        'N:B:Q:U', 'N:B:R:V', 'N:B:R:W', 'N:B:S:W', 'N:C:D:K', 'N:D:E:K',
        'N:D:I:K', 'N:D:I:W', 'N:D:K:O', 'N:D:K:R', 'N:D:K:S', 'N:D:K:T',
        'N:D:K:U', 'N:D:K:W', 'N:D:P:Y', 'N:D:Q:U', 'N:D:R:W', 'N:D:T:X',
        'N:D:U:Y', 'N:E:F:H', 'N:E:F:K', 'N:E:G:K', 'N:F:G:L', 'N:F:I:K',
        'N:F:K:L', 'N:F:K:R', 'N:F:O:P', 'N:F:P:R', 'N:F:P:T', 'N:F:T:V',
        'N:F:U:V', 'N:G:K:L', 'N:G:M:W', 'N:G:M:Z', 'N:G:P:V', 'N:G:P:Y',
        'N:G:P:Z', 'N:G:Q:U', 'N:G:S:W', 'N:G:W:Z', 'N:H:K:T', 'N:H:K:U',
        'N:H:Q:U', 'N:H:U:V', 'N:H:U:Z', 'N:H:V:Y', 'N:I:K:Y', 'N:K:W:Z',
        'N:L:V:X', 'N:M:W:Z', 'N:P:Q:V', 'N:P:Q:X', 'N:P:S:X', 'N:P:T:Z',
        'N:P:V:X', 'N:P:V:Y', 'N:R:V:Y', 'N:T:W:Z', 'N:T:X:Y', 'O:B:D:W',
        'O:B:E:W', 'O:B:L:W', 'O:B:N:W', 'O:C:F:H', 'O:C:G:V', 'O:C:K:R',
        'O:C:K:V', 'O:D:F:M', 'O:D:F:P', 'O:D:F:Y', 'O:D:N:W', 'O:D:V:Y',
        'O:E:U:W', 'O:F:H:L', 'O:F:H:P', 'O:F:I:Y', 'O:F:L:X', 'O:F:L:Y',
        'O:F:R:Y', 'O:F:T:Y', 'O:F:U:V', 'O:F:U:Y', 'O:G:H:K', 'O:G:J:R',
        'O:G:K:L', 'O:G:K:P', 'O:G:K:Q', 'O:G:K:V', 'O:G:K:Y', 'O:G:Q:Z',
        'O:G:Y:Z', 'O:H:I:K', 'O:H:K:Q', 'O:H:N:V', 'O:I:J:U', 'O:I:K:Y',
        'O:I:U:W', 'O:J:M:T', 'O:J:M:U', 'O:J:N:U', 'O:J:S:Z', 'O:J:T:Z',
        'O:J:U:Z', 'O:K:L:M', 'O:K:L:R', 'O:K:L:T', 'O:K:L:V', 'O:K:L:Z',
        'O:K:M:V', 'O:K:P:Q', 'O:K:P:U', 'O:K:P:Y', 'O:K:Q:T', 'O:K:Q:Y',
        'O:K:R:Y', 'O:L:M:W', 'O:M:U:Z', 'O:N:V:Y', 'O:P:X:Z', 'O:P:Y:Z',
        'O:Q:T:Z', 'O:R:U:W', 'O:S:W:Y', 'O:U:Y:Z', 'O:V:X:Y', 'O:V:Y:Z',
        'P:B:I:W', 'P:B:J:T', 'P:B:K:L', 'P:B:K:R', 'P:B:O:W', 'P:B:Q:Z',
        'P:B:T:W', 'P:C:F:K', 'P:C:H:W', 'P:D:K:T', 'P:D:K:U', 'P:D:K:Y',
        'P:E:J:K', 'P:F:G:K', 'P:F:K:O', 'P:F:K:R', 'P:F:K:U', 'P:F:K:V',
        'P:F:X:Y', 'P:G:H:J', 'P:G:J:L', 'P:G:J:U', 'P:H:J:O', 'P:H:J:T',
        'P:H:J:V', 'P:H:K:Q', 'P:H:N:W', 'P:H:R:W', 'P:H:X:Z', 'P:I:J:X',
        'P:I:K:X', 'P:I:M:W', 'P:J:K:N', 'P:J:K:R', 'P:J:K:V', 'P:J:L:V',
        'P:J:N:Y', 'P:J:O:X', 'P:J:O:Y', 'P:J:R:Y', 'P:J:T:V', 'P:J:T:X',
        'P:J:U:Y', 'P:K:O:X', 'P:K:Q:R', 'P:K:Q:Y', 'P:K:T:Z', 'P:L:M:W',
        'P:M:R:W', 'Q:A:F:U', 'Q:A:J:U', 'Q:A:K:T', 'Q:B:F:T', 'Q:B:L:U',
        'Q:B:L:V', 'Q:B:O:Z', 'Q:B:R:V', 'Q:B:T:V', 'Q:B:T:Z', 'Q:C:F:I',
        'Q:C:K:R', 'Q:C:L:Y', 'Q:C:M:U', 'Q:C:R:X', 'Q:C:T:X', 'Q:C:T:Z',
        'Q:D:F:R', 'Q:D:G:J', 'Q:D:G:R', 'Q:D:H:L', 'Q:D:H:P', 'Q:D:H:R',
        'Q:D:H:T', 'Q:D:H:U', 'Q:D:I:J', 'Q:D:J:U', 'Q:D:L:Y', 'Q:E:G:L',
        'Q:E:H:L', 'Q:E:H:P', 'Q:E:J:X', 'Q:E:O:X', 'Q:F:I:Z', 'Q:F:M:R',
        'Q:F:M:Z', 'Q:F:O:Z', 'Q:F:U:Z', 'Q:G:J:R', 'Q:G:N:Y', 'Q:G:R:X',
        'Q:G:S:X', 'Q:G:S:Y', 'Q:H:I:P', 'Q:H:L:R', 'Q:H:M:R', 'Q:H:M:T',
        'Q:H:M:Z', 'Q:H:N:P', 'Q:H:N:Z', 'Q:H:O:Z', 'Q:H:P:R', 'Q:H:P:U',
        'Q:H:S:Z', 'Q:H:T:Z', 'Q:I:K:R', 'Q:I:O:X', 'Q:J:L:S', 'Q:J:M:S',
        'Q:J:M:X', 'Q:J:N:O', 'Q:J:N:X', 'Q:J:O:R', 'Q:J:O:X', 'Q:J:R:U',
        'Q:J:R:X', 'Q:K:O:R', 'Q:K:R:T', 'Q:L:P:X', 'Q:L:R:Y', 'Q:L:S:W',
        'Q:M:N:V', 'Q:M:S:X', 'Q:N:O:X', 'Q:N:P:Z', 'Q:N:T:Y', 'Q:O:R:X',
        'Q:P:T:X', 'Q:P:T:Z', 'Q:S:T:W', 'Q:S:U:W', 'Q:S:W:Y', 'Q:S:X:Y',
        'Q:S:Y:Z', 'Q:T:U:Y', 'R:E:H:J', 'R:E:K:V', 'R:E:W:Y', 'R:F:J:U',
        'R:F:K:W', 'R:F:U:W', 'R:G:H:W', 'R:G:Q:Y', 'R:H:J:U', 'R:H:K:W',
        'R:K:L:V', 'R:K:P:U', 'R:L:W:Y', 'R:M:U:W', 'R:M:W:Y', 'R:N:W:Y',
        'R:O:W:Y', 'R:P:X:Y', 'R:U:W:Y', 'R:U:W:Z', 'S:B:R:W', 'S:C:U:W',
        'S:D:H:W', 'S:D:I:J', 'S:D:J:L', 'S:D:J:T', 'S:D:K:Y', 'S:D:W:Y',
        'S:F:G:J', 'S:F:H:K', 'S:F:H:W', 'S:F:J:L', 'S:F:J:O', 'S:F:J:T',
        'S:F:K:W', 'S:F:L:W', 'S:F:O:W', 'S:F:R:W', 'S:F:X:Y', 'S:G:J:L',
        'S:G:K:N', 'S:H:W:Y', 'S:I:W:Y', 'S:J:K:L', 'S:J:K:O', 'S:J:K:T',
        'S:J:L:P', 'S:J:L:Q', 'S:J:M:V', 'S:J:Q:R', 'S:J:T:V', 'S:J:U:V',
        'S:J:V:Z', 'S:K:L:Q', 'S:K:Q:R', 'S:K:Q:T', 'S:K:R:W', 'S:K:U:V',
        'S:L:U:W', 'S:O:W:Y', 'S:P:V:X', 'S:P:V:Y', 'S:P:W:Y', 'S:U:W:Z',
        'S:W:Y:Z', 'T:B:K:L', 'T:B:K:O', 'T:B:K:U', 'T:B:P:X', 'T:B:X:Y',
        'T:C:F:Q', 'T:C:J:P', 'T:C:V:X', 'T:D:J:R', 'T:D:J:U', 'T:D:K:N',
        'T:D:K:W', 'T:D:K:Y', 'T:D:N:W', 'T:D:O:W', 'T:E:G:W', 'T:E:J:P',
        'T:F:J:S', 'T:F:N:P', 'T:F:P:Q', 'T:G:I:J', 'T:G:J:O', 'T:G:J:P',
        'T:G:K:M', 'T:G:K:V', 'T:G:U:W', 'T:G:V:X', 'T:I:P:W', 'T:J:K:U',
        'T:J:M:N', 'T:J:M:X', 'T:J:N:X', 'T:J:O:P', 'T:J:O:X', 'T:J:O:Z',
        'T:J:P:R', 'T:J:S:Z', 'T:K:L:Q', 'T:K:N:Q', 'T:K:O:V', 'T:K:P:U',
        'T:K:Q:R', 'T:L:P:V', 'T:L:X:Y', 'T:M:P:V', 'T:N:P:V', 'T:N:P:W',
        'T:N:W:X', 'T:O:P:W', 'T:O:U:W', 'T:O:V:X', 'T:O:W:X', 'T:P:Q:X',
        'T:P:R:V', 'T:P:R:W', 'T:P:U:V', 'T:P:U:W', 'T:Q:X:Y', 'T:R:W:Y',
        'T:U:V:X', 'T:W:X:Y', 'U:A:K:L', 'U:A:N:W', 'U:A:P:Q', 'U:B:C:M',
        'U:B:C:O', 'U:B:D:I', 'U:B:D:T', 'U:B:F:M', 'U:B:F:O', 'U:B:G:L',
        'U:B:G:R', 'U:B:L:X', 'U:B:L:Y', 'U:B:N:X', 'U:B:O:X', 'U:B:Q:T',
        'U:B:R:X', 'U:B:R:Z', 'U:B:T:X', 'U:C:G:T', 'U:C:G:Y', 'U:C:K:R',
        'U:C:K:Z', 'U:C:N:Y', 'U:C:N:Z', 'U:C:P:Y', 'U:D:F:O', 'U:D:F:T',
        'U:D:G:M', 'U:D:H:L', 'U:D:H:P', 'U:D:H:T', 'U:D:H:X', 'U:D:K:M',
        'U:D:K:T', 'U:D:K:Z', 'U:D:L:X', 'U:D:L:Y', 'U:D:N:Z', 'U:D:O:Z',
        'U:D:P:Z', 'U:D:Q:T', 'U:D:Q:Y', 'U:D:S:W', 'U:D:T:V', 'U:D:T:X',
        'U:F:G:O', 'U:F:G:R', 'U:F:H:Z', 'U:F:M:Q', 'U:F:M:X', 'U:F:O:Q',
        'U:F:O:X', 'U:F:Q:R', 'U:F:Q:T', 'U:F:T:Z', 'U:G:H:L', 'U:G:H:Q',
        'U:G:H:R', 'U:G:H:T', 'U:G:M:P', 'U:G:P:Q', 'U:G:P:T', 'U:G:Q:T',
        'U:G:S:X', 'U:H:L:Z', 'U:H:M:X', 'U:H:N:X', 'U:H:O:P', 'U:H:O:X',
        'U:H:P:Q', 'U:H:P:R', 'U:H:Q:R', 'U:H:R:X', 'U:H:T:X', 'U:H:T:Z',
        'U:I:K:L', 'U:I:P:Y', 'U:I:V:X', 'U:K:L:M', 'U:K:L:N', 'U:K:L:O',
        'U:K:L:R', 'U:K:L:T', 'U:K:L:Z', 'U:K:M:O', 'U:K:O:Z', 'U:K:P:S',
        'U:K:R:Z', 'U:L:P:Y', 'U:L:R:Y', 'U:M:T:Z', 'U:N:Q:Y', 'U:N:R:W',
        'U:N:T:W', 'U:N:V:X', 'U:O:P:X', 'U:O:P:Y', 'U:O:P:Z', 'U:O:Q:V',
        'U:O:Q:Y', 'U:O:S:W', 'U:P:R:Y', 'U:P:S:W', 'U:P:T:X', 'U:P:T:Z',
        'U:Q:R:Y', 'U:Q:T:Y', 'U:R:V:X', 'U:S:V:X', 'V:A:K:T', 'V:B:G:P',
        'V:B:H:L', 'V:B:M:P', 'V:B:N:Q', 'V:B:O:P', 'V:B:O:X', 'V:B:P:U',
        'V:B:R:Y', 'V:B:S:X', 'V:C:I:K', 'V:C:J:S', 'V:C:J:T', 'V:C:K:N',
        'V:C:K:R', 'V:C:K:U', 'V:D:F:Q', 'V:D:F:R', 'V:D:F:U', 'V:D:J:N',
        'V:D:J:P', 'V:D:J:R', 'V:D:J:S', 'V:D:J:T', 'V:D:T:X', 'V:D:U:X',
        'V:E:K:N', 'V:E:K:T', 'V:F:I:Y', 'V:F:O:P', 'V:F:O:Q', 'V:F:O:Y',
        'V:F:O:Z', 'V:F:P:S', 'V:F:P:T', 'V:F:P:U', 'V:F:Q:R', 'V:F:U:Z',
        'V:G:K:L', 'V:G:K:O', 'V:G:K:P', 'V:G:M:Z', 'V:G:P:X', 'V:H:U:Z',
        'V:I:K:O', 'V:I:K:P', 'V:I:K:R', 'V:I:K:T', 'V:J:L:P', 'V:J:N:P',
        'V:J:P:R', 'V:J:P:S', 'V:J:P:T', 'V:J:P:U', 'V:J:S:Z', 'V:K:L:U',
        'V:K:N:O', 'V:K:N:T', 'V:K:P:U', 'V:K:R:T', 'V:K:R:U', 'V:K:S:T',
        'V:K:T:U', 'V:L:Q:X', 'V:O:P:Y', 'V:O:Q:X', 'V:P:Q:Z', 'V:P:R:Y',
        'V:P:S:Y', 'V:P:T:Y', 'V:Q:T:Y', 'W:A:H:X', 'W:A:K:Z', 'W:A:Q:U',
        'W:B:D:K', 'W:B:D:L', 'W:B:F:I', 'W:B:F:L', 'W:B:F:N', 'W:B:F:S',
        'W:B:F:T', 'W:B:G:H', 'W:B:H:L', 'W:B:K:O', 'W:B:K:T', 'W:B:K:U',
        'W:B:M:Z', 'W:B:T:Z', 'W:C:D:Q', 'W:C:H:P', 'W:C:H:Q', 'W:C:H:V',
        'W:C:K:U', 'W:C:M:Q', 'W:C:N:P', 'W:C:N:V', 'W:C:N:Z', 'W:C:O:Z',
        'W:C:P:R', 'W:C:P:U', 'W:C:S:V', 'W:C:T:V', 'W:C:T:Z', 'W:D:F:T',
        'W:D:F:U', 'W:D:K:L', 'W:D:K:P', 'W:D:K:R', 'W:D:K:U', 'W:D:L:P',
        'W:D:L:Q', 'W:D:L:Y', 'W:D:N:Y', 'W:D:O:P', 'W:D:O:Y', 'W:D:P:R',
        'W:D:P:T', 'W:D:P:U', 'W:D:Q:R', 'W:D:Q:S', 'W:D:R:Y', 'W:D:T:U',
        'W:D:T:Y', 'W:E:G:Z', 'W:E:K:P', 'W:F:G:L', 'W:F:G:R', 'W:F:G:S',
        'W:F:G:T', 'W:F:H:K', 'W:F:H:O', 'W:F:H:T', 'W:F:I:M', 'W:F:K:L',
        'W:F:M:R', 'W:F:N:U', 'W:F:S:Z', 'W:G:H:P', 'W:G:H:V', 'W:G:I:Z',
        'W:G:L:V', 'W:G:N:Q', 'W:G:O:Q', 'W:G:O:V', 'W:G:P:R', 'W:G:Q:R',
        'W:G:Q:S', 'W:G:R:V', 'W:G:T:Z', 'W:G:U:V', 'W:H:L:V', 'W:H:M:P',
        'W:H:M:X', 'W:H:N:Q', 'W:H:O:Y', 'W:H:O:Z', 'W:H:P:U', 'W:H:R:Y',
        'W:H:U:V', 'W:I:K:P', 'W:I:K:U', 'W:I:P:U', 'W:I:U:Z', 'W:K:L:P',
        'W:K:L:U', 'W:K:L:Y', 'W:K:M:P', 'W:K:N:P', 'W:K:O:P', 'W:K:O:V',
        'W:K:P:T', 'W:K:P:U', 'W:K:R:U', 'W:K:R:Y', 'W:K:R:Z', 'W:K:S:Z',
        'W:K:T:U', 'W:K:T:V', 'W:L:M:P', 'W:L:M:Q', 'W:L:N:P', 'W:L:N:Q',
        'W:L:O:Y', 'W:L:P:U', 'W:L:Q:S', 'W:M:O:P', 'W:M:O:Q', 'W:M:O:V',
        'W:M:O:Y', 'W:M:O:Z', 'W:M:Q:R', 'W:M:Q:S', 'W:M:Q:T', 'W:M:R:V',
        'W:M:R:Y', 'W:M:T:Z', 'W:M:U:V', 'W:N:P:U', 'W:N:Q:T', 'W:N:T:Y',
        'W:O:T:Y', 'W:P:S:Y', 'W:P:S:Z', 'W:Q:R:T', 'W:Q:S:U', 'W:R:T:Y',
        'X:A:B:R', 'X:A:D:I', 'X:A:D:M', 'X:A:D:R', 'X:A:G:Y', 'X:A:H:U',
        'X:A:M:U', 'X:A:P:U', 'X:B:E:M', 'X:B:E:Y', 'X:B:H:U', 'X:B:I:M',
        'X:B:I:P', 'X:B:I:Y', 'X:B:L:R', 'X:B:M:R', 'X:B:M:S', 'X:B:P:Q',
        'X:B:P:S', 'X:B:P:U', 'X:B:Q:T', 'X:B:R:T', 'X:B:R:Y', 'X:B:S:U',
        'X:B:S:Y', 'X:B:T:U', 'X:C:D:M', 'X:C:D:T', 'X:C:D:U', 'X:C:H:T',
        'X:C:M:U', 'X:C:M:Y', 'X:C:N:P', 'X:C:N:U', 'X:C:U:Y', 'X:D:H:R',
        'X:D:H:T', 'X:D:H:U', 'X:D:I:T', 'X:D:L:Q', 'X:D:L:U', 'X:D:M:T',
        'X:D:M:U', 'X:D:M:Y', 'X:D:N:R', 'X:D:P:Y', 'X:D:Q:Y', 'X:D:R:T',
        'X:D:S:T', 'X:D:S:Y', 'X:D:U:Y', 'X:F:N:R', 'X:F:N:S', 'X:F:S:U',
        'X:F:S:Y', 'X:G:H:Y', 'X:G:I:T', 'X:G:L:P', 'X:G:L:Q', 'X:G:M:Y',
        'X:G:P:R', 'X:G:P:U', 'X:G:P:Y', 'X:G:Q:R', 'X:G:Q:T', 'X:G:Q:Y',
        'X:G:R:T', 'X:G:R:Y', 'X:G:S:V', 'X:G:T:U', 'X:G:T:Y', 'X:G:U:Y',
        'X:H:L:U', 'X:H:P:U', 'X:H:R:U', 'X:H:T:U', 'X:H:U:Y', 'X:I:U:Y',
        'X:L:M:Q', 'X:L:M:U', 'X:L:N:U', 'X:L:N:V', 'X:L:P:Q', 'X:L:P:U',
        'X:M:N:U', 'X:M:P:Q', 'X:M:P:U', 'X:M:Q:T', 'X:M:T:U', 'X:O:Q:R',
        'X:P:T:U', 'X:P:U:Y', 'X:Q:R:Y', 'X:R:S:V', 'X:S:U:V', 'X:S:V:Y',
        'Y:A:F:N', 'Y:A:F:T', 'Y:A:J:L', 'Y:A:J:O', 'Y:A:J:S', 'Y:A:J:T',
        'Y:A:J:U', 'Y:A:R:W', 'Y:A:T:W', 'Y:B:C:H', 'Y:B:C:T', 'Y:B:G:H',
        'Y:B:G:N', 'Y:B:G:O', 'Y:B:G:R', 'Y:B:G:U', 'Y:B:H:O', 'Y:B:H:R',
        'Y:B:H:U', 'Y:B:L:Q', 'Y:B:Q:R', 'Y:B:Q:T', 'Y:C:D:T', 'Y:C:E:F',
        'Y:C:F:I', 'Y:C:F:N', 'Y:C:F:R', 'Y:C:F:T', 'Y:C:G:N', 'Y:C:G:U',
        'Y:C:K:M', 'Y:C:K:V', 'Y:C:L:Q', 'Y:C:M:P', 'Y:C:P:R', 'Y:C:R:T',
        'Y:C:R:W', 'Y:C:T:V', 'Y:D:H:R', 'Y:D:H:T', 'Y:E:M:W', 'Y:E:U:V',
        'Y:F:I:O', 'Y:F:I:R', 'Y:F:I:T', 'Y:F:L:N', 'Y:F:L:T', 'Y:F:S:W',
        'Y:G:H:M', 'Y:G:K:S', 'Y:G:L:U', 'Y:G:L:V', 'Y:G:M:O', 'Y:G:M:Q',
        'Y:G:M:V', 'Y:G:N:Q', 'Y:G:N:R', 'Y:G:N:U', 'Y:G:N:V', 'Y:G:O:V',
        'Y:G:Q:T', 'Y:G:R:T', 'Y:G:U:V', 'Y:H:K:M', 'Y:H:M:R', 'Y:H:M:U',
        'Y:H:T:V', 'Y:I:J:S', 'Y:I:J:U', 'Y:I:L:P', 'Y:I:L:Q', 'Y:I:N:Z',
        'Y:I:S:W', 'Y:I:T:V', 'Y:J:K:S', 'Y:K:L:N', 'Y:K:M:R', 'Y:K:M:T',
        'Y:K:M:U', 'Y:K:O:Z', 'Y:K:P:U', 'Y:K:S:W', 'Y:L:M:V', 'Y:L:N:Q',
        'Y:L:N:W', 'Y:L:O:W', 'Y:L:P:T', 'Y:L:Q:R', 'Y:L:Q:T', 'Y:L:Q:U',
        'Y:L:S:Z', 'Y:L:U:V', 'Y:M:N:Q', 'Y:M:P:R', 'Y:M:P:U', 'Y:M:S:W',
        'Y:N:Q:S', 'Y:N:Q:T', 'Y:N:R:Z', 'Y:N:U:V', 'Y:P:T:U', 'Y:T:U:V',
        'Z:A:F:M', 'Z:B:C:F', 'Z:B:C:N', 'Z:B:C:W', 'Z:B:D:R', 'Z:B:D:U',
        'Z:B:E:J', 'Z:B:F:U', 'Z:B:H:I', 'Z:B:H:O', 'Z:B:H:P', 'Z:B:H:U',
        'Z:B:I:P', 'Z:B:J:N', 'Z:B:J:U', 'Z:B:L:Q', 'Z:B:N:W', 'Z:B:P:W',
        'Z:B:Q:R', 'Z:B:T:W', 'Z:C:F:M', 'Z:C:F:O', 'Z:C:F:T', 'Z:C:F:U',
        'Z:C:H:W', 'Z:C:K:R', 'Z:C:L:Q', 'Z:C:N:V', 'Z:C:N:W', 'Z:C:O:V',
        'Z:C:R:V', 'Z:C:U:V', 'Z:C:U:W', 'Z:D:F:N', 'Z:D:H:N', 'Z:D:H:R',
        'Z:D:J:N', 'Z:D:J:U', 'Z:D:K:N', 'Z:D:K:Y', 'Z:D:L:Y', 'Z:D:M:W',
        'Z:D:N:V', 'Z:D:O:Q', 'Z:D:O:V', 'Z:D:P:U', 'Z:D:Q:U', 'Z:D:R:W',
        'Z:D:U:V', 'Z:E:H:W', 'Z:E:J:M', 'Z:E:J:N', 'Z:F:G:O', 'Z:F:G:R',
        'Z:F:I:U', 'Z:F:L:N', 'Z:F:L:O', 'Z:F:M:T', 'Z:F:M:U', 'Z:F:N:O',
        'Z:F:T:U', 'Z:G:O:V', 'Z:G:P:Q', 'Z:G:R:V', 'Z:G:R:W', 'Z:G:T:V',
        'Z:G:T:X', 'Z:G:U:V', 'Z:G:V:Y', 'Z:H:N:W', 'Z:H:U:W', 'Z:I:J:M',
        'Z:I:J:N', 'Z:I:J:P', 'Z:I:J:T', 'Z:I:K:V', 'Z:I:K:Y', 'Z:I:L:V',
        'Z:I:M:V', 'Z:I:M:X', 'Z:I:R:X', 'Z:I:U:W', 'Z:I:V:Y', 'Z:J:M:O',
        'Z:J:N:P', 'Z:J:N:T', 'Z:J:P:U', 'Z:J:R:S', 'Z:K:L:P', 'Z:K:M:O',
        'Z:K:N:V', 'Z:K:N:Y', 'Z:K:P:T', 'Z:K:P:V', 'Z:K:S:W', 'Z:K:T:V',
        'Z:K:T:Y', 'Z:L:T:W', 'Z:M:N:V', 'Z:M:N:X', 'Z:M:O:X', 'Z:M:R:W',
        'Z:M:T:X', 'Z:N:P:V', 'Z:N:U:V', 'Z:N:V:Y', 'Z:P:R:W', 'Z:R:U:V',
        'Z:T:V:Y',
    ];

    /**
     * Doublons de contenu CROISES avec une famille EXTERIEURE (D-045, meme discipline D-041) --
     * voir docs/DECISIONS.md D-045.
     *
     * @var list<string>
     */
    private const EXTERNAL_DUPLICATE_KEYS = [];

    public function __construct(
        private readonly Connection $connection,
    ) {
    }

    public function build(string $prefix, string $letter1, string $letter2): PrefixAvecThreeLettersLinks
    {
        $pair = [$letter1, $letter2];
        sort($pair, SORT_STRING);
        [$x, $y] = $pair;

        $statement = $this->connection->pdo()->prepare(
            "SELECT list_key, count FROM list_counts WHERE list_type = 'start_with_triple'"
            . ' AND (list_key LIKE ? OR list_key LIKE ? OR list_key LIKE ?)'
        );
        $statement->execute([
            $prefix . ':' . $x . ':' . $y . ':%',
            $prefix . ':' . $x . ':%:' . $y,
            $prefix . ':%:' . $x . ':' . $y,
        ]);

        $links = [];

        foreach ($statement as $row) {
            $key = (string) $row['list_key'];

            if (
                in_array($key, self::DUPLICATE_PARENT_KEYS, true)
                || in_array($key, self::SIBLING_DUPLICATE_KEYS, true)
                || in_array($key, self::EXTERNAL_DUPLICATE_KEYS, true)
            ) {
                continue;
            }

            $parts = explode(':', $key, 4);
            $triple = [$parts[1], $parts[2], $parts[3]];

            $partner = null;
            foreach ($triple as $candidate) {
                if ($candidate !== $x && $candidate !== $y) {
                    $partner = $candidate;
                    break;
                }
            }

            if ($partner === null) {
                continue;
            }

            $count = (int) $row['count'];
            $path = 'commencant/' . strtolower($prefix) . '/avec/' . strtolower($x) . '/' . strtolower($y) . '/' . strtolower($partner);
            $url = WordListFilters::fromPath($path)?->canonicalUrl();

            if ($url !== null) {
                $links[] = ['letter' => $partner, 'url' => $url, 'count' => $count];
            }
        }

        usort($links, static fn (array $a, array $b): int => $a['letter'] <=> $b['letter']);

        return new PrefixAvecThreeLettersLinks(links: $links, queryCount: 1);
    }
}
