<?php

declare(strict_types=1);

namespace App\Search;

use App\Database\Connection;

/**
 * Construit App\Search\SuffixAvecThreeLettersLinks depuis list_counts (list_type
 * 'end_with_triple'), symetrique de App\Search\PrefixAvecThreeLettersLinksBuilder cote suffixe
 * (Family::WORD_LIST_TERMINANT_WITH_THREE_LETTERS, D-045) -- une seule requete triviale.
 *
 * list_key est toujours "{suffixe}:{lettre1}:{lettre2}:{lettre3}" avec
 * lettre1 < lettre2 < lettre3 ALPHABETIQUEMENT. Meme OR a trois motifs que
 * App\Search\AvecThreeLettersLinksBuilder.
 */
final class SuffixAvecThreeLettersLinksBuilder
{
    /**
     * Doublons de contenu avec l'une des trois pages PARENTES palier 2 (D-045). Calculee
     * PROGRAMMATIQUEMENT (comparaison directe list_counts, chargement en memoire par suffixe),
     * 3 567 cles trouvees sur les 32 888 candidats reels -- voir docs/DECISIONS.md D-045.
     *
     * @var list<string>
     */
    private const DUPLICATE_PARENT_KEYS = [
        'A:B:J:W', 'A:C:Q:U', 'A:E:V:W', 'A:F:Q:U', 'A:G:Q:U', 'A:H:Q:U',
        'A:I:J:W', 'A:I:V:W', 'A:J:O:W', 'A:J:Q:U', 'A:K:O:Q', 'A:K:Q:U',
        'A:M:Q:U', 'A:N:Q:U', 'A:N:V:W', 'A:O:Q:U', 'A:P:Q:U', 'A:Q:U:V',
        'A:Q:U:X', 'A:Q:U:Z', 'A:R:V:W', 'A:T:V:W', 'B:A:C:F', 'B:A:C:G',
        'B:A:C:K', 'B:A:C:Y', 'B:A:D:H', 'B:A:D:J', 'B:A:D:K', 'B:A:D:S',
        'B:A:D:W', 'B:A:E:G', 'B:A:E:W', 'B:A:E:Y', 'B:A:F:H', 'B:A:F:L',
        'B:A:F:M', 'B:A:F:N', 'B:A:F:S', 'B:A:F:U', 'B:A:G:L', 'B:A:G:M',
        'B:A:G:O', 'B:A:G:U', 'B:A:H:J', 'B:A:H:K', 'B:A:H:O', 'B:A:H:P',
        'B:A:H:S', 'B:A:H:Y', 'B:A:I:J', 'B:A:I:M', 'B:A:I:Q', 'B:A:I:Y',
        'B:A:J:R', 'B:A:K:R', 'B:A:K:W', 'B:A:L:Y', 'B:A:M:Y', 'B:A:N:P',
        'B:A:N:Q', 'B:A:O:Y', 'B:A:P:Y', 'B:A:R:W', 'B:A:R:Y', 'B:A:R:Z',
        'B:A:T:Y', 'B:A:U:Y', 'B:C:D:I', 'B:C:D:V', 'B:C:E:K', 'B:C:E:V',
        'B:C:F:L', 'B:C:F:N', 'B:C:F:U', 'B:C:G:L', 'B:C:G:M', 'B:C:G:N',
        'B:C:G:O', 'B:C:G:T', 'B:C:G:U', 'B:C:H:K', 'B:C:H:N', 'B:C:I:K',
        'B:C:I:V', 'B:C:I:Y', 'B:C:J:M', 'B:C:J:O', 'B:C:L:N', 'B:C:L:T',
        'B:C:L:V', 'B:C:L:Y', 'B:C:M:Y', 'B:C:N:R', 'B:C:O:V', 'B:C:O:Y',
        'B:C:R:Y', 'B:C:T:U', 'B:C:U:V', 'B:C:U:Y', 'B:D:E:G', 'B:D:E:K',
        'B:D:E:S', 'B:D:E:V', 'B:D:E:W', 'B:D:G:R', 'B:D:H:I', 'B:D:H:J',
        'B:D:I:L', 'B:D:I:P', 'B:D:I:V', 'B:D:J:R', 'B:D:K:R', 'B:D:K:W',
        'B:D:L:P', 'B:D:L:V', 'B:D:M:O', 'B:D:O:V', 'B:D:R:S', 'B:D:R:W',
        'B:D:U:V', 'B:E:G:M', 'B:E:G:O', 'B:E:G:R', 'B:E:H:K', 'B:E:H:P',
        'B:E:H:Y', 'B:E:I:V', 'B:E:K:N', 'B:E:K:R', 'B:E:K:W', 'B:E:L:V',
        'B:E:L:Y', 'B:E:M:Y', 'B:E:M:Z', 'B:E:N:R', 'B:E:O:P', 'B:E:O:V',
        'B:E:O:Y', 'B:E:P:R', 'B:E:P:T', 'B:E:P:Y', 'B:E:R:T', 'B:E:R:W',
        'B:E:R:Y', 'B:E:T:Y', 'B:E:U:V', 'B:F:H:L', 'B:F:H:M', 'B:F:H:O',
        'B:F:H:S', 'B:F:L:M', 'B:F:L:N', 'B:F:L:S', 'B:F:L:U', 'B:F:M:O',
        'B:F:M:S', 'B:F:N:U', 'B:F:O:S', 'B:G:H:N', 'B:G:H:T', 'B:G:I:N',
        'B:G:I:T', 'B:G:I:U', 'B:G:L:M', 'B:G:L:N', 'B:G:L:O', 'B:G:L:T',
        'B:G:L:U', 'B:G:M:O', 'B:G:M:U', 'B:G:N:T', 'B:G:N:U', 'B:G:O:U',
        'B:G:T:U', 'B:H:I:J', 'B:H:I:K', 'B:H:I:N', 'B:H:L:N', 'B:H:L:O',
        'B:H:L:P', 'B:H:L:T', 'B:H:L:Y', 'B:H:M:O', 'B:H:M:P', 'B:H:M:R',
        'B:H:M:Y', 'B:H:N:T', 'B:H:N:U', 'B:H:O:P', 'B:H:O:Y', 'B:H:P:R',
        'B:H:P:T', 'B:H:P:Y', 'B:H:R:Y', 'B:H:T:Y', 'B:I:K:S', 'B:I:L:V',
        'B:I:L:Y', 'B:I:M:R', 'B:I:M:Y', 'B:I:N:P', 'B:I:N:Q', 'B:I:N:R',
        'B:I:N:T', 'B:I:N:W', 'B:I:O:V', 'B:I:O:Y', 'B:I:R:Y', 'B:I:S:W',
        'B:I:T:W', 'B:I:U:V', 'B:I:U:W', 'B:I:U:Y', 'B:J:M:O', 'B:K:M:O',
        'B:K:M:T', 'B:K:M:U', 'B:K:N:O', 'B:K:O:S', 'B:K:O:T', 'B:K:O:U',
        'B:K:R:W', 'B:K:T:U', 'B:L:M:P', 'B:L:M:S', 'B:L:M:Y', 'B:L:N:R',
        'B:L:N:U', 'B:L:O:V', 'B:L:O:Y', 'B:L:P:Y', 'B:L:R:Y', 'B:L:T:Y',
        'B:L:U:V', 'B:L:U:Y', 'B:M:N:O', 'B:M:O:P', 'B:M:O:S', 'B:M:O:T',
        'B:M:O:Y', 'B:M:P:Y', 'B:M:R:Y', 'B:M:T:Y', 'B:M:U:Y', 'B:N:P:T',
        'B:N:P:U', 'B:N:R:T', 'B:N:R:U', 'B:N:S:W', 'B:N:T:U', 'B:N:T:W',
        'B:N:U:W', 'B:O:P:R', 'B:O:P:S', 'B:O:P:Y', 'B:O:R:Y', 'B:O:T:Y',
        'B:O:U:V', 'B:O:U:Y', 'B:O:U:Z', 'B:P:R:S', 'B:P:R:Y', 'B:P:S:U',
        'B:P:T:Y', 'B:R:T:Y', 'B:R:U:Y', 'B:S:T:W', 'B:S:U:W', 'B:T:U:W',
        'C:A:B:K', 'C:A:B:Q', 'C:A:B:V', 'C:A:B:X', 'C:A:B:Y', 'C:A:B:Z',
        'C:A:D:G', 'C:A:D:H', 'C:A:D:Q', 'C:A:D:V', 'C:A:D:X', 'C:A:D:Z',
        'C:A:E:J', 'C:A:E:K', 'C:A:E:Q', 'C:A:E:X', 'C:A:F:J', 'C:A:F:K',
        'C:A:G:I', 'C:A:G:L', 'C:A:G:M', 'C:A:G:P', 'C:A:G:T', 'C:A:G:X',
        'C:A:G:Y', 'C:A:G:Z', 'C:A:H:M', 'C:A:H:S', 'C:A:H:V', 'C:A:I:J',
        'C:A:I:Q', 'C:A:I:X', 'C:A:J:K', 'C:A:J:L', 'C:A:J:M', 'C:A:J:R',
        'C:A:J:T', 'C:A:K:N', 'C:A:K:P', 'C:A:K:S', 'C:A:K:U', 'C:A:K:Y',
        'C:A:L:V', 'C:A:L:Z', 'C:A:M:V', 'C:A:M:Y', 'C:A:M:Z', 'C:A:N:X',
        'C:A:O:X', 'C:A:P:Z', 'C:A:Q:R', 'C:A:Q:S', 'C:A:Q:T', 'C:A:Q:U',
        'C:A:R:Z', 'C:A:S:V', 'C:A:S:X', 'C:A:S:Z', 'C:A:T:X', 'C:A:T:Z',
        'C:A:U:V', 'C:A:U:Y', 'C:A:V:Y', 'C:A:Y:Z', 'C:B:D:W', 'C:B:E:G',
        'C:B:E:Q', 'C:B:E:W', 'C:B:E:X', 'C:B:E:Y', 'C:B:G:R', 'C:B:I:K',
        'C:B:I:V', 'C:B:I:X', 'C:B:K:U', 'C:B:L:Z', 'C:B:N:X', 'C:B:N:Y',
        'C:B:O:W', 'C:B:Q:S', 'C:B:Q:U', 'C:B:U:Y', 'C:D:E:F', 'C:D:E:Q',
        'C:D:E:W', 'C:D:E:X', 'C:D:F:I', 'C:D:F:J', 'C:D:F:R', 'C:D:G:O',
        'C:D:G:X', 'C:D:G:Z', 'C:D:I:J', 'C:D:I:X', 'C:D:I:Y', 'C:D:M:O',
        'C:D:N:X', 'C:D:N:Y', 'C:D:O:W', 'C:D:O:X', 'C:D:Q:U', 'C:D:S:X',
        'C:D:S:Y', 'C:D:S:Z', 'C:D:T:X', 'C:D:T:Z', 'C:D:U:V', 'C:D:Y:Z',
        'C:E:F:G', 'C:E:F:H', 'C:E:F:J', 'C:E:F:M', 'C:E:G:P', 'C:E:G:X',
        'C:E:H:P', 'C:E:H:S', 'C:E:H:V', 'C:E:I:J', 'C:E:I:K', 'C:E:I:Q',
        'C:E:I:X', 'C:E:K:L', 'C:E:K:O', 'C:E:K:P', 'C:E:K:R', 'C:E:K:S',
        'C:E:L:V', 'C:E:M:P', 'C:E:M:V', 'C:E:N:X', 'C:E:N:Y', 'C:E:O:W',
        'C:E:O:X', 'C:E:Q:R', 'C:E:Q:S', 'C:E:Q:T', 'C:E:Q:U', 'C:E:S:V',
        'C:E:S:X', 'C:E:T:X', 'C:E:U:Y', 'C:E:V:Y', 'C:F:G:N', 'C:F:G:R',
        'C:F:G:U', 'C:F:H:L', 'C:F:H:N', 'C:F:H:O', 'C:F:H:T', 'C:F:I:J',
        'C:F:I:K', 'C:F:I:V', 'C:F:J:N', 'C:F:J:R', 'C:F:K:L', 'C:F:K:N',
        'C:F:K:O', 'C:F:K:R', 'C:F:M:O', 'C:F:O:V', 'C:F:P:Q', 'C:G:I:X',
        'C:G:M:N', 'C:G:M:P', 'C:G:N:P', 'C:G:N:X', 'C:G:O:S', 'C:G:O:X',
        'C:G:O:Z', 'C:G:S:X', 'C:G:S:Z', 'C:G:T:X', 'C:G:T:Z', 'C:G:Y:Z',
        'C:H:I:K', 'C:H:I:W', 'C:H:K:O', 'C:H:K:W', 'C:H:L:W', 'C:H:O:W',
        'C:H:R:V', 'C:H:R:W', 'C:H:S:V', 'C:I:J:N', 'C:I:J:R', 'C:I:K:L',
        'C:I:K:P', 'C:I:K:R', 'C:I:K:S', 'C:I:K:U', 'C:I:K:W', 'C:I:L:W',
        'C:I:N:X', 'C:I:O:W', 'C:I:O:X', 'C:I:Q:R', 'C:I:Q:T', 'C:I:Q:U',
        'C:I:R:W', 'C:I:S:X', 'C:I:S:Z', 'C:I:T:X', 'C:I:T:Z', 'C:I:Y:Z',
        'C:J:K:N', 'C:J:K:O', 'C:J:N:R', 'C:K:L:O', 'C:K:L:P', 'C:K:L:R',
        'C:K:L:S', 'C:K:L:U', 'C:K:L:W', 'C:K:N:O', 'C:K:O:P', 'C:K:O:R',
        'C:K:O:S', 'C:K:O:U', 'C:K:O:W', 'C:K:P:R', 'C:K:P:S', 'C:K:R:S',
        'C:K:R:W', 'C:L:M:V', 'C:L:N:V', 'C:L:O:W', 'C:L:R:W', 'C:L:U:Y',
        'C:L:V:Y', 'C:M:N:V', 'C:M:N:Y', 'C:M:S:Z', 'C:M:T:Z', 'C:M:V:Y',
        'C:M:Y:Z', 'C:N:O:X', 'C:N:S:X', 'C:N:S:Z', 'C:N:T:X', 'C:N:T:Z',
        'C:N:U:Y', 'C:N:V:Y', 'C:N:Y:Z', 'C:O:P:Z', 'C:O:R:W', 'C:O:S:X',
        'C:O:S:Z', 'C:O:T:X', 'C:O:T:Z', 'C:O:Y:Z', 'C:P:R:Z', 'C:Q:R:T',
        'C:Q:R:U', 'C:Q:S:U', 'C:Q:T:U', 'C:S:T:X', 'C:S:T:Z', 'C:S:Y:Z',
        'C:T:Y:Z', 'D:A:B:J', 'D:A:B:Q', 'D:A:B:W', 'D:A:B:Y', 'D:A:B:Z',
        'D:A:C:G', 'D:A:C:J', 'D:A:C:Y', 'D:A:C:Z', 'D:A:E:Q', 'D:A:E:X',
        'D:A:F:G', 'D:A:F:Y', 'D:A:F:Z', 'D:A:G:J', 'D:A:G:K', 'D:A:G:M',
        'D:A:G:P', 'D:A:G:T', 'D:A:G:V', 'D:A:G:Z', 'D:A:H:J', 'D:A:H:K',
        'D:A:H:Q', 'D:A:H:Z', 'D:A:I:X', 'D:A:I:Y', 'D:A:I:Z', 'D:A:J:M',
        'D:A:J:Q', 'D:A:J:T', 'D:A:J:W', 'D:A:J:Y', 'D:A:K:M', 'D:A:K:P',
        'D:A:K:T', 'D:A:K:V', 'D:A:L:Q', 'D:A:L:X', 'D:A:L:Z', 'D:A:M:Q',
        'D:A:M:X', 'D:A:M:Y', 'D:A:N:Q', 'D:A:O:Q', 'D:A:P:Q', 'D:A:P:Z',
        'D:A:Q:R', 'D:A:Q:S', 'D:A:Q:T', 'D:A:Q:U', 'D:A:R:Z', 'D:A:S:W',
        'D:A:S:X', 'D:A:S:Z', 'D:A:T:V', 'D:A:T:Y', 'D:A:T:Z', 'D:A:V:Y',
        'D:A:V:Z', 'D:A:Y:Z', 'D:B:C:K', 'D:B:F:K', 'D:B:K:O', 'D:B:K:T',
        'D:B:O:W', 'D:B:Q:R', 'D:B:Q:U', 'D:B:R:W', 'D:C:F:K', 'D:C:F:Q',
        'D:C:G:R', 'D:C:H:Q', 'D:C:H:W', 'D:C:I:W', 'D:C:J:R', 'D:C:K:O',
        'D:C:K:R', 'D:C:O:W', 'D:C:P:W', 'D:C:R:W', 'D:C:R:Y', 'D:C:R:Z',
        'D:C:Y:Z', 'D:E:G:W', 'D:E:H:K', 'D:E:I:X', 'D:E:K:T', 'D:E:K:V',
        'D:E:K:W', 'D:E:L:W', 'D:E:L:X', 'D:E:M:X', 'D:E:Q:U', 'D:E:S:X',
        'D:E:T:W', 'D:E:T:X', 'D:E:V:Z', 'D:F:G:R', 'D:F:H:X', 'D:F:I:K',
        'D:F:K:O', 'D:F:K:R', 'D:F:L:Z', 'D:F:O:P', 'D:F:O:X', 'D:F:R:Y',
        'D:F:R:Z', 'D:F:U:X', 'D:G:K:N', 'D:G:K:V', 'D:G:L:W', 'D:G:P:R',
        'D:G:R:W', 'D:G:R:Y', 'D:H:I:J', 'D:H:I:K', 'D:H:I:W', 'D:H:K:N',
        'D:H:K:S', 'D:H:N:X', 'D:H:O:W', 'D:H:O:X', 'D:H:P:W', 'D:H:Q:R',
        'D:H:Q:U', 'D:H:R:V', 'D:H:R:W', 'D:H:R:Z', 'D:H:U:X', 'D:H:Y:Z',
        'D:I:J:W', 'D:I:K:P', 'D:I:K:V', 'D:I:L:Q', 'D:I:L:X', 'D:I:M:X',
        'D:I:P:W', 'D:I:Q:S', 'D:I:Q:U', 'D:I:R:Y', 'D:I:S:X', 'D:I:S:Z',
        'D:I:T:X', 'D:J:M:Y', 'D:J:N:W', 'D:J:N:Y', 'D:J:O:Y', 'D:J:Q:R',
        'D:J:Q:U', 'D:J:R:Y', 'D:J:T:Y', 'D:K:L:V', 'D:K:M:O', 'D:K:M:R',
        'D:K:M:U', 'D:K:N:V', 'D:K:O:T', 'D:K:P:S', 'D:K:R:T', 'D:K:S:T',
        'D:L:Q:R', 'D:L:Q:U', 'D:L:S:X', 'D:L:S:Z', 'D:M:Q:R', 'D:M:Q:U',
        'D:M:R:X', 'D:M:R:Y', 'D:N:P:Q', 'D:N:Q:U', 'D:N:U:X', 'D:N:V:Z',
        'D:O:P:W', 'D:O:Q:R', 'D:O:Q:U', 'D:O:R:W', 'D:O:U:X', 'D:O:Y:Z',
        'D:P:Q:U', 'D:P:R:W', 'D:P:R:Y', 'D:Q:R:S', 'D:Q:R:T', 'D:Q:R:U',
        'D:Q:S:U', 'D:Q:T:U', 'D:R:S:W', 'D:R:S:X', 'D:R:S:Y', 'D:R:S:Z',
        'D:R:T:V', 'D:R:T:Y', 'D:R:T:Z', 'D:R:V:Y', 'D:R:Y:Z', 'D:S:T:X',
        'E:A:J:W', 'E:B:Q:U', 'E:D:Q:U', 'E:F:Q:U', 'E:G:Q:U', 'E:H:Q:U',
        'E:I:J:W', 'E:I:W:X', 'E:J:O:W', 'E:J:Q:U', 'E:J:R:W', 'E:J:T:W',
        'E:K:O:X', 'E:K:Q:U', 'E:L:Q:U', 'E:L:W:X', 'E:M:Q:U', 'E:O:W:X',
        'E:P:Q:U', 'E:Q:U:V', 'E:Q:U:W', 'E:Q:U:X', 'E:Q:U:Y', 'E:S:W:X',
        'F:A:B:G', 'F:A:B:M', 'F:A:B:X', 'F:A:C:Q', 'F:A:D:K', 'F:A:D:Q',
        'F:A:D:Y', 'F:A:E:W', 'F:A:G:J', 'F:A:G:X', 'F:A:H:W', 'F:A:H:X',
        'F:A:I:J', 'F:A:J:M', 'F:A:K:N', 'F:A:L:Q', 'F:A:P:W', 'F:A:Q:R',
        'F:A:Q:W', 'F:A:Q:Z', 'F:A:X:Y', 'F:B:C:X', 'F:B:E:Q', 'F:B:G:I',
        'F:B:G:O', 'F:B:G:R', 'F:B:G:T', 'F:B:H:I', 'F:B:I:J', 'F:B:I:M',
        'F:B:I:P', 'F:B:I:Q', 'F:B:J:L', 'F:B:L:X', 'F:B:M:T', 'F:B:O:Q',
        'F:B:O:X', 'F:B:P:Q', 'F:B:Q:U', 'F:C:D:J', 'F:C:G:I', 'F:C:G:J',
        'F:C:G:T', 'F:C:G:X', 'F:C:I:J', 'F:C:I:Q', 'F:C:I:V', 'F:C:I:Y',
        'F:C:J:T', 'F:C:P:Y', 'F:C:Q:T', 'F:C:Q:U', 'F:C:T:Y', 'F:D:G:I',
        'F:D:I:J', 'F:D:I:K', 'F:D:I:L', 'F:D:I:Q', 'F:D:I:W', 'F:D:I:X',
        'F:D:I:Y', 'F:D:J:T', 'F:D:L:Q', 'F:D:N:W', 'F:D:O:Y', 'F:D:Q:T',
        'F:D:Q:U', 'F:D:R:W', 'F:D:S:W', 'F:D:T:Y', 'F:D:U:W', 'F:D:X:Y',
        'F:E:G:X', 'F:E:H:K', 'F:E:H:X', 'F:E:I:J', 'F:E:I:Q', 'F:E:I:X',
        'F:E:I:Y', 'F:E:I:Z', 'F:E:J:L', 'F:E:J:M', 'F:E:J:P', 'F:E:J:R',
        'F:E:K:N', 'F:E:K:P', 'F:E:K:T', 'F:E:M:Y', 'F:E:N:X', 'F:E:N:Y',
        'F:E:N:Z', 'F:E:P:Q', 'F:E:P:W', 'F:E:P:Y', 'F:E:Q:R', 'F:E:Q:U',
        'F:E:S:X', 'F:E:T:Y', 'F:E:U:X', 'F:G:H:L', 'F:G:H:O', 'F:G:I:J',
        'F:G:I:S', 'F:G:I:T', 'F:G:I:V', 'F:G:I:X', 'F:G:J:N', 'F:G:J:O',
        'F:G:J:T', 'F:G:J:U', 'F:G:K:L', 'F:G:K:O', 'F:G:K:U', 'F:G:L:X',
        'F:G:O:X', 'F:G:R:X', 'F:G:T:X', 'F:H:I:X', 'F:H:I:Y', 'F:H:M:Y',
        'F:H:N:Y', 'F:H:P:Y', 'F:H:T:X', 'F:H:T:Y', 'F:I:J:L', 'F:I:J:M',
        'F:I:J:N', 'F:I:J:O', 'F:I:J:P', 'F:I:J:R', 'F:I:J:S', 'F:I:J:T',
        'F:I:J:U', 'F:I:K:T', 'F:I:L:Q', 'F:I:M:N', 'F:I:M:V', 'F:I:M:X',
        'F:I:M:Y', 'F:I:N:P', 'F:I:N:Q', 'F:I:N:W', 'F:I:N:X', 'F:I:N:Y',
        'F:I:N:Z', 'F:I:P:Q', 'F:I:P:V', 'F:I:P:X', 'F:I:Q:R', 'F:I:Q:S',
        'F:I:Q:T', 'F:I:Q:U', 'F:I:R:X', 'F:I:S:W', 'F:I:S:X', 'F:I:T:X',
        'F:I:T:Y', 'F:I:U:X', 'F:I:X:Y', 'F:J:L:O', 'F:J:M:O', 'F:J:M:R',
        'F:J:M:T', 'F:J:N:T', 'F:J:O:P', 'F:J:R:T', 'F:K:L:O', 'F:K:L:U',
        'F:K:O:P', 'F:K:R:S', 'F:K:R:T', 'F:K:R:Y', 'F:K:S:T', 'F:K:S:Y',
        'F:K:T:U', 'F:K:U:Y', 'F:L:O:W', 'F:L:Q:U', 'F:M:O:Y', 'F:M:P:Y',
        'F:M:R:Y', 'F:M:T:Y', 'F:N:P:Y', 'F:N:Q:R', 'F:N:Q:T', 'F:N:Q:U',
        'F:N:R:W', 'F:N:S:W', 'F:N:S:Y', 'F:N:T:Y', 'F:N:U:W', 'F:O:P:Q',
        'F:O:P:W', 'F:O:T:W', 'F:O:U:Z', 'F:O:X:Y', 'F:P:Q:U', 'F:P:R:V',
        'F:P:R:W', 'F:P:T:W', 'F:Q:R:T', 'F:Q:R:U', 'F:Q:S:U', 'F:Q:T:U',
        'F:R:S:W', 'F:R:U:Y', 'F:S:U:W', 'F:S:U:Y', 'F:T:X:Y', 'G:A:B:J',
        'G:A:B:Q', 'G:A:D:J', 'G:A:D:X', 'G:A:F:Y', 'G:A:H:J', 'G:A:H:Q',
        'G:A:H:Y', 'G:A:H:Z', 'G:A:I:V', 'G:A:J:L', 'G:A:J:T', 'G:A:K:P',
        'G:A:K:Q', 'G:A:M:X', 'G:A:M:Y', 'G:A:N:P', 'G:A:N:V', 'G:A:N:Y',
        'G:A:O:Q', 'G:A:P:Q', 'G:A:P:X', 'G:A:P:Z', 'G:A:Q:U', 'G:A:R:X',
        'G:A:W:Y', 'G:A:W:Z', 'G:B:C:X', 'G:B:D:V', 'G:B:E:V', 'G:B:E:Z',
        'G:B:H:X', 'G:B:I:K', 'G:B:I:Q', 'G:B:I:S', 'G:B:I:V', 'G:B:I:Z',
        'G:B:J:N', 'G:B:K:Q', 'G:B:K:X', 'G:B:K:Z', 'G:B:L:Z', 'G:B:N:Q',
        'G:B:N:S', 'G:B:O:W', 'G:B:O:X', 'G:B:Q:U', 'G:B:R:X', 'G:B:R:Z',
        'G:B:T:Z', 'G:B:U:X', 'G:C:E:Z', 'G:C:F:N', 'G:C:H:X', 'G:C:H:Y',
        'G:C:I:V', 'G:C:I:X', 'G:C:I:Z', 'G:C:K:N', 'G:C:K:W', 'G:C:K:X',
        'G:C:N:P', 'G:C:N:V', 'G:C:N:W', 'G:C:N:X', 'G:C:O:X', 'G:C:P:Y',
        'G:C:R:V', 'G:D:E:V', 'G:D:E:X', 'G:D:F:I', 'G:D:F:N', 'G:D:F:Y',
        'G:D:I:K', 'G:D:I:M', 'G:D:I:V', 'G:D:I:X', 'G:D:I:Y', 'G:D:J:L',
        'G:D:J:N', 'G:D:K:N', 'G:D:L:V', 'G:D:M:N', 'G:D:M:X', 'G:D:M:Y',
        'G:D:N:W', 'G:D:N:X', 'G:D:N:Y', 'G:D:O:V', 'G:D:P:X', 'G:D:S:X',
        'G:E:H:X', 'G:E:I:K', 'G:E:I:V', 'G:E:I:X', 'G:E:I:Y', 'G:E:J:T',
        'G:E:K:Z', 'G:E:L:Y', 'G:E:L:Z', 'G:E:M:X', 'G:E:M:Z', 'G:E:N:X',
        'G:E:N:Y', 'G:E:P:W', 'G:E:P:X', 'G:E:R:Y', 'G:E:S:X', 'G:E:S:Z',
        'G:E:T:Z', 'G:E:U:V', 'G:F:H:N', 'G:F:I:M', 'G:F:I:T', 'G:F:I:W',
        'G:F:I:Y', 'G:F:K:N', 'G:F:M:N', 'G:F:M:R', 'G:F:M:Y', 'G:F:N:P',
        'G:F:N:S', 'G:F:N:T', 'G:F:N:W', 'G:F:N:Y', 'G:F:O:W', 'G:F:R:X',
        'G:F:R:Y', 'G:H:I:K', 'G:H:I:V', 'G:H:I:X', 'G:H:I:Y', 'G:H:J:N',
        'G:H:J:O', 'G:H:K:N', 'G:H:N:V', 'G:H:N:X', 'G:H:N:Y', 'G:H:N:Z',
        'G:H:O:Q', 'G:H:O:X', 'G:H:Q:U', 'G:H:S:V', 'G:H:S:X', 'G:H:T:Y',
        'G:H:U:Z', 'G:I:J:K', 'G:I:J:N', 'G:I:J:R', 'G:I:J:S', 'G:I:K:M',
        'G:I:K:Q', 'G:I:K:T', 'G:I:K:V', 'G:I:K:W', 'G:I:K:X', 'G:I:K:Z',
        'G:I:L:Q', 'G:I:L:Y', 'G:I:L:Z', 'G:I:M:X', 'G:I:M:Y', 'G:I:M:Z',
        'G:I:N:Q', 'G:I:N:V', 'G:I:N:X', 'G:I:N:Y', 'G:I:O:Z', 'G:I:P:Q',
        'G:I:P:W', 'G:I:P:X', 'G:I:P:Y', 'G:I:P:Z', 'G:I:Q:S', 'G:I:R:V',
        'G:I:R:Z', 'G:I:S:V', 'G:I:S:X', 'G:I:S:Y', 'G:I:S:Z', 'G:I:T:V',
        'G:I:T:X', 'G:I:T:Y', 'G:I:T:Z', 'G:I:U:V', 'G:I:U:Y', 'G:J:K:N',
        'G:J:K:O', 'G:J:K:R', 'G:J:K:S', 'G:J:L:T', 'G:J:M:N', 'G:J:N:R',
        'G:J:N:S', 'G:J:O:S', 'G:J:R:S', 'G:K:L:Z', 'G:K:M:N', 'G:K:N:P',
        'G:K:N:Q', 'G:K:N:S', 'G:K:N:V', 'G:K:N:W', 'G:K:N:X', 'G:K:O:W',
        'G:K:O:X', 'G:K:Q:U', 'G:K:R:W', 'G:K:R:Z', 'G:K:T:Z', 'G:L:N:Q',
        'G:L:N:Y', 'G:L:P:Q', 'G:L:P:W', 'G:L:P:Y', 'G:L:Q:S', 'G:L:Q:U',
        'G:L:R:Z', 'G:L:T:Z', 'G:L:U:Y', 'G:M:N:P', 'G:M:N:T', 'G:M:N:X',
        'G:M:N:Y', 'G:M:P:X', 'G:M:R:Y', 'G:M:S:X', 'G:N:O:Z', 'G:N:P:Q',
        'G:N:P:W', 'G:N:P:X', 'G:N:P:Y', 'G:N:P:Z', 'G:N:Q:S', 'G:N:R:W',
        'G:N:S:V', 'G:N:S:X', 'G:N:S:Y', 'G:N:T:V', 'G:N:T:X', 'G:N:T:Y',
        'G:N:U:V', 'G:N:U:Y', 'G:N:W:Y', 'G:N:W:Z', 'G:O:Q:U', 'G:O:R:X',
        'G:O:U:V', 'G:O:U:X', 'G:P:Q:U', 'G:P:S:X', 'G:P:U:W', 'G:P:U:Y',
        'G:Q:S:U', 'G:R:U:V', 'G:R:U:X', 'G:S:T:Y', 'G:T:U:V', 'G:U:W:Z',
        'H:A:B:D', 'H:A:B:V', 'H:A:C:Z', 'H:A:D:F', 'H:A:D:G', 'H:A:D:K',
        'H:A:D:N', 'H:A:D:Q', 'H:A:D:U', 'H:A:D:W', 'H:A:F:G', 'H:A:G:M',
        'H:A:G:P', 'H:A:G:Z', 'H:A:J:M', 'H:A:J:R', 'H:A:K:M', 'H:A:K:N',
        'H:A:K:W', 'H:A:K:Z', 'H:A:Q:S', 'H:A:Q:U', 'H:A:R:W', 'H:A:R:Z',
        'H:A:S:Z', 'H:A:U:W', 'H:A:V:Z', 'H:A:W:Y', 'H:A:W:Z', 'H:A:Y:Z',
        'H:B:C:F', 'H:B:C:V', 'H:B:D:E', 'H:B:D:I', 'H:B:F:I', 'H:B:F:L',
        'H:B:F:N', 'H:B:F:U', 'H:B:I:Z', 'H:B:K:Y', 'H:B:L:V', 'H:B:O:V',
        'H:B:O:Y', 'H:B:T:Z', 'H:B:U:Y', 'H:B:U:Z', 'H:C:D:Q', 'H:C:E:J',
        'H:C:E:Z', 'H:C:F:Y', 'H:C:G:L', 'H:C:J:L', 'H:C:J:O', 'H:C:J:P',
        'H:C:J:S', 'H:C:J:T', 'H:C:J:V', 'H:C:N:W', 'H:C:P:V', 'H:C:R:W',
        'H:C:R:Z', 'H:C:S:Z', 'H:C:V:Z', 'H:D:E:F', 'H:D:E:L', 'H:D:F:L',
        'H:D:F:P', 'H:D:F:S', 'H:D:F:T', 'H:D:G:U', 'H:D:I:K', 'H:D:I:Q',
        'H:D:K:S', 'H:D:N:U', 'H:D:O:U', 'H:D:R:U', 'H:D:R:W', 'H:E:J:L',
        'H:E:J:O', 'H:E:J:P', 'H:E:J:S', 'H:E:J:T', 'H:E:J:V', 'H:E:L:W',
        'H:E:M:V', 'H:E:N:V', 'H:E:N:Z', 'H:E:P:V', 'H:E:R:V', 'H:E:R:Z',
        'H:E:S:Z', 'H:E:V:Z', 'H:F:G:I', 'H:F:G:N', 'H:F:G:T', 'H:F:I:K',
        'H:F:I:Q', 'H:F:L:Y', 'H:F:P:S', 'H:F:S:Y', 'H:G:I:M', 'H:G:I:P',
        'H:G:I:V', 'H:G:I:W', 'H:G:I:Z', 'H:G:L:P', 'H:G:M:Z', 'H:G:N:P',
        'H:G:O:V', 'H:G:O:W', 'H:G:O:Y', 'H:G:P:S', 'H:G:R:Y', 'H:G:S:V',
        'H:G:S:W', 'H:G:T:V', 'H:G:T:W', 'H:G:T:Y', 'H:G:U:Y', 'H:I:N:S',
        'H:I:N:W', 'H:I:N:Z', 'H:I:R:W', 'H:I:T:W', 'H:I:W:Y', 'H:I:Y:Z',
        'H:J:L:O', 'H:J:L:P', 'H:J:L:S', 'H:J:L:T', 'H:J:L:V', 'H:J:M:R',
        'H:J:O:P', 'H:J:O:S', 'H:J:O:T', 'H:J:O:V', 'H:J:P:S', 'H:J:P:T',
        'H:J:P:V', 'H:J:S:T', 'H:J:S:V', 'H:J:T:V', 'H:K:W:Z', 'H:L:P:V',
        'H:L:S:W', 'H:M:T:V', 'H:N:R:W', 'H:N:T:Z', 'H:O:P:Q', 'H:O:P:V',
        'H:O:R:W', 'H:O:T:Y', 'H:O:U:W', 'H:O:U:Y', 'H:P:S:V', 'H:P:T:V',
        'H:Q:S:U', 'H:R:S:W', 'H:R:S:Z', 'H:R:V:Z', 'H:S:T:W', 'H:S:U:Z',
        'H:S:V:Z', 'H:W:Y:Z', 'I:A:B:W', 'I:A:B:X', 'I:A:C:W', 'I:A:C:X',
        'I:A:D:W', 'I:A:F:J', 'I:A:F:K', 'I:A:F:Q', 'I:A:F:X', 'I:A:F:Y',
        'I:A:F:Z', 'I:A:G:Q', 'I:A:G:W', 'I:A:H:Q', 'I:A:H:W', 'I:A:H:X',
        'I:A:J:Q', 'I:A:J:V', 'I:A:J:W', 'I:A:J:Y', 'I:A:J:Z', 'I:A:K:Q',
        'I:A:K:X', 'I:A:K:Y', 'I:A:L:Q', 'I:A:M:W', 'I:A:M:X', 'I:A:P:W',
        'I:A:Q:W', 'I:A:Q:X', 'I:A:Q:Z', 'I:A:U:W', 'I:A:U:X', 'I:A:V:W',
        'I:A:W:Z', 'I:A:X:Y', 'I:B:K:Q', 'I:B:Q:U', 'I:C:Q:U', 'I:E:V:W',
        'I:F:Q:U', 'I:G:N:W', 'I:G:U:W', 'I:H:Q:U', 'I:J:N:Y', 'I:J:Q:U',
        'I:K:L:X', 'I:K:M:Q', 'I:K:N:X', 'I:K:O:Q', 'I:K:O:X', 'I:K:Q:R',
        'I:K:Q:U', 'I:L:Q:W', 'I:N:U:W', 'I:N:V:W', 'I:P:Q:U', 'I:Q:U:V',
        'I:Q:U:X', 'I:Q:U:Y', 'I:Q:U:Z', 'I:R:V:W', 'I:S:U:W', 'I:T:V:W',
        'J:A:D:H', 'J:A:D:K', 'J:A:D:M', 'J:A:D:N', 'J:A:K:M', 'J:A:K:N',
        'J:A:K:O', 'J:A:K:R', 'J:A:K:T', 'J:A:K:U', 'J:A:M:N', 'J:A:M:R',
        'J:A:M:U', 'J:A:N:R', 'J:A:N:U', 'J:A:O:T', 'J:A:R:U', 'J:B:D:E',
        'J:B:D:O', 'J:B:D:R', 'J:B:D:U', 'J:B:D:Z', 'J:B:E:O', 'J:B:E:U',
        'J:B:E:Z', 'J:B:O:R', 'J:B:O:U', 'J:B:O:Z', 'J:B:U:Z', 'J:C:D:I',
        'J:D:E:O', 'J:D:E:Z', 'J:D:K:M', 'J:D:K:N', 'J:D:K:R', 'J:D:K:U',
        'J:D:M:N', 'J:D:M:R', 'J:D:M:U', 'J:D:N:R', 'J:D:N:U', 'J:D:O:R',
        'J:D:O:U', 'J:D:O:Z', 'J:D:U:Z', 'J:E:F:U', 'J:E:O:U', 'J:E:O:Z',
        'J:E:U:Z', 'J:I:N:O', 'J:K:M:N', 'J:K:M:R', 'J:K:M:U', 'J:K:N:R',
        'J:K:N:U', 'J:K:O:T', 'J:K:R:U', 'J:M:N:R', 'J:M:N:U', 'J:M:R:U',
        'J:N:R:U', 'J:O:U:Z', 'K:A:B:J', 'K:A:B:Q', 'K:A:B:W', 'K:A:C:W',
        'K:A:C:Z', 'K:A:D:J', 'K:A:D:L', 'K:A:D:P', 'K:A:D:W', 'K:A:D:Y',
        'K:A:E:Q', 'K:A:F:H', 'K:A:H:W', 'K:A:H:Z', 'K:A:I:W', 'K:A:J:L',
        'K:A:M:W', 'K:A:M:Z', 'K:A:N:Q', 'K:A:P:Q', 'K:A:P:V', 'K:A:P:W',
        'K:A:Q:R', 'K:A:Q:T', 'K:A:Q:U', 'K:A:S:V', 'K:A:S:W', 'K:A:U:V',
        'K:A:U:W', 'K:A:W:Z', 'K:B:C:Q', 'K:B:C:V', 'K:B:C:W', 'K:B:D:W',
        'K:B:E:Q', 'K:B:E:V', 'K:B:F:P', 'K:B:G:O', 'K:B:G:S', 'K:B:H:V',
        'K:B:I:V', 'K:B:I:W', 'K:B:J:L', 'K:B:L:V', 'K:B:O:V', 'K:B:Q:R',
        'K:B:Q:T', 'K:B:Q:U', 'K:B:U:W', 'K:B:W:Z', 'K:C:D:G', 'K:C:D:L',
        'K:C:D:M', 'K:C:D:W', 'K:C:E:V', 'K:C:H:V', 'K:C:H:Y', 'K:C:H:Z',
        'K:C:I:V', 'K:C:I:W', 'K:C:J:Y', 'K:C:M:V', 'K:C:Q:U', 'K:C:U:W',
        'K:C:W:Z', 'K:D:E:G', 'K:D:E:L', 'K:D:E:Z', 'K:D:G:O', 'K:D:G:U',
        'K:D:I:Z', 'K:D:L:O', 'K:D:M:U', 'K:D:N:Z', 'K:D:R:W', 'K:E:F:Z',
        'K:E:G:V', 'K:E:H:V', 'K:E:I:W', 'K:E:J:R', 'K:E:M:V', 'K:E:P:Q',
        'K:E:Q:R', 'K:E:Q:T', 'K:E:Q:U', 'K:E:R:Z', 'K:E:U:W', 'K:E:W:Z',
        'K:F:H:L', 'K:F:I:P', 'K:F:I:Z', 'K:F:L:P', 'K:F:N:U', 'K:F:N:Z',
        'K:F:O:P', 'K:F:R:Z', 'K:F:U:Z', 'K:G:I:L', 'K:G:I:T', 'K:G:I:V',
        'K:G:L:O', 'K:G:O:P', 'K:G:O:S', 'K:G:R:T', 'K:H:I:V', 'K:H:M:V',
        'K:H:M:Y', 'K:H:O:W', 'K:H:O:Z', 'K:I:J:M', 'K:I:J:O', 'K:I:J:P',
        'K:I:J:T', 'K:I:J:Y', 'K:I:M:P', 'K:I:M:V', 'K:I:N:V', 'K:I:P:Z',
        'K:I:Q:U', 'K:I:R:V', 'K:I:R:Z', 'K:I:S:V', 'K:I:W:Z', 'K:J:M:O',
        'K:J:M:U', 'K:J:O:P', 'K:J:O:Y', 'K:J:P:R', 'K:J:S:Y', 'K:J:T:Y',
        'K:L:O:V', 'K:L:U:V', 'K:M:N:V', 'K:M:O:W', 'K:N:P:Q', 'K:N:Q:R',
        'K:N:Q:T', 'K:N:Q:U', 'K:N:R:V', 'K:N:R:Y', 'K:N:R:Z', 'K:N:S:V',
        'K:N:S:W', 'K:O:P:W', 'K:O:P:Z', 'K:O:S:W', 'K:O:S:Y', 'K:O:T:Z',
        'K:O:U:V', 'K:P:Q:R', 'K:P:Q:T', 'K:P:Q:U', 'K:P:R:W', 'K:P:S:V',
        'K:P:S:W', 'K:P:U:V', 'K:Q:R:T', 'K:Q:R:U', 'K:Q:T:U', 'K:R:S:V',
        'K:R:S:W', 'K:R:U:W', 'K:R:U:Z', 'K:T:U:W', 'L:A:B:K', 'L:A:F:G',
        'L:A:F:V', 'L:A:F:Z', 'L:A:G:J', 'L:A:G:X', 'L:A:J:K', 'L:A:J:V',
        'L:A:J:W', 'L:A:J:X', 'L:A:J:Y', 'L:A:K:V', 'L:A:K:X', 'L:A:K:Y',
        'L:A:M:Q', 'L:A:M:W', 'L:A:N:W', 'L:A:Q:U', 'L:A:Q:V', 'L:A:Q:X',
        'L:A:Q:Z', 'L:A:S:W', 'L:A:U:W', 'L:A:V:X', 'L:A:V:Z', 'L:A:W:X',
        'L:A:W:Y', 'L:B:J:W', 'L:B:J:Y', 'L:B:N:W', 'L:B:Q:U', 'L:B:S:W',
        'L:B:U:W', 'L:C:J:X', 'L:C:Q:U', 'L:C:Q:V', 'L:C:R:W', 'L:D:E:J',
        'L:D:E:K', 'L:D:F:Z', 'L:D:Q:U', 'L:D:Q:V', 'L:E:F:J', 'L:E:F:Q',
        'L:E:F:W', 'L:E:F:Z', 'L:E:J:W', 'L:E:K:W', 'L:E:K:X', 'L:E:M:Q',
        'L:E:N:W', 'L:E:Q:U', 'L:E:Q:V', 'L:E:Q:X', 'L:E:Q:Z', 'L:E:U:W',
        'L:E:V:X', 'L:E:W:X', 'L:F:I:Q', 'L:F:I:Z', 'L:F:N:Q', 'L:F:N:Z',
        'L:F:Q:R', 'L:F:Q:T', 'L:F:Q:U', 'L:G:I:W', 'L:G:J:U', 'L:G:O:W',
        'L:G:Q:U', 'L:I:Q:S', 'L:I:Q:U', 'L:I:Q:V', 'L:I:Q:X', 'L:I:T:W',
        'L:J:K:Y', 'L:J:N:S', 'L:J:N:W', 'L:J:O:W', 'L:J:O:X', 'L:J:O:Y',
        'L:J:R:W', 'L:J:R:X', 'L:J:R:Y', 'L:J:S:U', 'L:J:T:X', 'L:J:U:W',
        'L:J:U:X', 'L:K:O:Y', 'L:K:T:X', 'L:M:Q:R', 'L:M:Q:U', 'L:M:Q:V',
        'L:M:S:W', 'L:M:W:X', 'L:N:O:W', 'L:N:Q:U', 'L:N:Q:V', 'L:N:Q:X',
        'L:N:R:W', 'L:N:U:W', 'L:O:Q:U', 'L:O:Q:X', 'L:O:S:W', 'L:O:U:W',
        'L:P:Q:U', 'L:Q:R:U', 'L:Q:R:V', 'L:Q:S:U', 'L:Q:T:U', 'L:Q:T:Z',
        'L:Q:U:V', 'L:Q:U:X', 'L:Q:U:Z', 'L:R:U:W', 'M:A:B:J', 'M:A:B:P',
        'M:A:B:W', 'M:A:C:K', 'M:A:C:W', 'M:A:D:J', 'M:A:D:K', 'M:A:D:W',
        'M:A:E:W', 'M:A:F:G', 'M:A:F:P', 'M:A:F:W', 'M:A:G:Q', 'M:A:G:W',
        'M:A:G:Z', 'M:A:H:J', 'M:A:H:V', 'M:A:J:S', 'M:A:K:N', 'M:A:K:S',
        'M:A:K:V', 'M:A:L:Z', 'M:A:N:Q', 'M:A:N:W', 'M:A:P:W', 'M:A:P:Z',
        'M:A:Q:S', 'M:A:Q:V', 'M:A:Q:Y', 'M:A:S:Z', 'M:B:C:W', 'M:B:E:J',
        'M:B:E:V', 'M:B:E:W', 'M:B:F:L', 'M:B:G:U', 'M:B:I:V', 'M:B:I:Z',
        'M:B:J:O', 'M:B:J:R', 'M:B:R:V', 'M:B:U:Z', 'M:C:D:X', 'M:C:E:W',
        'M:C:E:X', 'M:C:H:V', 'M:C:H:X', 'M:C:I:X', 'M:C:K:V', 'M:C:N:X',
        'M:C:O:X', 'M:C:P:U', 'M:C:U:X', 'M:D:E:Z', 'M:D:I:Q', 'M:D:I:W',
        'M:D:J:S', 'M:D:K:O', 'M:D:K:R', 'M:D:L:Q', 'M:D:N:W', 'M:D:O:W',
        'M:D:O:X', 'M:D:Q:U', 'M:D:Q:V', 'M:D:S:X', 'M:D:U:W', 'M:D:U:X',
        'M:D:U:Y', 'M:E:F:S', 'M:E:F:X', 'M:E:G:J', 'M:E:G:Z', 'M:E:H:X',
        'M:E:J:N', 'M:E:J:R', 'M:E:J:S', 'M:E:K:N', 'M:E:K:S', 'M:E:P:Z',
        'M:E:Q:S', 'M:E:Q:U', 'M:E:R:X', 'M:E:S:X', 'M:E:S:Z', 'M:E:V:X',
        'M:F:G:U', 'M:F:I:S', 'M:F:L:V', 'M:F:L:W', 'M:F:L:X', 'M:F:L:Y',
        'M:F:N:U', 'M:F:O:V', 'M:F:O:W', 'M:F:O:Y', 'M:F:P:R', 'M:F:R:S',
        'M:F:R:V', 'M:F:R:W', 'M:F:R:Y', 'M:F:U:X', 'M:G:I:W', 'M:G:J:R',
        'M:G:J:U', 'M:G:L:Z', 'M:G:O:Z', 'M:G:P:Z', 'M:G:Q:U', 'M:G:Q:Y',
        'M:G:T:Z', 'M:G:U:Z', 'M:G:Y:Z', 'M:H:I:K', 'M:H:I:V', 'M:H:I:X',
        'M:H:J:S', 'M:H:K:N', 'M:H:K:V', 'M:H:N:X', 'M:H:O:V', 'M:H:O:W',
        'M:H:R:V', 'M:H:R:W', 'M:H:S:W', 'M:H:S:Z', 'M:H:T:V', 'M:H:U:V',
        'M:H:U:X', 'M:I:J:L', 'M:I:J:O', 'M:I:J:T', 'M:I:J:U', 'M:I:K:N',
        'M:I:K:T', 'M:I:K:V', 'M:I:K:W', 'M:I:K:Z', 'M:I:L:Q', 'M:I:N:W',
        'M:I:N:X', 'M:I:Q:S', 'M:I:Q:U', 'M:I:Q:V', 'M:I:S:V', 'M:I:S:Z',
        'M:I:U:X', 'M:I:V:X', 'M:J:L:O', 'M:J:L:S', 'M:J:L:T', 'M:J:N:U',
        'M:J:O:S', 'M:J:O:T', 'M:J:S:T', 'M:K:L:W', 'M:K:N:S', 'M:K:N:Z',
        'M:K:O:T', 'M:K:O:V', 'M:K:O:W', 'M:K:R:V', 'M:K:S:Z', 'M:K:T:U',
        'M:K:T:V', 'M:K:U:V', 'M:L:Q:U', 'M:L:U:Z', 'M:L:V:X', 'M:N:Q:S',
        'M:N:Q:U', 'M:N:S:Z', 'M:N:U:W', 'M:N:U:X', 'M:O:Q:R', 'M:O:Q:U',
        'M:O:S:W', 'M:O:S:X', 'M:O:U:X', 'M:P:U:W', 'M:Q:R:U', 'M:Q:R:V',
        'M:Q:S:U', 'M:Q:T:U', 'M:Q:U:V', 'M:Q:U:Y', 'M:R:S:W', 'M:R:S:X',
        'M:R:T:X', 'M:R:U:X', 'M:S:T:X', 'M:S:U:V', 'M:S:U:X', 'M:T:U:X',
        'M:T:Y:Z', 'M:U:V:X', 'M:U:Y:Z', 'N:A:J:W', 'N:A:K:X', 'N:A:Q:X',
        'N:A:V:W', 'N:A:W:X', 'N:A:X:Z', 'N:B:Q:U', 'N:C:Q:U', 'N:D:I:Q',
        'N:D:Q:U', 'N:E:J:K', 'N:E:J:Y', 'N:E:K:V', 'N:E:Q:V', 'N:E:Q:X',
        'N:E:V:W', 'N:E:V:Z', 'N:E:X:Z', 'N:F:I:Q', 'N:F:Q:U', 'N:G:Q:U',
        'N:H:Q:U', 'N:I:J:K', 'N:I:J:Q', 'N:I:J:X', 'N:I:Q:V', 'N:I:Q:X',
        'N:I:Q:Z', 'N:I:V:W', 'N:I:V:X', 'N:I:W:X', 'N:I:X:Z', 'N:J:K:O',
        'N:J:K:S', 'N:J:M:W', 'N:J:O:W', 'N:J:O:X', 'N:J:Q:U', 'N:J:W:Z',
        'N:K:L:X', 'N:K:O:X', 'N:M:Q:U', 'N:M:W:X', 'N:O:W:X', 'N:Q:S:X',
        'N:Q:T:X', 'N:Q:U:V', 'N:Q:U:W', 'N:Q:U:X', 'N:Q:U:Y', 'N:Q:U:Z',
        'N:R:X:Z', 'N:T:W:X', 'O:A:B:Q', 'O:A:B:W', 'O:A:B:Z', 'O:A:D:F',
        'O:A:D:Q', 'O:A:D:W', 'O:A:E:W', 'O:A:F:H', 'O:A:F:Z', 'O:A:G:X',
        'O:A:H:K', 'O:A:H:Q', 'O:A:J:V', 'O:A:J:Z', 'O:A:K:Q', 'O:A:K:W',
        'O:A:L:W', 'O:A:N:W', 'O:A:P:W', 'O:A:P:Z', 'O:A:Q:U', 'O:A:Q:V',
        'O:A:Q:X', 'O:B:C:Y', 'O:B:D:W', 'O:B:E:W', 'O:B:I:W', 'O:B:Q:U',
        'O:B:R:W', 'O:B:S:Y', 'O:C:E:Q', 'O:C:F:H', 'O:C:H:Q', 'O:C:H:V',
        'O:C:I:X', 'O:C:Q:U', 'O:C:T:X', 'O:C:V:Y', 'O:D:E:W', 'O:D:E:X',
        'O:D:F:Z', 'O:D:I:V', 'O:D:I:X', 'O:D:Q:U', 'O:D:U:X', 'O:D:Y:Z',
        'O:E:G:Q', 'O:E:G:X', 'O:E:H:Q', 'O:E:H:V', 'O:E:J:L', 'O:E:J:Z',
        'O:E:K:Q', 'O:E:L:W', 'O:E:M:X', 'O:E:P:W', 'O:E:Q:U', 'O:E:Q:V',
        'O:E:Q:X', 'O:E:V:X', 'O:E:Y:Z', 'O:F:N:Z', 'O:F:R:Z', 'O:G:I:Q',
        'O:G:I:X', 'O:G:M:Q', 'O:G:M:X', 'O:G:Q:S', 'O:G:Q:U', 'O:G:S:X',
        'O:H:I:V', 'O:H:I:X', 'O:H:L:V', 'O:H:P:X', 'O:H:Q:U', 'O:H:R:V',
        'O:H:S:V', 'O:I:J:T', 'O:I:L:Q', 'O:I:M:Q', 'O:I:M:X', 'O:I:P:Q',
        'O:I:Q:U', 'O:I:V:Y', 'O:J:L:Z', 'O:J:M:T', 'O:J:U:Y', 'O:J:U:Z',
        'O:K:N:W', 'O:K:Q:S', 'O:K:Q:U', 'O:L:P:W', 'O:L:Q:U', 'O:L:R:W',
        'O:L:T:W', 'O:M:Q:S', 'O:M:Q:U', 'O:M:S:X', 'O:N:Q:U', 'O:P:Q:U',
        'O:P:R:W', 'O:P:R:X', 'O:P:T:W', 'O:P:V:Y', 'O:Q:R:U', 'O:Q:R:V',
        'O:Q:S:U', 'O:Q:T:U', 'O:Q:U:V', 'O:Q:U:X', 'O:T:V:X', 'P:A:B:L',
        'P:A:B:M', 'P:A:B:N', 'P:A:C:M', 'P:A:D:K', 'P:A:D:Y', 'P:A:E:Y',
        'P:A:F:G', 'P:A:F:M', 'P:A:F:O', 'P:A:G:M', 'P:A:G:T', 'P:A:H:J',
        'P:A:H:Y', 'P:A:J:K', 'P:A:J:O', 'P:A:K:N', 'P:A:K:Y', 'P:A:L:T',
        'P:A:L:Y', 'P:A:M:V', 'P:A:M:Y', 'P:A:N:Y', 'P:B:D:E', 'P:B:D:S',
        'P:B:D:T', 'P:B:D:U', 'P:B:E:U', 'P:B:H:I', 'P:B:H:O', 'P:B:H:S',
        'P:B:I:N', 'P:B:L:R', 'P:B:L:T', 'P:B:N:O', 'P:B:N:R', 'P:C:D:G',
        'P:C:D:V', 'P:C:D:Y', 'P:C:E:Q', 'P:C:E:V', 'P:C:G:Y', 'P:C:H:Y',
        'P:C:I:Q', 'P:C:I:V', 'P:C:I:Y', 'P:C:K:Q', 'P:C:K:U', 'P:C:L:V',
        'P:C:L:Y', 'P:C:O:V', 'P:C:O:Y', 'P:C:Q:S', 'P:C:Q:T', 'P:C:Q:U',
        'P:D:E:K', 'P:D:E:T', 'P:D:E:V', 'P:D:F:N', 'P:D:F:U', 'P:D:H:Y',
        'P:D:I:V', 'P:D:I:Y', 'P:D:K:R', 'P:D:K:S', 'P:D:K:T', 'P:D:L:V',
        'P:D:L:Y', 'P:D:N:Y', 'P:D:O:V', 'P:D:O:Y', 'P:D:S:T', 'P:E:F:H',
        'P:E:F:N', 'P:E:F:R', 'P:E:F:S', 'P:E:F:U', 'P:E:G:M', 'P:E:I:Q',
        'P:E:K:N', 'P:E:K:Q', 'P:E:K:T', 'P:E:K:Y', 'P:E:L:V', 'P:E:M:Y',
        'P:E:N:Y', 'P:E:O:V', 'P:E:Q:S', 'P:E:Q:T', 'P:E:Q:U', 'P:E:U:V',
        'P:F:G:L', 'P:F:G:M', 'P:F:G:O', 'P:F:H:O', 'P:F:H:R', 'P:F:H:S',
        'P:F:I:L', 'P:F:I:N', 'P:F:I:U', 'P:F:L:N', 'P:F:L:U', 'P:F:M:O',
        'P:F:N:R', 'P:F:N:U', 'P:F:O:S', 'P:F:R:S', 'P:F:R:U', 'P:G:I:T',
        'P:G:I:Y', 'P:G:L:M', 'P:G:M:O', 'P:G:O:T', 'P:G:O:Y', 'P:G:R:T',
        'P:G:S:Y', 'P:H:I:W', 'P:H:I:Y', 'P:H:J:K', 'P:H:J:L', 'P:H:J:O',
        'P:H:J:U', 'P:H:K:W', 'P:H:L:Y', 'P:H:N:W', 'P:H:N:Y', 'P:H:O:W',
        'P:H:O:Y', 'P:H:T:W', 'P:I:K:Q', 'P:I:L:Y', 'P:I:N:W', 'P:I:O:V',
        'P:I:O:Y', 'P:I:Q:S', 'P:I:Q:T', 'P:I:Q:U', 'P:I:T:W', 'P:J:K:L',
        'P:J:K:O', 'P:J:K:U', 'P:J:L:O', 'P:J:M:U', 'P:J:O:U', 'P:K:M:N',
        'P:K:M:Y', 'P:K:N:Y', 'P:K:O:W', 'P:K:Q:S', 'P:K:Q:T', 'P:K:Q:U',
        'P:K:R:W', 'P:K:S:W', 'P:L:N:Y', 'P:L:O:V', 'P:L:O:Y', 'P:L:U:V',
        'P:M:N:Y', 'P:N:O:S', 'P:N:O:W', 'P:N:S:W', 'P:N:T:W', 'P:O:S:W',
        'P:O:S:Y', 'P:O:T:W', 'P:O:U:V', 'P:O:U:Y', 'P:Q:S:T', 'P:Q:S:U',
        'P:Q:T:U', 'P:R:S:V', 'P:S:T:W', 'P:S:U:V', 'Q:A:B:C', 'Q:A:B:H',
        'Q:A:B:M', 'Q:A:B:P', 'Q:A:B:S', 'Q:A:B:T', 'Q:A:B:Y', 'Q:A:C:E',
        'Q:A:C:H', 'Q:A:C:O', 'Q:A:C:P', 'Q:A:C:R', 'Q:A:C:T', 'Q:A:C:Y',
        'Q:A:D:R', 'Q:A:D:S', 'Q:A:E:H', 'Q:A:E:P', 'Q:A:E:T', 'Q:A:E:Y',
        'Q:A:H:M', 'Q:A:H:O', 'Q:A:H:T', 'Q:A:I:L', 'Q:A:I:M', 'Q:A:I:P',
        'Q:A:I:V', 'Q:A:L:M', 'Q:A:L:S', 'Q:A:L:Y', 'Q:A:M:N', 'Q:A:M:P',
        'Q:A:M:U', 'Q:A:M:V', 'Q:A:N:P', 'Q:A:N:S', 'Q:A:N:V', 'Q:A:N:Y',
        'Q:A:O:P', 'Q:A:P:S', 'Q:A:P:U', 'Q:A:U:V', 'Q:A:U:Y', 'Q:B:C:E',
        'Q:B:C:H', 'Q:B:C:I', 'Q:B:C:L', 'Q:B:C:M', 'Q:B:C:N', 'Q:B:C:O',
        'Q:B:C:P', 'Q:B:C:S', 'Q:B:C:T', 'Q:B:C:U', 'Q:B:C:Y', 'Q:B:E:H',
        'Q:B:E:M', 'Q:B:E:N', 'Q:B:E:P', 'Q:B:E:T', 'Q:B:E:U', 'Q:B:E:Y',
        'Q:B:H:N', 'Q:B:H:O', 'Q:B:H:T', 'Q:B:I:O', 'Q:B:L:N', 'Q:B:L:O',
        'Q:B:L:S', 'Q:B:L:U', 'Q:B:L:Y', 'Q:B:M:N', 'Q:B:M:O', 'Q:B:M:P',
        'Q:B:M:S', 'Q:B:N:P', 'Q:B:N:T', 'Q:B:N:U', 'Q:B:N:Y', 'Q:B:O:P',
        'Q:B:O:S', 'Q:B:O:T', 'Q:B:P:S', 'Q:B:U:Y', 'Q:C:D:O', 'Q:C:D:R',
        'Q:C:D:V', 'Q:C:E:H', 'Q:C:E:M', 'Q:C:E:O', 'Q:C:E:P', 'Q:C:E:R',
        'Q:C:E:S', 'Q:C:E:T', 'Q:C:E:U', 'Q:C:E:V', 'Q:C:E:Y', 'Q:C:H:M',
        'Q:C:H:O', 'Q:C:H:T', 'Q:C:I:O', 'Q:C:I:R', 'Q:C:I:S', 'Q:C:I:V',
        'Q:C:L:N', 'Q:C:L:O', 'Q:C:L:S', 'Q:C:L:Y', 'Q:C:M:O', 'Q:C:M:P',
        'Q:C:M:R', 'Q:C:M:S', 'Q:C:M:T', 'Q:C:N:O', 'Q:C:N:P', 'Q:C:N:Y',
        'Q:C:O:P', 'Q:C:O:R', 'Q:C:O:S', 'Q:C:O:T', 'Q:C:O:U', 'Q:C:O:V',
        'Q:C:P:S', 'Q:C:R:S', 'Q:C:R:T', 'Q:C:R:U', 'Q:C:S:T', 'Q:C:S:U',
        'Q:C:U:Y', 'Q:D:E:I', 'Q:D:E:O', 'Q:D:E:V', 'Q:D:E:Z', 'Q:D:I:O',
        'Q:D:I:V', 'Q:D:I:Z', 'Q:D:N:S', 'Q:D:N:Z', 'Q:D:O:V', 'Q:E:H:M',
        'Q:E:H:N', 'Q:E:H:O', 'Q:E:H:T', 'Q:E:I:R', 'Q:E:I:V', 'Q:E:I:Z',
        'Q:E:L:N', 'Q:E:L:Y', 'Q:E:M:O', 'Q:E:M:P', 'Q:E:M:R', 'Q:E:M:S',
        'Q:E:M:T', 'Q:E:N:P', 'Q:E:N:T', 'Q:E:N:Y', 'Q:E:N:Z', 'Q:E:O:P',
        'Q:E:O:R', 'Q:E:O:S', 'Q:E:O:T', 'Q:E:O:U', 'Q:E:O:V', 'Q:E:P:S',
        'Q:E:R:S', 'Q:E:R:T', 'Q:E:R:U', 'Q:E:S:T', 'Q:E:S:U', 'Q:E:U:Y',
        'Q:H:M:T', 'Q:H:N:O', 'Q:H:N:T', 'Q:H:O:T', 'Q:I:L:M', 'Q:I:L:S',
        'Q:I:M:U', 'Q:I:M:V', 'Q:I:N:P', 'Q:I:N:V', 'Q:I:N:Z', 'Q:I:O:R',
        'Q:I:O:S', 'Q:I:O:V', 'Q:I:P:U', 'Q:I:R:S', 'Q:I:R:U', 'Q:I:S:U',
        'Q:I:U:V', 'Q:L:M:U', 'Q:L:N:U', 'Q:L:N:Y', 'Q:L:O:S', 'Q:L:U:Y',
        'Q:M:N:P', 'Q:M:N:V', 'Q:M:O:P', 'Q:M:O:R', 'Q:M:O:S', 'Q:M:P:S',
        'Q:M:R:S', 'Q:M:R:T', 'Q:M:S:T', 'Q:M:U:V', 'Q:N:O:P', 'Q:N:P:S',
        'Q:N:P:U', 'Q:N:U:V', 'Q:N:U:Y', 'Q:O:P:S', 'Q:O:R:S', 'Q:O:R:T',
        'Q:O:R:U', 'Q:O:S:T', 'Q:O:S:U', 'Q:R:S:T', 'Q:R:S:U', 'R:A:E:X',
        'R:A:J:Z', 'R:A:M:W', 'R:B:E:W', 'R:B:E:X', 'R:B:Q:U', 'R:C:E:W',
        'R:C:E:X', 'R:C:Q:U', 'R:D:E:W', 'R:D:E:X', 'R:E:F:Q', 'R:E:F:W',
        'R:E:F:X', 'R:E:G:Q', 'R:E:G:W', 'R:E:G:X', 'R:E:H:Q', 'R:E:H:X',
        'R:E:I:X', 'R:E:J:V', 'R:E:J:X', 'R:E:J:Y', 'R:E:J:Z', 'R:E:K:Q',
        'R:E:K:X', 'R:E:L:W', 'R:E:L:X', 'R:E:M:W', 'R:E:M:X', 'R:E:N:X',
        'R:E:P:X', 'R:E:Q:X', 'R:E:Q:Y', 'R:E:Q:Z', 'R:E:T:X', 'R:E:U:W',
        'R:E:V:W', 'R:E:V:X', 'R:E:V:Y', 'R:E:X:Y', 'R:E:Y:Z', 'R:F:Q:U',
        'R:G:Q:U', 'R:H:Q:U', 'R:I:V:Z', 'R:J:O:Y', 'R:K:O:X', 'R:K:Q:U',
        'R:L:Q:U', 'R:M:Q:U', 'R:N:Q:U', 'R:O:Q:U', 'R:P:Q:U', 'R:Q:U:V',
        'R:Q:U:X', 'R:Q:U:Y', 'R:Q:U:Z', 'S:A:J:W', 'S:B:J:W', 'S:E:X:Z',
        'S:I:J:W', 'S:J:O:W', 'S:J:Q:U', 'S:K:Q:U', 'S:Q:U:V', 'S:Q:U:X',
        'T:A:J:Z', 'T:A:K:Q', 'T:A:K:X', 'T:A:M:W', 'T:A:Q:W', 'T:A:W:Y',
        'T:A:W:Z', 'T:B:Q:U', 'T:C:Q:U', 'T:D:Q:U', 'T:E:G:K', 'T:E:Q:W',
        'T:E:V:W', 'T:F:Q:U', 'T:G:Q:U', 'T:G:Q:W', 'T:G:U:W', 'T:H:Q:U',
        'T:I:Q:W', 'T:I:U:W', 'T:I:V:W', 'T:I:W:Y', 'T:J:Q:U', 'T:K:L:X',
        'T:K:M:Q', 'T:K:N:X', 'T:K:O:X', 'T:K:Q:U', 'T:L:Q:U', 'T:M:Q:U',
        'T:M:Q:W', 'T:N:Q:W', 'T:N:U:W', 'T:N:V:W', 'T:N:W:Z', 'T:P:Q:U',
        'T:Q:R:W', 'T:Q:U:V', 'T:Q:U:W', 'T:Q:U:X', 'T:Q:U:Y', 'T:Q:U:Z',
        'T:R:V:W', 'T:R:W:Y', 'U:A:B:P', 'U:A:B:Q', 'U:A:B:Y', 'U:A:C:J',
        'U:A:C:K', 'U:A:C:Q', 'U:A:C:W', 'U:A:C:X', 'U:A:D:Q', 'U:A:D:Z',
        'U:A:E:Q', 'U:A:E:X', 'U:A:G:V', 'U:A:G:W', 'U:A:H:K', 'U:A:J:K',
        'U:A:J:M', 'U:A:J:P', 'U:A:J:Q', 'U:A:J:V', 'U:A:J:Y', 'U:A:K:W',
        'U:A:L:Q', 'U:A:L:W', 'U:A:L:X', 'U:A:L:Y', 'U:A:M:Q', 'U:A:N:W',
        'U:A:O:W', 'U:A:O:X', 'U:A:P:W', 'U:A:Q:R', 'U:A:Q:S', 'U:A:Q:V',
        'U:A:S:Z', 'U:A:T:X', 'U:A:V:Z', 'U:A:W:Z', 'U:B:E:Q', 'U:B:E:V',
        'U:C:E:X', 'U:C:F:H', 'U:C:J:O', 'U:C:K:N', 'U:C:L:X', 'U:C:O:W',
        'U:C:P:W', 'U:C:R:X', 'U:C:T:X', 'U:D:E:Q', 'U:D:I:Q', 'U:D:J:Q',
        'U:D:K:O', 'U:D:M:Q', 'U:D:N:Y', 'U:D:Q:R', 'U:E:J:M', 'U:E:J:V',
        'U:E:L:X', 'U:E:M:Q', 'U:E:P:Y', 'U:E:Q:S', 'U:E:Q:V', 'U:E:R:X',
        'U:E:R:Z', 'U:E:T:X', 'U:F:J:L', 'U:F:J:O', 'U:G:H:N', 'U:G:I:X',
        'U:G:J:N', 'U:G:J:R', 'U:G:N:W', 'U:G:N:X', 'U:G:W:Z', 'U:H:K:W',
        'U:H:S:W', 'U:I:J:K', 'U:I:J:Q', 'U:I:K:Z', 'U:I:N:X', 'U:I:P:Q',
        'U:I:P:Z', 'U:I:Q:S', 'U:I:Q:V', 'U:I:S:Z', 'U:J:K:N', 'U:J:K:O',
        'U:J:O:P', 'U:J:O:Y', 'U:J:P:S', 'U:K:M:V', 'U:K:M:Z', 'U:K:S:W',
        'U:L:O:W', 'U:L:O:Y', 'U:L:Q:V', 'U:L:T:X', 'U:M:Q:S', 'U:N:O:X',
        'U:N:W:Z', 'U:O:P:W', 'U:O:T:X', 'U:O:V:Y', 'U:O:V:Z', 'V:A:C:H',
        'V:A:C:I', 'V:A:C:K', 'V:A:C:L', 'V:A:C:N', 'V:A:C:S', 'V:A:H:I',
        'V:A:H:K', 'V:A:H:L', 'V:A:H:M', 'V:A:H:N', 'V:A:H:O', 'V:A:H:S',
        'V:A:I:K', 'V:A:I:L', 'V:A:K:L', 'V:A:K:N', 'V:A:K:O', 'V:A:L:N',
        'V:A:L:O', 'V:A:M:O', 'V:A:M:S', 'V:A:N:O', 'V:A:N:S', 'V:C:H:I',
        'V:C:H:K', 'V:C:H:L', 'V:C:H:N', 'V:C:H:O', 'V:C:I:K', 'V:C:I:L',
        'V:C:I:S', 'V:C:K:L', 'V:C:K:N', 'V:C:K:O', 'V:C:L:N', 'V:C:L:O',
        'V:C:O:U', 'V:E:I:K', 'V:E:I:L', 'V:E:I:M', 'V:E:I:S', 'V:E:I:T',
        'V:E:K:L', 'V:E:K:S', 'V:E:L:M', 'V:E:L:S', 'V:E:L:T', 'V:E:M:O',
        'V:E:M:T', 'V:E:O:R', 'V:E:O:T', 'V:E:O:U', 'V:E:R:U', 'V:H:I:K',
        'V:H:I:L', 'V:H:I:N', 'V:H:I:O', 'V:H:K:L', 'V:H:K:N', 'V:H:K:O',
        'V:H:L:N', 'V:H:L:O', 'V:H:M:O', 'V:H:M:S', 'V:H:N:O', 'V:H:N:S',
        'V:H:O:S', 'V:I:K:L', 'V:I:K:N', 'V:I:L:M', 'V:I:L:N', 'V:I:L:O',
        'V:I:L:S', 'V:I:L:T', 'V:I:M:O', 'V:I:M:T', 'V:I:N:O', 'V:I:N:S',
        'V:I:N:U', 'V:I:O:T', 'V:K:L:N', 'V:K:L:S', 'V:K:N:O', 'V:K:N:S',
        'V:K:O:R', 'V:K:O:U', 'V:K:R:S', 'V:K:R:U', 'V:K:S:U', 'V:L:M:O',
        'V:L:M:T', 'V:L:N:O', 'V:L:N:S', 'V:L:O:T', 'V:M:O:S', 'V:M:O:T',
        'V:N:O:S', 'V:O:R:S', 'V:O:R:U', 'V:O:S:U', 'V:O:U:Y', 'V:R:S:U',
        'W:A:B:G', 'W:A:B:L', 'W:A:B:N', 'W:A:B:O', 'W:A:B:U', 'W:A:C:E',
        'W:A:C:F', 'W:A:C:I', 'W:A:C:K', 'W:A:C:L', 'W:A:C:M', 'W:A:C:S',
        'W:A:D:G', 'W:A:D:K', 'W:A:D:N', 'W:A:D:O', 'W:A:D:S', 'W:A:D:T',
        'W:A:D:U', 'W:A:E:L', 'W:A:E:O', 'W:A:E:S', 'W:A:F:H', 'W:A:F:L',
        'W:A:F:O', 'W:A:F:S', 'W:A:G:L', 'W:A:G:N', 'W:A:G:T', 'W:A:G:U',
        'W:A:H:I', 'W:A:H:K', 'W:A:H:L', 'W:A:H:M', 'W:A:H:R', 'W:A:H:T',
        'W:A:I:K', 'W:A:I:L', 'W:A:I:P', 'W:A:I:S', 'W:A:K:L', 'W:A:K:N',
        'W:A:K:O', 'W:A:K:R', 'W:A:K:S', 'W:A:K:T', 'W:A:L:M', 'W:A:L:N',
        'W:A:L:P', 'W:A:L:R', 'W:A:L:T', 'W:A:L:U', 'W:A:M:O', 'W:A:M:R',
        'W:A:M:S', 'W:A:N:U', 'W:A:O:T', 'W:A:O:U', 'W:A:Q:S', 'W:A:Q:U',
        'W:A:R:S', 'W:A:S:T', 'W:A:S:U', 'W:A:T:U', 'W:B:G:L', 'W:B:G:N',
        'W:B:G:O', 'W:B:G:U', 'W:B:L:N', 'W:B:L:O', 'W:B:L:U', 'W:B:N:O',
        'W:B:N:U', 'W:B:O:U', 'W:C:E:L', 'W:C:E:O', 'W:C:E:S', 'W:C:F:H',
        'W:C:F:L', 'W:C:F:O', 'W:C:F:S', 'W:C:H:I', 'W:C:H:K', 'W:C:H:M',
        'W:C:I:K', 'W:C:I:R', 'W:C:I:S', 'W:C:K:R', 'W:C:K:S', 'W:C:L:M',
        'W:C:L:O', 'W:C:M:O', 'W:D:G:N', 'W:D:G:T', 'W:D:K:N', 'W:D:K:T',
        'W:D:N:O', 'W:D:N:S', 'W:D:N:T', 'W:D:O:S', 'W:E:H:O', 'W:E:H:P',
        'W:E:H:S', 'W:E:I:N', 'W:E:I:R', 'W:E:I:T', 'W:E:I:V', 'W:E:L:O',
        'W:E:L:S', 'W:E:N:R', 'W:E:N:T', 'W:E:N:V', 'W:E:O:P', 'W:E:O:S',
        'W:E:P:S', 'W:E:R:T', 'W:E:R:V', 'W:E:T:V', 'W:F:H:L', 'W:F:H:O',
        'W:F:H:S', 'W:F:L:O', 'W:F:L:S', 'W:F:O:S', 'W:G:L:N', 'W:G:L:O',
        'W:G:L:U', 'W:G:N:T', 'W:G:N:U', 'W:G:O:U', 'W:H:I:K', 'W:H:I:R',
        'W:H:I:S', 'W:H:K:L', 'W:H:K:O', 'W:H:K:R', 'W:H:K:S', 'W:H:K:T',
        'W:H:L:M', 'W:H:L:O', 'W:H:L:R', 'W:H:L:T', 'W:H:M:O', 'W:H:M:R',
        'W:H:M:S', 'W:H:O:P', 'W:H:O:T', 'W:H:P:S', 'W:H:R:S', 'W:H:S:T',
        'W:I:K:R', 'W:I:K:S', 'W:I:L:P', 'W:I:N:R', 'W:I:N:T', 'W:I:N:V',
        'W:I:R:S', 'W:I:R:T', 'W:I:R:V', 'W:I:T:V', 'W:K:L:O', 'W:K:L:S',
        'W:K:L:T', 'W:K:N:T', 'W:K:O:S', 'W:K:O:T', 'W:K:R:S', 'W:K:S:T',
        'W:L:M:O', 'W:L:M:R', 'W:L:M:S', 'W:L:N:O', 'W:L:N:U', 'W:L:O:R',
        'W:L:O:S', 'W:L:O:T', 'W:L:O:U', 'W:L:R:S', 'W:L:S:T', 'W:L:T:U',
        'W:M:O:R', 'W:M:O:S', 'W:M:R:S', 'W:N:O:S', 'W:N:O:U', 'W:N:R:T',
        'W:N:R:V', 'W:N:T:V', 'W:O:P:S', 'W:O:S:T', 'W:O:T:U', 'W:Q:S:U',
        'W:R:T:V', 'X:A:B:Z', 'X:A:C:K', 'X:A:C:Z', 'X:A:D:K', 'X:A:D:Z',
        'X:A:E:W', 'X:A:F:J', 'X:A:G:J', 'X:A:G:K', 'X:A:G:Q', 'X:A:H:K',
        'X:A:H:W', 'X:A:H:Z', 'X:A:I:W', 'X:A:J:L', 'X:A:J:P', 'X:A:J:Q',
        'X:A:J:U', 'X:A:J:V', 'X:A:K:M', 'X:A:K:P', 'X:A:K:R', 'X:A:K:U',
        'X:A:K:V', 'X:A:M:W', 'X:A:M:Z', 'X:A:P:Z', 'X:A:Q:U', 'X:A:Q:Z',
        'X:A:R:W', 'X:A:R:Z', 'X:A:S:Z', 'X:A:T:Z', 'X:A:U:Z', 'X:A:V:Z',
        'X:A:Y:Z', 'X:B:E:Q', 'X:B:E:Z', 'X:B:G:U', 'X:B:H:U', 'X:B:J:K',
        'X:B:J:U', 'X:B:K:U', 'X:B:P:U', 'X:B:Q:U', 'X:B:S:U', 'X:B:U:V',
        'X:B:U:Z', 'X:C:E:W', 'X:C:F:U', 'X:C:G:U', 'X:C:H:W', 'X:C:J:P',
        'X:C:J:U', 'X:C:K:T', 'X:C:K:U', 'X:C:O:W', 'X:C:P:W', 'X:C:Q:U',
        'X:C:R:W', 'X:C:U:Z', 'X:D:E:F', 'X:D:E:J', 'X:D:E:K', 'X:D:F:U',
        'X:D:G:U', 'X:D:I:J', 'X:D:I:Z', 'X:D:J:U', 'X:D:K:U', 'X:D:K:V',
        'X:D:O:Z', 'X:D:Q:U', 'X:D:U:Z', 'X:E:F:J', 'X:E:F:Y', 'X:E:G:Q',
        'X:E:G:Z', 'X:E:H:Q', 'X:E:H:V', 'X:E:H:W', 'X:E:I:W', 'X:E:J:K',
        'X:E:J:S', 'X:E:J:U', 'X:E:K:S', 'X:E:K:V', 'X:E:M:Q', 'X:E:P:Z',
        'X:E:Q:U', 'X:E:Q:V', 'X:E:Q:Y', 'X:E:Q:Z', 'X:E:R:W', 'X:E:S:Z',
        'X:E:U:Z', 'X:F:G:U', 'X:F:I:Q', 'X:F:J:M', 'X:F:J:N', 'X:F:J:O',
        'X:F:J:T', 'X:F:J:U', 'X:F:K:U', 'X:F:M:U', 'X:F:Q:U', 'X:F:R:Y',
        'X:F:S:U', 'X:F:U:V', 'X:F:U:Y', 'X:G:J:U', 'X:G:K:U', 'X:G:N:U',
        'X:G:Q:U', 'X:G:U:Y', 'X:G:U:Z', 'X:H:I:W', 'X:H:K:U', 'X:H:K:V',
        'X:H:Q:U', 'X:H:R:W', 'X:H:U:Z', 'X:H:Y:Z', 'X:I:J:Q', 'X:I:J:U',
        'X:I:K:V', 'X:I:M:W', 'X:I:Q:U', 'X:I:R:W', 'X:I:S:Z', 'X:I:U:Z',
        'X:I:V:Z', 'X:J:K:O', 'X:J:K:U', 'X:J:L:O', 'X:J:L:U', 'X:J:M:U',
        'X:J:N:U', 'X:J:O:U', 'X:J:O:Y', 'X:J:P:R', 'X:J:P:U', 'X:J:Q:U',
        'X:J:R:U', 'X:J:S:U', 'X:J:T:U', 'X:J:U:V', 'X:J:U:Y', 'X:K:M:T',
        'X:K:M:U', 'X:K:O:U', 'X:K:P:T', 'X:K:P:U', 'X:K:R:U', 'X:K:S:T',
        'X:K:S:U', 'X:K:S:Y', 'X:K:T:U', 'X:K:U:V', 'X:L:Q:U', 'X:M:Q:U',
        'X:M:Q:Y', 'X:M:U:V', 'X:M:U:Z', 'X:N:Q:U', 'X:N:U:Z', 'X:O:P:W',
        'X:O:P:Z', 'X:O:Q:U', 'X:O:Q:Y', 'X:O:S:Z', 'X:O:U:Z', 'X:O:Y:Z',
        'X:P:Q:U', 'X:P:Q:Y', 'X:P:T:Z', 'X:P:U:Z', 'X:Q:R:U', 'X:Q:R:Y',
        'X:Q:S:U', 'X:Q:T:U', 'X:Q:U:V', 'X:Q:U:Y', 'X:Q:U:Z', 'X:R:U:Z',
        'X:R:V:Z', 'X:S:U:Z', 'X:T:U:Z', 'X:U:V:Z', 'X:U:Y:Z', 'Y:A:B:J',
        'Y:A:B:K', 'Y:A:B:P', 'Y:A:C:D', 'Y:A:C:F', 'Y:A:C:Z', 'Y:A:D:F',
        'Y:A:D:P', 'Y:A:D:W', 'Y:A:D:Z', 'Y:A:F:H', 'Y:A:F:P', 'Y:A:F:W',
        'Y:A:G:M', 'Y:A:G:W', 'Y:A:J:W', 'Y:A:J:Z', 'Y:A:L:W', 'Y:A:M:W',
        'Y:A:N:X', 'Y:A:N:Z', 'Y:A:P:W', 'Y:A:V:Z', 'Y:A:W:X', 'Y:B:C:W',
        'Y:B:E:V', 'Y:B:F:M', 'Y:B:F:O', 'Y:B:I:J', 'Y:B:J:O', 'Y:B:J:W',
        'Y:B:K:R', 'Y:B:L:V', 'Y:B:O:P', 'Y:B:O:V', 'Y:B:O:W', 'Y:B:O:Z',
        'Y:B:R:V', 'Y:B:U:Z', 'Y:C:E:G', 'Y:C:G:N', 'Y:C:G:R', 'Y:C:H:V',
        'Y:C:I:Q', 'Y:C:J:T', 'Y:C:L:Z', 'Y:C:N:Q', 'Y:C:O:W', 'Y:C:O:Z',
        'Y:C:Q:U', 'Y:C:R:Z', 'Y:D:E:T', 'Y:D:E:W', 'Y:D:E:X', 'Y:D:E:Z',
        'Y:D:F:R', 'Y:D:G:H', 'Y:D:G:I', 'Y:D:G:N', 'Y:D:L:Z', 'Y:D:P:W',
        'Y:D:S:W', 'Y:D:T:X', 'Y:E:F:M', 'Y:E:G:W', 'Y:E:H:X', 'Y:E:J:S',
        'Y:E:J:T', 'Y:E:M:X', 'Y:E:N:Z', 'Y:E:P:V', 'Y:E:P:W', 'Y:E:Q:S',
        'Y:E:Q:T', 'Y:E:Q:W', 'Y:E:S:X', 'Y:E:V:Z', 'Y:F:H:L', 'Y:F:H:S',
        'Y:F:I:P', 'Y:F:I:W', 'Y:F:K:N', 'Y:F:K:U', 'Y:F:L:P', 'Y:F:M:O',
        'Y:F:P:R', 'Y:F:R:W', 'Y:G:I:V', 'Y:G:I:Z', 'Y:G:L:Z', 'Y:G:R:Z',
        'Y:G:T:W', 'Y:H:I:W', 'Y:H:K:W', 'Y:H:M:X', 'Y:H:O:X', 'Y:H:S:W',
        'Y:H:T:X', 'Y:I:J:O', 'Y:I:J:T', 'Y:I:J:W', 'Y:I:K:W', 'Y:I:L:Z',
        'Y:I:N:Q', 'Y:I:N:X', 'Y:I:P:V', 'Y:I:Q:U', 'Y:I:R:Z', 'Y:I:W:X',
        'Y:J:O:T', 'Y:J:O:W', 'Y:J:S:T', 'Y:K:O:T', 'Y:K:O:Z', 'Y:K:P:Z',
        'Y:K:S:W', 'Y:K:S:Z', 'Y:K:T:Z', 'Y:L:M:P', 'Y:L:P:V', 'Y:M:O:X',
        'Y:M:R:W', 'Y:M:T:W', 'Y:M:T:X', 'Y:N:P:V', 'Y:N:Q:U', 'Y:N:S:V',
        'Y:N:V:Z', 'Y:O:P:Q', 'Y:O:P:X', 'Y:O:P:Z', 'Y:O:Q:S', 'Y:O:Q:U',
        'Y:O:S:Z', 'Y:O:U:Z', 'Y:P:Q:R', 'Y:P:Q:U', 'Y:P:R:V', 'Y:P:S:W',
        'Y:P:S:Z', 'Y:P:T:V', 'Y:P:T:Z', 'Y:Q:R:T', 'Y:Q:R:W', 'Y:Q:S:U',
        'Y:Q:T:W', 'Y:S:T:Z', 'Y:T:W:X', 'Z:A:C:E', 'Z:A:E:F', 'Z:A:E:W',
        'Z:A:E:X', 'Z:A:E:Y', 'Z:A:K:Q', 'Z:A:K:X', 'Z:A:M:W', 'Z:B:C:E',
        'Z:B:D:E', 'Z:B:E:F', 'Z:B:E:J', 'Z:B:E:M', 'Z:B:E:P', 'Z:B:E:Q',
        'Z:B:E:V', 'Z:B:E:X', 'Z:B:E:Y', 'Z:B:K:Q', 'Z:B:M:W', 'Z:B:Q:U',
        'Z:C:D:E', 'Z:C:E:F', 'Z:C:E:G', 'Z:C:E:J', 'Z:C:E:K', 'Z:C:E:P',
        'Z:C:E:Q', 'Z:C:E:R', 'Z:C:E:V', 'Z:C:E:W', 'Z:C:E:X', 'Z:C:E:Y',
        'Z:C:M:W', 'Z:C:Q:U', 'Z:D:E:F', 'Z:D:E:G', 'Z:D:E:H', 'Z:D:E:J',
        'Z:D:E:K', 'Z:D:E:L', 'Z:D:E:M', 'Z:D:E:N', 'Z:D:E:O', 'Z:D:E:P',
        'Z:D:E:Q', 'Z:D:E:R', 'Z:D:E:S', 'Z:D:E:U', 'Z:D:E:W', 'Z:D:E:X',
        'Z:D:E:Y', 'Z:D:Q:U', 'Z:E:F:G', 'Z:E:F:H', 'Z:E:F:J', 'Z:E:F:K',
        'Z:E:F:L', 'Z:E:F:M', 'Z:E:F:N', 'Z:E:F:O', 'Z:E:F:P', 'Z:E:F:Q',
        'Z:E:F:S', 'Z:E:F:U', 'Z:E:F:V', 'Z:E:F:W', 'Z:E:F:X', 'Z:E:F:Y',
        'Z:E:G:J', 'Z:E:G:L', 'Z:E:G:M', 'Z:E:G:P', 'Z:E:G:Q', 'Z:E:G:S',
        'Z:E:G:V', 'Z:E:G:W', 'Z:E:G:X', 'Z:E:G:Y', 'Z:E:H:J', 'Z:E:H:P',
        'Z:E:H:Q', 'Z:E:H:X', 'Z:E:H:Y', 'Z:E:I:J', 'Z:E:I:X', 'Z:E:I:Y',
        'Z:E:J:K', 'Z:E:J:L', 'Z:E:J:M', 'Z:E:J:N', 'Z:E:J:O', 'Z:E:J:P',
        'Z:E:J:Q', 'Z:E:J:R', 'Z:E:J:S', 'Z:E:J:T', 'Z:E:J:U', 'Z:E:J:V',
        'Z:E:J:X', 'Z:E:J:Y', 'Z:E:K:M', 'Z:E:K:Q', 'Z:E:K:W', 'Z:E:K:X',
        'Z:E:K:Y', 'Z:E:L:Q', 'Z:E:L:W', 'Z:E:L:X', 'Z:E:L:Y', 'Z:E:M:N',
        'Z:E:M:P', 'Z:E:M:Q', 'Z:E:M:R', 'Z:E:M:V', 'Z:E:M:W', 'Z:E:M:X',
        'Z:E:M:Y', 'Z:E:N:Q', 'Z:E:N:W', 'Z:E:N:X', 'Z:E:N:Y', 'Z:E:O:Q',
        'Z:E:O:X', 'Z:E:O:Y', 'Z:E:P:Q', 'Z:E:P:U', 'Z:E:P:V', 'Z:E:P:W',
        'Z:E:P:X', 'Z:E:P:Y', 'Z:E:Q:S', 'Z:E:Q:V', 'Z:E:Q:W', 'Z:E:Q:X',
        'Z:E:Q:Y', 'Z:E:R:W', 'Z:E:R:X', 'Z:E:R:Y', 'Z:E:S:X', 'Z:E:S:Y',
        'Z:E:T:X', 'Z:E:T:Y', 'Z:E:U:V', 'Z:E:U:W', 'Z:E:U:X', 'Z:E:U:Y',
        'Z:E:V:W', 'Z:E:V:X', 'Z:E:V:Y', 'Z:E:X:Y', 'Z:F:Q:U', 'Z:G:Q:U',
        'Z:G:U:W', 'Z:H:Q:U', 'Z:I:V:W', 'Z:J:N:Y', 'Z:J:O:Y', 'Z:J:Q:U',
        'Z:K:L:X', 'Z:K:M:Q', 'Z:K:N:X', 'Z:K:O:Q', 'Z:K:O:X', 'Z:K:Q:R',
        'Z:K:Q:U', 'Z:L:Q:U', 'Z:M:Q:U', 'Z:N:Q:U', 'Z:N:V:W', 'Z:O:Q:U',
        'Z:O:V:Y', 'Z:P:Q:U', 'Z:Q:R:W', 'Z:Q:T:W', 'Z:Q:U:V', 'Z:Q:U:X',
        'Z:Q:U:Y', 'Z:R:V:W', 'Z:T:V:W',
    ];

    /**
     * Doublons de contenu entre pages SOEURS du meme suffixe (D-045) : regroupement par
     * (suffixe, count), verification par empreinte. 2 319 cles trouvees (perdantes,
     * canonicalisees vers la cle gagnante la plus petite alphabetiquement) -- voir
     * docs/DECISIONS.md D-045.
     *
     * @var list<string>
     */
    private const SIBLING_DUPLICATE_KEYS = [
        'A:C:U:W', 'A:D:H:W', 'A:D:K:Z', 'A:D:S:W', 'A:E:M:W', 'A:F:J:L',
        'A:F:J:M', 'A:F:M:Z', 'A:F:O:Z', 'A:F:U:Z', 'A:G:K:Z', 'A:G:P:Q',
        'A:H:J:L', 'A:H:K:Z', 'A:H:L:Q', 'A:H:P:W', 'A:I:M:W', 'A:J:K:L',
        'A:J:K:M', 'A:J:K:U', 'A:J:L:Y', 'A:J:O:Z', 'A:J:Q:T', 'A:J:R:X',
        'A:J:S:X', 'A:J:T:X', 'A:J:T:Y', 'A:J:U:X', 'A:J:U:Z', 'A:K:M:Q',
        'A:K:O:X', 'A:K:Q:R', 'A:K:V:Z', 'A:K:W:Y', 'A:L:V:Z', 'A:M:X:Y',
        'A:N:P:W', 'A:N:Q:Z', 'A:N:V:X', 'A:O:P:W', 'A:O:V:X', 'A:P:Q:X',
        'A:P:Q:Y', 'A:P:U:W', 'A:P:U:Z', 'A:Q:T:X', 'A:R:V:Z', 'A:R:W:Y',
        'A:R:W:Z', 'A:U:V:X', 'A:W:Y:Z', 'B:A:C:T', 'B:A:D:M', 'B:A:D:P',
        'B:A:H:T', 'B:A:I:K', 'B:A:K:O', 'B:A:K:T', 'B:A:K:U', 'B:A:L:N',
        'B:A:M:P', 'B:A:N:T', 'B:A:O:P', 'B:A:O:S', 'B:A:P:U', 'B:A:R:T',
        'B:A:S:T', 'B:A:S:U', 'B:C:D:L', 'B:C:D:O', 'B:C:D:R', 'B:C:D:U',
        'B:C:E:M', 'B:C:E:U', 'B:C:G:I', 'B:C:H:L', 'B:C:H:T', 'B:C:H:U',
        'B:C:I:U', 'B:C:L:S', 'B:C:M:N', 'B:C:M:P', 'B:C:M:S', 'B:C:M:T',
        'B:C:M:U', 'B:C:N:O', 'B:C:N:T', 'B:C:O:P', 'B:C:O:S', 'B:C:O:T',
        'B:C:O:U', 'B:C:P:R', 'B:C:P:U', 'B:C:R:T', 'B:C:S:T', 'B:D:E:I',
        'B:D:E:L', 'B:D:I:M', 'B:D:L:M', 'B:D:L:O', 'B:D:L:R', 'B:D:L:U',
        'B:D:M:P', 'B:D:M:R', 'B:D:O:P', 'B:D:O:R', 'B:D:P:R', 'B:D:R:U',
        'B:E:G:L', 'B:E:G:U', 'B:E:H:I', 'B:E:H:M', 'B:E:H:O', 'B:E:H:R',
        'B:E:H:T', 'B:E:I:K', 'B:E:I:N', 'B:E:I:O', 'B:E:I:T', 'B:E:K:T',
        'B:E:K:U', 'B:E:L:M', 'B:E:L:N', 'B:E:L:P', 'B:E:L:U', 'B:E:M:P',
        'B:E:M:R', 'B:E:N:T', 'B:E:N:U', 'B:E:P:S', 'B:E:P:U', 'B:E:S:U',
        'B:F:L:O', 'B:G:H:I', 'B:G:H:L', 'B:G:H:U', 'B:G:I:L', 'B:H:I:L',
        'B:H:I:R', 'B:H:I:T', 'B:H:I:U', 'B:H:L:R', 'B:H:L:U', 'B:H:M:S',
        'B:H:M:T', 'B:H:O:R', 'B:H:O:S', 'B:H:O:T', 'B:H:R:T', 'B:H:R:U',
        'B:H:T:U', 'B:I:L:M', 'B:I:L:N', 'B:I:M:O', 'B:I:M:P', 'B:I:M:U',
        'B:I:O:P', 'B:I:O:R', 'B:I:O:S', 'B:I:P:R', 'B:I:P:T', 'B:I:R:S',
        'B:I:R:T', 'B:L:M:N', 'B:L:N:O', 'B:L:N:T', 'B:L:P:T', 'B:L:R:S',
        'B:M:N:U', 'B:M:O:R', 'B:M:P:R', 'B:M:P:S', 'B:M:P:T', 'B:M:R:S',
        'B:M:R:T', 'B:M:S:T', 'B:M:S:U', 'B:N:O:U', 'B:N:S:T', 'B:N:S:U',
        'B:O:R:T', 'B:P:R:T', 'B:P:S:T', 'B:R:S:T', 'C:A:O:Y', 'C:A:R:Y',
        'C:A:T:Y', 'C:B:D:S', 'C:B:G:S', 'C:B:H:N', 'C:B:H:O', 'C:B:H:P',
        'C:B:H:T', 'C:B:H:U', 'C:B:K:O', 'C:B:N:Z', 'C:B:O:Z', 'C:B:T:Y',
        'C:B:U:V', 'C:D:E:J', 'C:D:E:Z', 'C:D:F:N', 'C:D:G:I', 'C:D:G:N',
        'C:D:G:S', 'C:D:G:T', 'C:D:G:U', 'C:D:G:Y', 'C:D:H:P', 'C:D:I:M',
        'C:D:I:P', 'C:D:I:Z', 'C:D:J:N', 'C:D:J:R', 'C:D:L:S', 'C:D:M:N',
        'C:D:M:S', 'C:D:M:Y', 'C:D:M:Z', 'C:D:N:V', 'C:D:N:Z', 'C:D:P:T',
        'C:D:P:U', 'C:D:R:Z', 'C:D:S:V', 'C:D:T:Y', 'C:E:F:S', 'C:E:H:M',
        'C:E:I:Y', 'C:E:J:N', 'C:E:J:R', 'C:E:J:T', 'C:E:L:Y', 'C:E:R:Y',
        'C:E:R:Z', 'C:E:T:Y', 'C:E:U:V', 'C:F:I:P', 'C:F:L:P', 'C:F:L:S',
        'C:F:N:S', 'C:F:P:R', 'C:F:P:S', 'C:F:P:U', 'C:G:I:M', 'C:G:I:O',
        'C:G:I:S', 'C:G:I:Y', 'C:G:I:Z', 'C:G:L:O', 'C:G:L:S', 'C:G:L:T',
        'C:G:M:S', 'C:G:M:T', 'C:G:M:Y', 'C:G:M:Z', 'C:G:N:S', 'C:G:N:T',
        'C:G:N:Y', 'C:G:N:Z', 'C:G:O:T', 'C:G:O:U', 'C:G:O:Y', 'C:G:R:T',
        'C:G:R:U', 'C:G:S:T', 'C:G:S:U', 'C:G:S:Y', 'C:G:T:U', 'C:G:T:Y',
        'C:G:U:Z', 'C:H:I:P', 'C:H:K:R', 'C:H:L:N', 'C:H:L:U', 'C:H:M:N',
        'C:H:M:O', 'C:H:M:T', 'C:H:M:U', 'C:H:N:P', 'C:H:N:T', 'C:H:N:U',
        'C:H:O:S', 'C:H:P:R', 'C:H:S:T', 'C:I:L:V', 'C:I:L:Z', 'C:I:M:Y',
        'C:I:O:Z', 'C:I:S:V', 'C:I:T:V', 'C:J:L:T', 'C:J:M:T', 'C:J:M:U',
        'C:J:N:T', 'C:J:N:U', 'C:J:T:U', 'C:K:L:N', 'C:K:N:R', 'C:L:M:R',
        'C:L:M:Y', 'C:L:M:Z', 'C:L:N:Y', 'C:L:N:Z', 'C:L:O:Z', 'C:L:P:Y',
        'C:L:R:Y', 'C:L:S:V', 'C:L:T:V', 'C:M:N:P', 'C:M:N:Z', 'C:M:O:Y',
        'C:M:O:Z', 'C:M:P:R', 'C:M:P:S', 'C:M:P:U', 'C:M:R:U', 'C:M:S:Y',
        'C:M:T:Y', 'C:N:O:Z', 'C:N:P:Y', 'C:N:R:V', 'C:N:R:Y', 'C:N:T:V',
        'C:N:U:V', 'C:O:R:V', 'C:O:U:V', 'C:P:R:V', 'C:R:S:V', 'C:R:S:Y',
        'C:R:T:Y', 'C:S:T:V', 'C:S:T:Y', 'C:S:U:V', 'D:B:E:W', 'D:B:F:T',
        'D:B:G:K', 'D:B:I:J', 'D:B:I:K', 'D:B:J:L', 'D:B:J:U', 'D:B:K:N',
        'D:B:K:U', 'D:B:K:W', 'D:B:O:P', 'D:B:P:R', 'D:B:S:W', 'D:B:T:Y',
        'D:B:T:Z', 'D:C:G:K', 'D:C:I:K', 'D:C:K:N', 'D:C:K:U', 'D:C:M:Q',
        'D:C:Q:R', 'D:C:Q:U', 'D:C:T:Z', 'D:E:G:K', 'D:E:H:Z', 'D:E:I:J',
        'D:E:J:M', 'D:E:J:Q', 'D:E:J:R', 'D:E:J:U', 'D:E:K:L', 'D:E:K:O',
        'D:E:K:R', 'D:E:L:Q', 'D:E:N:X', 'D:E:Q:S', 'D:E:R:X', 'D:F:H:L',
        'D:F:H:P', 'D:F:J:L', 'D:F:J:R', 'D:F:M:P', 'D:F:P:Y', 'D:F:T:Y',
        'D:G:H:Y', 'D:G:I:K', 'D:G:J:N', 'D:G:J:U', 'D:G:K:L', 'D:G:K:O',
        'D:G:K:R', 'D:G:K:U', 'D:G:N:W', 'D:G:O:W', 'D:G:O:Z', 'D:G:T:W',
        'D:G:U:Z', 'D:H:I:Z', 'D:H:J:U', 'D:H:O:V', 'D:H:S:V', 'D:H:T:V',
        'D:I:J:R', 'D:I:J:T', 'D:I:K:L', 'D:I:K:O', 'D:I:M:V', 'D:I:M:Z',
        'D:I:N:W', 'D:I:N:X', 'D:I:O:X', 'D:I:R:X', 'D:I:T:Z', 'D:J:L:O',
        'D:J:L:R', 'D:J:M:Q', 'D:J:O:T', 'D:J:R:T', 'D:K:L:N', 'D:K:L:O',
        'D:K:N:O', 'D:K:N:U', 'D:K:O:S', 'D:K:O:U', 'D:K:O:W', 'D:K:R:S',
        'D:K:R:U', 'D:K:R:W', 'D:K:S:U', 'D:L:M:V', 'D:L:N:W', 'D:L:N:X',
        'D:L:O:Q', 'D:L:O:W', 'D:L:P:Z', 'D:L:Q:S', 'D:L:R:X', 'D:L:T:W',
        'D:L:T:X', 'D:L:V:Y', 'D:M:N:V', 'D:M:Q:S', 'D:M:R:Z', 'D:M:U:V',
        'D:M:U:Z', 'D:N:O:Q', 'D:N:O:X', 'D:N:Q:S', 'D:N:R:W', 'D:N:S:W',
        'D:N:T:W', 'D:N:U:Z', 'D:O:Q:S', 'D:O:R:X', 'D:O:S:W', 'D:O:T:W',
        'D:O:T:X', 'D:P:Q:R', 'D:P:T:V', 'D:P:T:Y', 'D:P:T:Z', 'D:P:U:Z',
        'D:P:V:Y', 'D:R:T:W', 'D:R:T:X', 'D:S:T:W', 'D:T:U:V', 'D:T:U:Y',
        'E:D:J:Z', 'E:F:W:Z', 'E:I:K:X', 'E:J:P:Z', 'E:K:U:X', 'E:K:X:Y',
        'E:M:W:X', 'E:P:Q:W', 'E:P:W:Z', 'E:S:X:Z', 'E:U:W:X', 'E:X:Y:Z',
        'F:A:J:L', 'F:A:K:U', 'F:A:Q:U', 'F:A:T:Y', 'F:A:U:W', 'F:B:E:M',
        'F:B:G:U', 'F:B:H:R', 'F:B:J:P', 'F:B:J:T', 'F:B:L:P', 'F:B:M:U',
        'F:B:P:S', 'F:B:R:V', 'F:B:R:Z', 'F:B:U:Z', 'F:C:H:Y', 'F:C:I:X',
        'F:C:O:Q', 'F:C:Q:S', 'F:C:S:Y', 'F:D:H:U', 'F:D:J:O', 'F:D:J:S',
        'F:D:P:Y', 'F:D:R:Y', 'F:D:U:V', 'F:E:H:W', 'F:E:K:L', 'F:E:K:S',
        'F:E:K:W', 'F:E:O:W', 'F:E:Q:T', 'F:E:R:W', 'F:E:T:W', 'F:E:X:Y',
        'F:G:H:I', 'F:G:H:K', 'F:G:H:M', 'F:G:H:T', 'F:G:H:U', 'F:G:M:T',
        'F:G:O:V', 'F:G:T:V', 'F:H:K:L', 'F:H:K:O', 'F:H:K:P', 'F:H:K:U',
        'F:H:K:W', 'F:H:L:M', 'F:H:L:T', 'F:H:R:X', 'F:H:U:X', 'F:I:K:U',
        'F:I:L:Y', 'F:I:O:W', 'F:I:T:W', 'F:I:U:W', 'F:J:L:P', 'F:J:L:T',
        'F:J:L:U', 'F:J:P:T', 'F:J:P:U', 'F:K:L:P', 'F:K:O:S', 'F:K:O:W',
        'F:K:P:R', 'F:K:P:S', 'F:K:P:U', 'F:K:S:U', 'F:K:U:W', 'F:L:M:X',
        'F:L:O:Q', 'F:L:P:Y', 'F:L:S:Y', 'F:L:T:W', 'F:L:T:Y', 'F:M:N:V',
        'F:M:S:V', 'F:M:T:V', 'F:M:T:X', 'F:O:Q:T', 'F:O:R:W', 'F:O:R:Z',
        'F:O:T:Y', 'F:O:U:W', 'F:P:R:Y', 'F:P:S:Y', 'F:P:T:Y', 'F:P:X:Y',
        'F:R:T:W', 'F:R:T:Y', 'F:R:U:W', 'F:R:U:Z', 'F:R:X:Y', 'F:S:T:Y',
        'G:A:J:R', 'G:A:L:Y', 'G:A:N:Q', 'G:A:N:X', 'G:A:O:W', 'G:A:O:X',
        'G:A:S:X', 'G:A:S:Y', 'G:A:U:X', 'G:B:C:P', 'G:B:D:S', 'G:B:D:W',
        'G:B:E:J', 'G:B:F:U', 'G:B:F:X', 'G:B:H:J', 'G:B:I:J', 'G:B:J:L',
        'G:B:J:O', 'G:B:J:R', 'G:B:J:S', 'G:B:K:M', 'G:B:K:P', 'G:B:K:T',
        'G:B:L:P', 'G:B:N:P', 'G:B:N:V', 'G:B:N:W', 'G:B:N:X', 'G:B:N:Y',
        'G:B:O:V', 'G:B:P:R', 'G:B:P:S', 'G:B:R:V', 'G:B:R:Y', 'G:B:S:V',
        'G:B:S:W', 'G:B:S:X', 'G:B:S:Y', 'G:B:T:V', 'G:B:T:X', 'G:B:T:Y',
        'G:B:U:Y', 'G:C:D:H', 'G:C:D:N', 'G:C:D:U', 'G:C:E:X', 'G:C:F:K',
        'G:C:F:P', 'G:C:F:S', 'G:C:F:W', 'G:C:H:W', 'G:C:K:L', 'G:C:K:V',
        'G:C:L:V', 'G:C:L:W', 'G:C:M:S', 'G:C:N:Y', 'G:C:O:V', 'G:C:O:W',
        'G:C:P:T', 'G:C:R:W', 'G:C:R:Y', 'G:C:S:W', 'G:C:S:X', 'G:C:T:W',
        'G:C:U:Y', 'G:D:E:F', 'G:D:E:H', 'G:D:E:T', 'G:D:F:M', 'G:D:F:O',
        'G:D:F:U', 'G:D:F:W', 'G:D:H:M', 'G:D:H:N', 'G:D:H:R', 'G:D:H:S',
        'G:D:I:J', 'G:D:J:R', 'G:D:K:M', 'G:D:K:T', 'G:D:L:W', 'G:D:L:Y',
        'G:D:N:P', 'G:D:O:Y', 'G:D:R:W', 'G:D:R:Y', 'G:D:U:W', 'G:D:U:Y',
        'G:E:F:O', 'G:E:H:J', 'G:E:H:K', 'G:E:J:N', 'G:E:J:O', 'G:E:J:R',
        'G:E:J:S', 'G:E:K:M', 'G:E:K:V', 'G:E:M:P', 'G:E:O:X', 'G:E:R:Z',
        'G:E:S:V', 'G:E:S:Y', 'G:E:T:Y', 'G:F:H:U', 'G:F:I:P', 'G:F:K:O',
        'G:F:K:P', 'G:F:K:S', 'G:F:K:U', 'G:F:L:S', 'G:F:M:O', 'G:F:N:X',
        'G:F:O:X', 'G:F:P:U', 'G:F:R:S', 'G:F:R:W', 'G:F:U:W', 'G:F:U:X',
        'G:H:I:J', 'G:H:J:R', 'G:H:J:S', 'G:H:K:M', 'G:H:K:R', 'G:H:K:T',
        'G:H:K:V', 'G:H:L:W', 'G:H:S:W', 'G:H:T:V', 'G:H:T:W', 'G:H:U:W',
        'G:I:J:P', 'G:I:O:V', 'G:I:O:X', 'G:J:L:O', 'G:J:L:R', 'G:J:L:U',
        'G:J:M:O', 'G:J:M:P', 'G:J:M:U', 'G:J:N:P', 'G:J:N:U', 'G:J:P:U',
        'G:J:R:U', 'G:K:L:R', 'G:K:L:V', 'G:K:O:P', 'G:K:O:V', 'G:K:P:S',
        'G:K:P:U', 'G:K:R:V', 'G:K:S:V', 'G:K:T:V', 'G:L:S:W', 'G:L:S:Y',
        'G:L:T:V', 'G:L:T:Y', 'G:L:U:W', 'G:N:O:X', 'G:N:O:Y', 'G:N:Q:U',
        'G:N:R:Y', 'G:N:U:X', 'G:N:U:Z', 'G:O:R:V', 'G:O:S:W', 'G:O:S:X',
        'G:O:S:Y', 'G:O:T:X', 'G:O:T:Y', 'G:O:U:W', 'G:O:U:Y', 'G:P:S:U',
        'G:R:S:V', 'G:R:S:W', 'G:R:S:Y', 'G:R:T:V', 'G:R:T:Y', 'G:R:T:Z',
        'G:R:U:W', 'G:S:T:X', 'G:T:U:W', 'G:T:U:X', 'H:A:F:U', 'H:A:I:Q',
        'H:A:K:Y', 'H:A:N:W', 'H:A:O:Y', 'H:A:R:V', 'H:A:S:W', 'H:A:S:Y',
        'H:A:T:V', 'H:A:T:Y', 'H:B:E:M', 'H:B:E:N', 'H:B:E:V', 'H:B:G:L',
        'H:B:G:U', 'H:B:I:K', 'H:B:K:M', 'H:B:K:U', 'H:B:L:M', 'H:B:L:R',
        'H:B:M:O', 'H:B:M:R', 'H:B:M:T', 'H:B:M:U', 'H:B:N:O', 'H:B:N:V',
        'H:B:R:V', 'H:B:T:V', 'H:B:U:V', 'H:C:D:N', 'H:C:D:W', 'H:C:D:Z',
        'H:C:G:O', 'H:C:G:S', 'H:C:G:T', 'H:C:G:U', 'H:C:I:Q', 'H:C:I:V',
        'H:C:I:Y', 'H:C:N:V', 'H:C:O:V', 'H:C:R:V', 'H:C:T:Z', 'H:C:U:V',
        'H:D:E:R', 'H:D:E:Z', 'H:D:G:O', 'H:D:G:R', 'H:D:G:S', 'H:D:I:L',
        'H:D:I:N', 'H:D:I:W', 'H:D:J:R', 'H:D:L:P', 'H:D:L:T', 'H:D:M:Z',
        'H:D:N:R', 'H:D:N:S', 'H:D:N:W', 'H:D:O:P', 'H:D:O:T', 'H:D:O:Z',
        'H:D:R:Z', 'H:D:S:W', 'H:E:F:L', 'H:E:F:N', 'H:E:F:P', 'H:E:I:U',
        'H:E:K:Y', 'H:E:N:P', 'H:E:N:S', 'H:E:O:Z', 'H:E:S:V', 'H:E:T:Z',
        'H:E:U:Z', 'H:F:I:U', 'H:F:K:O', 'H:F:K:S', 'H:F:K:T', 'H:F:L:N',
        'H:F:L:P', 'H:F:L:T', 'H:F:N:P', 'H:F:N:R', 'H:F:N:U', 'H:F:O:P',
        'H:F:O:R', 'H:F:O:U', 'H:F:R:T', 'H:F:R:U', 'H:G:N:U', 'H:I:K:N',
        'H:I:L:V', 'H:I:M:P', 'H:I:M:U', 'H:I:N:U', 'H:I:N:V', 'H:I:O:Z',
        'H:I:P:Z', 'H:I:R:Z', 'H:I:S:U', 'H:I:S:Y', 'H:I:U:V', 'H:I:V:Z',
        'H:I:W:Z', 'H:K:L:M', 'H:K:L:P', 'H:K:L:T', 'H:K:M:N', 'H:K:M:O',
        'H:K:M:T', 'H:K:N:O', 'H:K:N:S', 'H:K:N:T', 'H:K:N:U', 'H:K:O:P',
        'H:K:O:Y', 'H:K:P:S', 'H:K:P:T', 'H:K:U:Y', 'H:L:N:O', 'H:L:N:V',
        'H:L:O:V', 'H:L:O:Y', 'H:L:R:V', 'H:L:S:Y', 'H:L:T:Y', 'H:L:U:V',
        'H:M:N:T', 'H:M:N:V', 'H:M:P:T', 'H:M:P:Z', 'H:M:R:T', 'H:M:R:V',
        'H:M:S:U', 'H:M:U:V', 'H:M:U:Z', 'H:N:O:S', 'H:N:O:U', 'H:N:O:V',
        'H:N:O:W', 'H:N:R:S', 'H:N:R:V', 'H:N:S:W', 'H:N:T:V', 'H:O:P:R',
        'H:O:S:W', 'H:O:U:Z', 'H:P:R:U', 'H:R:S:Y', 'H:R:T:Y', 'H:R:T:Z',
        'H:R:U:V', 'H:R:U:Y', 'H:R:U:Z', 'H:S:U:V', 'H:T:U:V', 'H:T:U:Y',
        'H:T:U:Z', 'H:T:V:Z', 'H:U:V:Z', 'I:B:M:W', 'I:B:P:Q', 'I:C:M:W',
        'I:C:N:W', 'I:D:H:W', 'I:D:J:Y', 'I:D:S:W', 'I:E:M:W', 'I:F:J:R',
        'I:F:T:Z', 'I:G:K:P', 'I:G:K:U', 'I:G:P:Q', 'I:H:J:P', 'I:H:L:Q',
        'I:H:N:W', 'I:H:T:W', 'I:H:Y:Z', 'I:J:N:X', 'I:J:Q:T', 'I:J:R:X',
        'I:J:R:Z', 'I:J:S:X', 'I:J:T:X', 'I:J:U:X', 'I:J:U:Z', 'I:K:N:Z',
        'I:K:R:X', 'I:L:Y:Z', 'I:M:P:Z', 'I:M:R:W', 'I:N:V:X', 'I:P:Q:X',
        'I:P:Q:Y', 'I:P:R:W', 'I:Q:T:X', 'I:R:U:W', 'I:R:W:Z', 'I:T:W:Z',
        'I:U:V:X', 'I:U:Y:Z', 'J:A:D:U', 'J:D:R:U', 'K:A:C:G', 'K:A:G:I',
        'K:A:G:L', 'K:A:G:R', 'K:A:G:S', 'K:A:G:T', 'K:A:I:Z', 'K:A:J:R',
        'K:A:J:S', 'K:A:L:Y', 'K:A:M:Y', 'K:A:N:V', 'K:A:O:V', 'K:A:R:V',
        'K:B:C:G', 'K:B:C:Z', 'K:B:D:F', 'K:B:D:T', 'K:B:D:U', 'K:B:E:J',
        'K:B:F:S', 'K:B:G:L', 'K:B:G:M', 'K:B:G:N', 'K:B:G:R', 'K:B:G:T',
        'K:B:I:J', 'K:B:J:R', 'K:B:L:N', 'K:B:L:T', 'K:B:M:R', 'K:B:P:U',
        'K:B:P:Y', 'K:B:R:Y', 'K:B:S:U', 'K:B:T:Z', 'K:B:U:Y', 'K:C:E:Q',
        'K:C:E:W', 'K:C:E:Z', 'K:C:F:S', 'K:C:G:L', 'K:C:G:N', 'K:C:G:R',
        'K:C:G:S', 'K:C:G:T', 'K:C:G:U', 'K:C:H:R', 'K:C:I:Z', 'K:C:J:L',
        'K:C:J:O', 'K:C:J:S', 'K:C:J:T', 'K:C:N:Y', 'K:C:O:V', 'K:C:O:W',
        'K:C:P:W', 'K:C:Q:R', 'K:C:Q:T', 'K:C:R:Y', 'K:C:S:Y', 'K:C:T:Y',
        'K:C:T:Z', 'K:C:U:Y', 'K:C:U:Z', 'K:D:E:F', 'K:D:E:M', 'K:D:E:T',
        'K:D:F:I', 'K:D:F:T', 'K:D:H:M', 'K:D:H:T', 'K:D:I:J', 'K:D:I:T',
        'K:D:J:N', 'K:D:J:S', 'K:D:J:T', 'K:D:M:N', 'K:D:M:R', 'K:D:M:S',
        'K:D:M:T', 'K:D:P:R', 'K:D:P:S', 'K:D:R:T', 'K:E:F:L', 'K:E:F:U',
        'K:E:G:M', 'K:E:G:P', 'K:E:G:S', 'K:E:I:J', 'K:E:J:L', 'K:E:M:Y',
        'K:E:N:Y', 'K:E:O:W', 'K:E:P:V', 'K:E:P:Y', 'K:E:R:Y', 'K:E:T:W',
        'K:E:T:Y', 'K:E:U:Y', 'K:F:H:S', 'K:F:H:T', 'K:F:I:R', 'K:F:I:U',
        'K:F:L:N', 'K:F:L:T', 'K:F:N:R', 'K:F:N:T', 'K:F:O:T', 'K:F:S:T',
        'K:F:S:U', 'K:F:T:U', 'K:G:I:M', 'K:G:I:S', 'K:G:L:N', 'K:G:L:P',
        'K:G:L:R', 'K:G:L:S', 'K:G:L:T', 'K:G:L:V', 'K:G:M:O', 'K:G:M:S',
        'K:G:N:P', 'K:G:N:S', 'K:G:N:T', 'K:G:N:V', 'K:G:O:T', 'K:G:O:U',
        'K:G:O:V', 'K:G:P:R', 'K:G:P:S', 'K:G:P:V', 'K:G:R:S', 'K:G:R:V',
        'K:G:S:T', 'K:G:T:U', 'K:H:I:Z', 'K:H:L:R', 'K:H:L:V', 'K:H:N:P',
        'K:H:N:R', 'K:H:N:V', 'K:H:O:V', 'K:H:P:S', 'K:H:P:W', 'K:H:R:U',
        'K:H:R:W', 'K:H:T:Y', 'K:H:T:Z', 'K:H:U:Z', 'K:I:J:L', 'K:I:J:S',
        'K:I:L:V', 'K:I:L:Y', 'K:I:M:Y', 'K:I:N:Q', 'K:I:O:V', 'K:I:Q:R',
        'K:I:Q:T', 'K:I:S:Y', 'K:I:T:Y', 'K:I:T:Z', 'K:I:U:Y', 'K:J:L:R',
        'K:J:N:S', 'K:J:O:S', 'K:J:O:T', 'K:J:O:U', 'K:J:S:T', 'K:L:M:P',
        'K:L:M:S', 'K:L:P:Y', 'K:L:R:U', 'K:M:N:P', 'K:M:N:W', 'K:M:P:R',
        'K:M:P:U', 'K:M:R:W', 'K:M:T:Y', 'K:M:U:Y', 'K:M:U:Z', 'K:N:P:V',
        'K:N:P:Y', 'K:N:S:Y', 'K:N:T:Z', 'K:N:U:Y', 'K:O:P:V', 'K:P:R:V',
        'K:P:R:Y', 'K:P:T:W', 'K:R:S:Y', 'K:S:T:Y', 'K:T:U:Z', 'L:A:I:W',
        'L:A:O:W', 'L:B:D:W', 'L:B:F:I', 'L:B:F:R', 'L:B:F:W', 'L:B:G:P',
        'L:B:H:K', 'L:B:J:O', 'L:B:J:T', 'L:B:J:U', 'L:B:K:N', 'L:B:K:S',
        'L:B:K:U', 'L:B:K:Y', 'L:B:O:W', 'L:B:P:Z', 'L:B:R:W', 'L:B:S:X',
        'L:B:U:Y', 'L:C:I:W', 'L:C:O:W', 'L:C:P:Q', 'L:C:U:Z', 'L:C:Y:Z',
        'L:D:E:W', 'L:D:F:W', 'L:D:H:V', 'L:D:I:W', 'L:D:I:Z', 'L:D:K:O',
        'L:D:K:T', 'L:D:K:V', 'L:D:O:W', 'L:D:P:Q', 'L:D:T:Z', 'L:E:I:W',
        'L:E:J:S', 'L:E:J:X', 'L:E:O:W', 'L:E:P:Z', 'L:F:G:P', 'L:F:G:T',
        'L:F:H:S', 'L:F:H:T', 'L:F:I:W', 'L:F:K:N', 'L:F:K:T', 'L:F:M:X',
        'L:F:P:V', 'L:F:R:W', 'L:F:T:Y', 'L:F:U:X', 'L:G:J:O', 'L:G:J:P',
        'L:G:J:R', 'L:G:J:S', 'L:G:J:T', 'L:G:J:X', 'L:G:K:N', 'L:G:K:O',
        'L:G:K:S', 'L:G:K:T', 'L:G:O:Z', 'L:G:R:W', 'L:G:R:Z', 'L:G:T:X',
        'L:G:U:X', 'L:H:P:Z', 'L:H:T:Z', 'L:H:Y:Z', 'L:I:K:V', 'L:I:M:Q',
        'L:I:P:Z', 'L:I:Y:Z', 'L:J:K:O', 'L:J:K:R', 'L:J:M:O', 'L:J:M:R',
        'L:J:M:U', 'L:J:N:P', 'L:J:N:X', 'L:J:O:S', 'L:J:P:S', 'L:J:P:X',
        'L:J:R:S', 'L:J:S:T', 'L:J:T:V', 'L:K:N:U', 'L:K:P:U', 'L:K:R:Y',
        'L:K:S:T', 'L:K:T:U', 'L:K:T:V', 'L:M:O:W', 'L:M:Y:Z', 'L:N:U:Y',
        'L:N:U:Z', 'L:O:S:Z', 'L:O:V:Z', 'L:O:Y:Z', 'L:P:R:Z', 'L:Q:R:S',
        'L:R:V:Z', 'L:R:Y:Z', 'L:S:T:Z', 'L:T:V:Z', 'L:U:X:Y', 'M:A:C:Z',
        'M:A:J:O', 'M:A:J:T', 'M:A:K:R', 'M:A:K:Z', 'M:A:O:X', 'M:A:R:W',
        'M:A:T:Z', 'M:A:Y:Z', 'M:B:C:K', 'M:B:C:Z', 'M:B:E:F', 'M:B:F:N',
        'M:B:G:N', 'M:B:G:O', 'M:B:G:R', 'M:B:G:S', 'M:B:K:L', 'M:B:K:U',
        'M:B:K:Z', 'M:B:L:P', 'M:B:L:Z', 'M:B:N:S', 'M:B:N:Y', 'M:B:P:R',
        'M:B:P:Y', 'M:B:R:Z', 'M:B:T:V', 'M:B:T:Z', 'M:C:H:K', 'M:C:H:Z',
        'M:C:K:L', 'M:C:K:R', 'M:C:K:S', 'M:C:K:T', 'M:C:K:U', 'M:C:L:W',
        'M:C:L:Z', 'M:C:N:W', 'M:C:O:Z', 'M:C:P:V', 'M:C:R:V', 'M:C:R:W',
        'M:C:R:Z', 'M:C:T:Z', 'M:C:U:W', 'M:D:E:J', 'M:D:F:S', 'M:D:G:N',
        'M:D:G:R', 'M:D:G:U', 'M:D:H:J', 'M:D:I:Z', 'M:D:J:L', 'M:D:J:O',
        'M:D:J:T', 'M:D:J:U', 'M:D:N:X', 'M:D:O:V', 'M:D:P:V', 'M:D:P:Z',
        'M:D:R:Z', 'M:D:U:Z', 'M:E:H:J', 'M:E:H:K', 'M:E:I:W', 'M:E:J:T',
        'M:E:K:R', 'M:E:K:Z', 'M:E:L:Q', 'M:E:L:W', 'M:E:L:Z', 'M:E:N:Q',
        'M:E:N:W', 'M:E:O:X', 'M:E:Q:T', 'M:E:R:W', 'M:E:T:Z', 'M:E:U:W',
        'M:E:Y:Z', 'M:F:G:L', 'M:F:G:R', 'M:F:H:R', 'M:F:H:T', 'M:F:I:V',
        'M:F:L:P', 'M:F:L:S', 'M:F:O:P', 'M:F:O:S', 'M:F:P:Y', 'M:F:S:U',
        'M:F:U:V', 'M:F:U:Y', 'M:G:H:N', 'M:G:H:T', 'M:G:H:U', 'M:G:H:Y',
        'M:G:T:Y', 'M:H:J:L', 'M:H:J:O', 'M:H:J:T', 'M:H:K:R', 'M:H:K:S',
        'M:H:K:T', 'M:H:K:U', 'M:H:K:Z', 'M:H:N:Z', 'M:H:O:X', 'M:H:R:Z',
        'M:I:L:Z', 'M:I:P:Z', 'M:I:R:W', 'M:I:T:X', 'M:J:L:R', 'M:J:N:O',
        'M:J:N:R', 'M:J:O:U', 'M:K:L:R', 'M:K:L:S', 'M:K:O:R', 'M:K:O:Z',
        'M:K:R:T', 'M:K:R:U', 'M:K:S:U', 'M:K:T:Z', 'M:K:U:Z', 'M:L:N:Q',
        'M:L:N:W', 'M:L:N:X', 'M:L:O:Z', 'M:L:P:Z', 'M:L:R:W', 'M:L:S:V',
        'M:L:T:V', 'M:L:T:Z', 'M:L:U:W', 'M:L:U:X', 'M:L:Y:Z', 'M:N:O:Z',
        'M:N:Q:T', 'M:N:R:W', 'M:N:S:Y', 'M:N:T:Z', 'M:O:P:Z', 'M:O:Q:T',
        'M:O:R:X', 'M:O:T:X', 'M:O:U:W', 'M:O:Y:Z', 'M:P:T:Z', 'M:P:U:V',
        'M:P:U:Z', 'M:P:Y:Z', 'M:Q:R:T', 'M:R:T:Z', 'N:B:K:Y', 'N:C:J:K',
        'N:D:J:Q', 'N:D:P:W', 'N:F:K:V', 'N:F:L:W', 'N:F:U:W', 'N:F:U:Z',
        'N:F:V:W', 'N:F:W:Y', 'N:F:W:Z', 'N:H:K:V', 'N:J:K:L', 'N:J:K:R',
        'N:J:K:T', 'N:J:L:X', 'N:J:R:X', 'N:J:T:Y', 'N:K:P:V', 'N:K:P:W',
        'N:K:U:Y', 'N:K:W:Y', 'N:L:Q:W', 'N:O:V:W', 'N:Q:S:W', 'N:S:V:W',
        'N:V:W:Z', 'O:B:E:Q', 'O:B:F:P', 'O:B:F:R', 'O:B:H:R', 'O:B:I:K',
        'O:B:I:P', 'O:B:I:Q', 'O:B:I:Z', 'O:B:L:Q', 'O:B:M:V', 'O:B:N:Q',
        'O:B:P:S', 'O:B:Q:R', 'O:B:R:Z', 'O:B:S:V', 'O:C:F:M', 'O:C:J:P',
        'O:C:J:Y', 'O:C:K:N', 'O:C:K:P', 'O:C:M:X', 'O:C:N:X', 'O:C:P:V',
        'O:C:Q:T', 'O:C:S:X', 'O:C:T:Z', 'O:C:U:Y', 'O:D:G:J', 'O:D:H:L',
        'O:D:H:Q', 'O:D:J:R', 'O:D:K:W', 'O:D:N:V', 'O:D:N:W', 'O:D:Q:R',
        'O:D:Q:S', 'O:D:Q:T', 'O:D:R:W', 'O:D:T:V', 'O:D:T:W', 'O:D:T:Y',
        'O:D:T:Z', 'O:D:U:Y', 'O:E:F:M', 'O:E:G:K', 'O:E:G:Y', 'O:E:I:J',
        'O:E:I:W', 'O:E:J:P', 'O:E:J:R', 'O:E:K:W', 'O:E:K:Y', 'O:E:L:X',
        'O:E:M:Y', 'O:E:N:W', 'O:E:P:Z', 'O:E:R:W', 'O:E:U:Y', 'O:F:G:U',
        'O:F:K:R', 'O:F:K:S', 'O:F:M:N', 'O:F:M:P', 'O:F:P:U', 'O:F:S:Z',
        'O:G:H:P', 'O:G:I:Y', 'O:G:J:K', 'O:G:J:N', 'O:G:J:Y', 'O:G:K:U',
        'O:G:K:Y', 'O:G:Q:R', 'O:G:S:V', 'O:G:U:Y', 'O:G:U:Z', 'O:H:I:K',
        'O:H:I:Q', 'O:H:K:N', 'O:H:K:P', 'O:H:M:Z', 'O:H:N:Z', 'O:H:Q:R',
        'O:H:Q:S', 'O:H:S:Z', 'O:I:J:K', 'O:I:J:U', 'O:I:J:Y', 'O:I:K:P',
        'O:I:K:Y', 'O:I:R:W', 'O:I:S:Y', 'O:I:T:Y', 'O:J:K:U', 'O:J:K:Y',
        'O:J:L:N', 'O:J:L:P', 'O:J:L:U', 'O:J:M:U', 'O:J:N:P', 'O:J:N:U',
        'O:J:P:U', 'O:J:P:Y', 'O:J:R:V', 'O:K:L:U', 'O:K:N:P', 'O:K:P:U',
        'O:K:R:S', 'O:K:R:Y', 'O:K:R:Z', 'O:K:T:Y', 'O:K:Y:Z', 'O:L:N:Q',
        'O:L:P:Z', 'O:L:S:X', 'O:L:U:Z', 'O:M:N:Q', 'O:M:N:X', 'O:M:Q:R',
        'O:M:R:Y', 'O:M:T:X', 'O:M:U:Y', 'O:M:V:Z', 'O:N:P:V', 'O:N:P:Y',
        'O:N:P:Z', 'O:N:Q:S', 'O:N:S:X', 'O:N:S:Z', 'O:N:T:W', 'O:N:T:X',
        'O:N:T:Y', 'O:N:U:Y', 'O:N:V:Z', 'O:P:S:X', 'O:P:U:V', 'O:P:U:Y',
        'O:P:V:Z', 'O:Q:R:S', 'O:R:S:X', 'O:R:S:Y', 'O:R:U:V', 'O:S:T:Z',
        'O:S:V:Z', 'O:T:U:Y', 'O:T:V:Z', 'P:A:B:U', 'P:A:C:I', 'P:A:D:I',
        'P:A:D:N', 'P:A:H:I', 'P:A:H:S', 'P:A:I:Y', 'P:A:J:U', 'P:A:K:L',
        'P:A:K:O', 'P:A:K:R', 'P:A:K:T', 'P:A:K:U', 'P:A:N:T', 'P:A:O:Y',
        'P:B:C:E', 'P:B:C:R', 'P:B:C:U', 'P:B:E:T', 'P:B:I:K', 'P:B:K:M',
        'P:B:K:S', 'P:B:M:R', 'P:B:O:R', 'P:B:O:U', 'P:B:S:T', 'P:B:S:U',
        'P:B:T:U', 'P:C:D:N', 'P:C:D:O', 'P:C:E:L', 'P:C:E:M', 'P:C:G:O',
        'P:C:G:S', 'P:C:H:L', 'P:C:H:M', 'P:C:H:R', 'P:C:H:U', 'P:C:I:U',
        'P:C:K:S', 'P:C:L:N', 'P:C:L:T', 'P:C:M:N', 'P:C:M:O', 'P:C:M:T',
        'P:C:N:S', 'P:C:N:Y', 'P:C:R:T', 'P:C:S:T', 'P:C:S:U', 'P:C:S:Y',
        'P:D:E:H', 'P:D:E:L', 'P:D:E:N', 'P:D:E:O', 'P:D:F:I', 'P:D:F:L',
        'P:D:F:M', 'P:D:F:O', 'P:D:F:R', 'P:D:H:N', 'P:D:H:R', 'P:D:I:M',
        'P:D:I:O', 'P:D:I:S', 'P:D:L:R', 'P:D:L:S', 'P:D:M:O', 'P:D:M:S',
        'P:D:N:O', 'P:D:N:R', 'P:D:N:U', 'P:D:R:S', 'P:D:R:T', 'P:D:R:U',
        'P:D:T:U', 'P:E:F:G', 'P:E:F:I', 'P:E:F:M', 'P:E:F:T', 'P:E:G:L',
        'P:E:G:O', 'P:E:H:K', 'P:E:H:L', 'P:E:H:M', 'P:E:I:K', 'P:E:I:L',
        'P:E:I:V', 'P:E:J:U', 'P:E:K:R', 'P:E:K:U', 'P:E:L:M', 'P:E:L:N',
        'P:E:L:T', 'P:E:M:R', 'P:F:G:I', 'P:F:I:O', 'P:F:I:R', 'P:F:L:M',
        'P:F:L:T', 'P:F:O:T', 'P:F:R:T', 'P:G:I:L', 'P:G:I:S', 'P:G:O:S',
        'P:H:I:L', 'P:H:I:U', 'P:H:K:L', 'P:H:K:S', 'P:H:L:N', 'P:H:L:R',
        'P:H:L:S', 'P:H:M:N', 'P:H:M:R', 'P:H:M:S', 'P:H:M:T', 'P:H:N:R',
        'P:H:R:U', 'P:H:R:W', 'P:H:S:U', 'P:H:T:U', 'P:I:K:M', 'P:I:K:T',
        'P:I:K:U', 'P:I:L:N', 'P:I:L:R', 'P:I:L:U', 'P:I:L:V', 'P:I:M:S',
        'P:I:N:Y', 'P:I:S:W', 'P:I:S:Y', 'P:I:T:U', 'P:K:L:O', 'P:K:L:U',
        'P:K:M:U', 'P:K:O:R', 'P:K:O:U', 'P:K:R:T', 'P:K:R:U', 'P:K:S:T',
        'P:K:S:U', 'P:K:T:U', 'P:L:M:O', 'P:L:N:O', 'P:L:N:R', 'P:L:N:T',
        'P:L:O:R', 'P:L:S:V', 'P:L:T:U', 'P:M:N:T', 'P:M:R:S', 'P:M:R:U',
        'P:N:O:U', 'P:N:O:Y', 'P:N:R:U', 'P:O:R:W', 'P:O:S:V', 'P:R:S:W',
        'Q:A:B:N', 'Q:A:C:I', 'Q:A:C:L', 'Q:A:C:U', 'Q:A:E:L', 'Q:A:E:M',
        'Q:A:E:N', 'Q:A:E:U', 'Q:A:I:O', 'Q:A:I:S', 'Q:A:L:N', 'Q:A:L:O',
        'Q:A:M:O', 'Q:A:M:S', 'Q:A:N:T', 'Q:A:O:S', 'Q:A:O:T', 'Q:B:E:S',
        'Q:B:I:L', 'Q:B:I:S', 'Q:B:N:O', 'Q:B:N:S', 'Q:C:D:I', 'Q:C:E:L',
        'Q:C:H:N', 'Q:C:I:L', 'Q:C:L:U', 'Q:C:M:N', 'Q:C:N:S', 'Q:C:N:T',
        'Q:C:N:U', 'Q:D:I:N', 'Q:E:I:N', 'Q:E:I:O', 'Q:E:I:S', 'Q:E:I:U',
        'Q:E:L:O', 'Q:E:L:U', 'Q:E:M:N', 'Q:E:N:O', 'Q:E:N:S', 'Q:E:N:U',
        'Q:I:L:O', 'Q:I:N:U', 'Q:I:O:U', 'Q:L:N:O', 'Q:L:O:U', 'Q:M:N:O',
        'Q:M:N:S', 'Q:M:N:U', 'Q:N:O:S', 'Q:N:O:T', 'Q:N:O:U', 'R:B:I:W',
        'R:B:J:Y', 'R:B:N:W', 'R:B:P:Q', 'R:B:S:Z', 'R:C:K:X', 'R:C:K:Z',
        'R:C:M:W', 'R:C:P:W', 'R:C:W:Z', 'R:D:G:W', 'R:D:J:Z', 'R:D:K:Z',
        'R:D:Q:Z', 'R:D:W:Z', 'R:F:J:N', 'R:F:M:Z', 'R:F:S:W', 'R:F:T:Z',
        'R:G:H:Z', 'R:G:P:Q', 'R:G:P:Z', 'R:G:W:Z', 'R:H:J:S', 'R:I:J:K',
        'R:I:K:X', 'R:I:M:W', 'R:I:X:Y', 'R:I:Y:Z', 'R:J:M:Q', 'R:J:N:Z',
        'R:J:Q:U', 'R:J:S:X', 'R:J:S:Z', 'R:J:T:X', 'R:J:T:Y', 'R:J:U:X',
        'R:K:L:X', 'R:K:M:Q', 'R:K:N:X', 'R:K:Q:S', 'R:K:S:W', 'R:K:T:V',
        'R:K:U:X', 'R:K:V:W', 'R:K:W:Z', 'R:L:V:W', 'R:L:W:Z', 'R:L:Y:Z',
        'R:M:N:W', 'R:M:S:W', 'R:M:U:W', 'R:M:W:Z', 'R:N:Q:Z', 'R:N:V:W',
        'R:N:V:X', 'R:N:W:Z', 'R:O:V:W', 'R:O:V:X', 'R:O:W:Z', 'R:P:Q:X',
        'R:P:U:W', 'R:T:V:W', 'S:C:K:X', 'S:K:L:X', 'S:K:X:Y', 'T:F:J:L',
        'T:F:J:M', 'T:F:M:Z', 'T:G:K:P', 'T:G:P:Z', 'T:H:J:Y', 'T:J:K:M',
        'T:K:O:Q', 'T:K:Q:R', 'T:P:Q:X', 'T:P:V:Z', 'T:R:V:Z', 'U:A:S:W',
        'U:B:E:K', 'U:B:F:K', 'U:B:J:L', 'U:B:L:P', 'U:B:N:P', 'U:B:O:P',
        'U:B:P:T', 'U:B:Q:R', 'U:B:Q:T', 'U:B:R:Y', 'U:B:S:Y', 'U:B:T:Z',
        'U:C:E:Z', 'U:C:F:L', 'U:C:H:Y', 'U:C:J:K', 'U:C:K:O', 'U:C:L:Z',
        'U:C:M:Y', 'U:C:N:Q', 'U:C:O:Z', 'U:C:R:Y', 'U:D:H:M', 'U:D:H:Y',
        'U:D:I:Z', 'U:D:J:M', 'U:D:J:T', 'U:D:P:Y', 'U:D:T:Y', 'U:D:V:Z',
        'U:E:G:J', 'U:E:G:Y', 'U:E:I:X', 'U:E:J:L', 'U:E:J:Q', 'U:E:L:Z',
        'U:E:O:X', 'U:E:P:Q', 'U:F:G:L', 'U:F:G:N', 'U:F:K:N', 'U:F:L:S',
        'U:F:L:V', 'U:F:M:O', 'U:F:O:V', 'U:F:P:S', 'U:F:R:V', 'U:F:T:V',
        'U:G:H:L', 'U:G:H:M', 'U:G:H:O', 'U:G:H:T', 'U:G:H:Y', 'U:G:J:O',
        'U:G:J:T', 'U:G:M:S', 'U:G:M:Y', 'U:G:N:Y', 'U:G:R:Y', 'U:G:S:Y',
        'U:G:T:Z', 'U:H:K:N', 'U:H:K:S', 'U:H:N:Y', 'U:H:R:S', 'U:H:T:Y',
        'U:I:J:L', 'U:I:K:P', 'U:I:K:T', 'U:I:M:Y', 'U:I:N:Y', 'U:I:O:X',
        'U:I:O:Y', 'U:I:R:Y', 'U:J:L:N', 'U:J:L:R', 'U:J:M:Q', 'U:J:N:Q',
        'U:J:N:V', 'U:J:O:Q', 'U:J:O:V', 'U:J:Q:R', 'U:J:R:S', 'U:K:M:O',
        'U:K:O:T', 'U:K:P:R', 'U:K:P:S', 'U:K:R:S', 'U:L:O:X', 'U:L:Q:R',
        'U:L:Q:T', 'U:M:N:Z', 'U:M:P:Y', 'U:M:S:Y', 'U:N:O:W', 'U:N:P:Y',
        'U:N:Q:T', 'U:N:T:Z', 'U:N:V:Z', 'U:O:Q:S', 'U:O:S:Y', 'U:O:S:Z',
        'U:O:T:Z', 'U:O:W:Z', 'U:P:Q:R', 'U:P:T:Y', 'U:P:T:Z', 'U:Q:R:T',
        'U:R:S:Y', 'U:R:V:Z', 'U:S:T:Y', 'U:S:T:Z', 'V:A:L:S', 'V:C:I:N',
        'V:C:I:O', 'V:C:N:O', 'V:E:L:O', 'V:H:I:S', 'V:H:K:S', 'V:H:L:S',
        'V:I:K:O', 'V:I:O:S', 'V:K:L:O', 'V:L:O:S', 'W:A:I:R', 'W:C:H:R',
        'W:C:O:S', 'W:C:R:S', 'W:G:N:O', 'W:H:O:R', 'W:O:R:S', 'X:B:G:T',
        'X:B:H:M', 'X:B:J:R', 'X:B:J:T', 'X:B:K:R', 'X:B:O:Z', 'X:B:S:V',
        'X:C:I:W', 'X:C:K:R', 'X:C:K:Y', 'X:D:F:Y', 'X:D:H:V', 'X:D:J:Q',
        'X:D:J:V', 'X:D:K:T', 'X:D:P:Q', 'X:D:P:Z', 'X:D:R:Z', 'X:D:T:Z',
        'X:E:J:Q', 'X:F:I:K', 'X:F:K:O', 'X:F:K:T', 'X:F:L:Q', 'X:F:O:Q',
        'X:F:O:Y', 'X:F:Q:R', 'X:F:S:Y', 'X:G:J:R', 'X:G:K:N', 'X:G:Q:R',
        'X:G:Q:S', 'X:H:K:L', 'X:H:K:N', 'X:H:K:O', 'X:H:K:T', 'X:H:L:Q',
        'X:H:O:Q', 'X:H:P:Z', 'X:H:Q:R', 'X:H:Q:S', 'X:H:S:V', 'X:H:V:Y',
        'X:I:K:N', 'X:I:K:P', 'X:I:K:R', 'X:I:P:Z', 'X:I:Y:Z', 'X:J:L:N',
        'X:J:M:Q', 'X:J:M:S', 'X:J:N:Q', 'X:J:O:Q', 'X:J:P:T', 'X:J:Q:R',
        'X:J:S:T', 'X:J:T:Y', 'X:K:M:R', 'X:K:N:U', 'X:K:O:P', 'X:K:O:R',
        'X:K:O:T', 'X:K:O:Y', 'X:L:V:Y', 'X:M:O:Z', 'X:M:P:Q', 'X:M:Q:T',
        'X:M:R:Z', 'X:M:Y:Z', 'X:O:P:Q', 'X:P:Q:T', 'X:P:R:Z', 'X:P:V:Y',
        'X:P:Y:Z', 'X:R:Y:Z', 'X:S:V:Y', 'X:T:Y:Z', 'Y:A:C:U', 'Y:A:D:X',
        'Y:A:H:U', 'Y:A:J:K', 'Y:A:J:O', 'Y:A:K:L', 'Y:A:N:U', 'Y:A:O:W',
        'Y:A:P:U', 'Y:A:R:X', 'Y:A:S:U', 'Y:A:S:V', 'Y:A:T:U', 'Y:B:C:H',
        'Y:B:C:I', 'Y:B:C:K', 'Y:B:C:L', 'Y:B:C:M', 'Y:B:C:N', 'Y:B:C:R',
        'Y:B:C:U', 'Y:B:E:P', 'Y:B:F:S', 'Y:B:F:U', 'Y:B:G:H', 'Y:B:G:N',
        'Y:B:H:M', 'Y:B:H:R', 'Y:B:H:U', 'Y:B:I:K', 'Y:B:I:N', 'Y:B:I:W',
        'Y:B:K:L', 'Y:B:K:O', 'Y:B:L:N', 'Y:B:L:T', 'Y:B:L:U', 'Y:B:M:N',
        'Y:B:M:R', 'Y:B:M:U', 'Y:B:O:S', 'Y:B:R:S', 'Y:B:S:U', 'Y:C:D:N',
        'Y:C:D:O', 'Y:C:D:R', 'Y:C:E:F', 'Y:C:F:R', 'Y:C:H:M', 'Y:C:I:S',
        'Y:C:J:O', 'Y:C:J:S', 'Y:C:K:L', 'Y:C:L:V', 'Y:C:M:P', 'Y:C:N:V',
        'Y:C:O:V', 'Y:C:P:R', 'Y:C:P:S', 'Y:C:P:U', 'Y:C:S:V', 'Y:C:T:V',
        'Y:D:H:R', 'Y:D:H:S', 'Y:D:H:X', 'Y:D:I:O', 'Y:D:I:T', 'Y:D:I:X',
        'Y:D:L:N', 'Y:D:L:P', 'Y:D:L:S', 'Y:D:N:O', 'Y:D:O:P', 'Y:D:O:X',
        'Y:D:R:S', 'Y:D:R:X', 'Y:E:F:O', 'Y:E:G:H', 'Y:E:H:L', 'Y:E:H:P',
        'Y:E:H:V', 'Y:E:I:J', 'Y:E:I:K', 'Y:E:I:W', 'Y:E:I:X', 'Y:E:J:O',
        'Y:E:K:N', 'Y:E:K:W', 'Y:E:Q:U', 'Y:E:R:W', 'Y:E:R:X', 'Y:E:S:V',
        'Y:E:T:Z', 'Y:F:I:R', 'Y:F:N:S', 'Y:F:N:T', 'Y:F:O:R', 'Y:F:O:S',
        'Y:F:O:U', 'Y:F:R:S', 'Y:F:S:T', 'Y:F:S:U', 'Y:G:H:S', 'Y:G:I:O',
        'Y:G:L:S', 'Y:G:L:T', 'Y:G:L:U', 'Y:G:M:T', 'Y:G:N:U', 'Y:G:N:V',
        'Y:G:O:S', 'Y:G:O:T', 'Y:G:O:U', 'Y:G:O:V', 'Y:G:P:S', 'Y:G:S:V',
        'Y:G:T:U', 'Y:H:I:V', 'Y:H:I:X', 'Y:H:K:P', 'Y:H:L:M', 'Y:H:L:P',
        'Y:H:L:T', 'Y:H:M:P', 'Y:H:M:R', 'Y:H:M:U', 'Y:H:N:P', 'Y:H:N:V',
        'Y:H:O:P', 'Y:H:O:U', 'Y:H:O:V', 'Y:H:P:R', 'Y:H:P:U', 'Y:H:R:U',
        'Y:H:R:V', 'Y:H:S:U', 'Y:H:S:V', 'Y:H:T:U', 'Y:H:T:V', 'Y:I:J:S',
        'Y:I:K:L', 'Y:I:K:O', 'Y:I:K:R', 'Y:I:L:V', 'Y:I:M:T', 'Y:I:M:U',
        'Y:I:N:P', 'Y:I:N:S', 'Y:I:O:S', 'Y:I:O:V', 'Y:I:O:W', 'Y:I:O:X',
        'Y:I:P:T', 'Y:I:P:U', 'Y:I:S:T', 'Y:I:S:V', 'Y:I:S:W', 'Y:J:K:O',
        'Y:J:K:U', 'Y:J:N:U', 'Y:J:O:S', 'Y:J:R:S', 'Y:K:L:O', 'Y:K:L:R',
        'Y:K:L:U', 'Y:K:N:O', 'Y:K:O:U', 'Y:K:P:U', 'Y:K:R:T', 'Y:K:R:U',
        'Y:K:S:T', 'Y:L:M:R', 'Y:L:M:S', 'Y:L:M:T', 'Y:L:N:R', 'Y:L:R:W',
        'Y:L:T:U', 'Y:M:N:P', 'Y:M:O:S', 'Y:M:P:R', 'Y:M:P:S', 'Y:M:P:T',
        'Y:M:P:U', 'Y:M:S:U', 'Y:M:T:U', 'Y:N:P:U', 'Y:O:S:V', 'Y:O:U:V',
        'Y:P:R:X', 'Y:P:S:U', 'Y:Q:R:U', 'Y:R:S:V', 'Y:R:T:X', 'Y:R:T:Z',
        'Y:R:U:V', 'Y:S:T:U', 'Y:S:T:V', 'Z:B:C:W', 'Z:B:E:W', 'Z:B:P:Q',
        'Z:D:H:W', 'Z:E:H:W', 'Z:G:K:P', 'Z:G:P:Q', 'Z:H:J:K', 'Z:H:J:M',
        'Z:H:K:M', 'Z:H:K:Y', 'Z:H:L:Q', 'Z:H:N:W', 'Z:H:O:W', 'Z:H:T:W',
        'Z:J:K:M', 'Z:J:S:Y', 'Z:J:T:X', 'Z:J:U:X', 'Z:K:M:Y', 'Z:K:N:V',
        'Z:K:O:W', 'Z:K:P:U', 'Z:K:S:W', 'Z:K:T:W', 'Z:N:U:W', 'Z:N:V:X',
        'Z:O:T:W', 'Z:O:V:X', 'Z:P:Q:X', 'Z:P:Q:Y', 'Z:P:S:W', 'Z:Q:T:X',
        'Z:S:U:W', 'Z:S:V:W', 'Z:U:V:X',
    ];

    /**
     * Doublons de contenu CROISES avec une famille EXTERIEURE (D-045, meme discipline D-041) --
     * voir docs/DECISIONS.md D-045.
     *
     * @var list<string>
     */
    private const EXTERNAL_DUPLICATE_KEYS = [];

    public function __construct(
        private readonly Connection $connection,
    ) {
    }

    public function build(string $suffix, string $letter1, string $letter2): SuffixAvecThreeLettersLinks
    {
        $pair = [$letter1, $letter2];
        sort($pair, SORT_STRING);
        [$x, $y] = $pair;

        $statement = $this->connection->pdo()->prepare(
            "SELECT list_key, count FROM list_counts WHERE list_type = 'end_with_triple'"
            . ' AND (list_key LIKE ? OR list_key LIKE ? OR list_key LIKE ?)'
        );
        $statement->execute([
            $suffix . ':' . $x . ':' . $y . ':%',
            $suffix . ':' . $x . ':%:' . $y,
            $suffix . ':%:' . $x . ':' . $y,
        ]);

        $links = [];

        foreach ($statement as $row) {
            $key = (string) $row['list_key'];

            if (
                in_array($key, self::DUPLICATE_PARENT_KEYS, true)
                || in_array($key, self::SIBLING_DUPLICATE_KEYS, true)
                || in_array($key, self::EXTERNAL_DUPLICATE_KEYS, true)
            ) {
                continue;
            }

            $parts = explode(':', $key, 4);
            $triple = [$parts[1], $parts[2], $parts[3]];

            $partner = null;
            foreach ($triple as $candidate) {
                if ($candidate !== $x && $candidate !== $y) {
                    $partner = $candidate;
                    break;
                }
            }

            if ($partner === null) {
                continue;
            }

            $count = (int) $row['count'];
            $path = 'terminant/' . strtolower($suffix) . '/avec/' . strtolower($x) . '/' . strtolower($y) . '/' . strtolower($partner);
            $url = WordListFilters::fromPath($path)?->canonicalUrl();

            if ($url !== null) {
                $links[] = ['letter' => $partner, 'url' => $url, 'count' => $count];
            }
        }

        usort($links, static fn (array $a, array $b): int => $a['letter'] <=> $b['letter']);

        return new SuffixAvecThreeLettersLinks(links: $links, queryCount: 1);
    }
}
